TACC/Core-Portal

server/requirements.txt
* [FP-723](https://jira.tacc.utexas.edu/browse/FP-723)
1. docker system prune -a
2. docker volume prune
3. docker image prune -a
4. make build
5. make start
6. Re-run collectstatic and migrate on frontera_prtl_cms and frontera_prtl_django
I believe an unpinned dependency in celery 4.3.0 was causing an import error related to vine, which resulted in other things (such as daphne) not working.
=> Pinning celery to 4.4.7 to resolve dependency issue

server/portal/apps/onboarding/execute.py, server/portal/apps/onboarding/execute_unit_test.py, server/portal/apps/onboarding/steps/abstract.py, server/portal/apps/onboarding/steps/abstract_unit_test.py, server/portal/settings/settings.py, server/portal/settings/settings_secret.example.py, server/portal/settings/unit_test_settings.py, server/requirements.txt
* [FP-500](https://jira.tacc.utexas.edu/browse/FP-500)
* [FP-669](https://jira.tacc.utexas.edu/browse/FP-669)
- PORTAL_USER_ACCOUNT_SETUP_STEPS is no longer in settings_secret, values should be explicit in settings.py
- PORTAL_USER_ACCOUNT_SETUP_STEPS format has changed from list of strings to list of dicts: 
```
{
'step': 'step.package.file_name.ClassName', 
'settings': { 'key': 'value' }
}
```
- Settings are now automatically loaded and can be accessed from within step processing code using the `settings` attribute, rather than loading a specific key from django.conf settings. This should reduce proliferation of settings unique to each step.
- abstract_unit_test.py refactored to pytest
1. Unit tests only
=> task/FP-500 - refactor onboarding settings

server/conf/nginx/nginx.conf, server/portal/apps/accounts/managers/unit_test.py, server/portal/apps/accounts/views.py, server/portal/apps/auth/unit_test.py, server/portal/apps/auth/views.py, server/portal/apps/onboarding/middleware.py, server/portal/apps/onboarding/templates/portal/apps/onboarding/admin.html, server/portal/apps/onboarding/templates/portal/apps/onboarding/setup.html, server/portal/apps/tickets/unit_test.py, server/portal/apps/tickets/views.py, server/portal/settings/settings.py
* [FP-702](https://jira.tacc.utexas.edu/browse/FP-702)
* [FP-669](https://jira.tacc.utexas.edu/browse/FP-669)
- The onboarding check is now enabled and performed during the agave auth callback, before Allocations are cached and additional private systems such as Longhorn are created.
- PORTAL_USER_ACCOUNT_SETUP_STEPS has not been refactored yet, and still exists in settings_secret.py. This is addressed in a different PR.
- Ticket creation routing for /tickets/new/ has had the logic altered. Users who have not completed onboarding (and had setup_complete = True) will not be redirected to the workbench when trying to access /tickets/new/. Users who are not setup_complete will not be allowed access to the dashboard
- The onboarding route is now enabled in nginx.conf for local docker dev …
=> task/FP-702 - onboarding -- refactor for cepv2

client/package.json, client/src/utils/timeFormat.js, client/src/utils/timeFormat.test.js
Fix for displaying job times using the client's time zone and not assuming CST.
* [FP-760](https://jira.tacc.utexas.edu/browse/FP-760)
* Fix for displaying job times using the client's time zone and not assuming CST.
* Add unit test
1. Run unit tests
2. When this is merged, we should test dev again (with our time zone set to non-central zone)
Here, I set the time zone to be CST for our tests. This is done in the `client/package.json`:  _"test": "TZ=America/Chicago jest"_  An alternative would be to set the time zone in the the jest global-setup.js as outlined here:  https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config?answertab=votes#tab-top
=> FP-760 Show time according to client's time zone

client/src/components/History/HistoryBadge/HistoryBadge.js, client/src/components/History/HistoryBadge/HistoryBadge.module.scss, client/src/components/Onboarding/Onboarding.js, client/src/components/Sidebar/Sidebar.js, client/src/components/Sidebar/Sidebar.module.scss
Update on-boarding ui to include disabled property to sidebar.  
This is related to but will require follow on work:
* [FP-768](https://jira.tacc.utexas.edu/browse/FP-768)
* Make sidebar disabled-able
* Use sidebar in onboarding view
1. View onboarding view and compare with UI mockups 
This PR just adds a disabled sidebar to current onboarding path.  A second PR will be submitted where onboarding route (`/onboarding`) is moved under (`/workbench`)
=> Task/FP-768: add disabled property to sidebar

client/src/components/ManageAccount/ManageAccountTables.js, server/portal/apps/licenses/templates/portal/apps/licenses/matlab_details.html
Change default blue <a> tag links in the license modal template to purple.
* [FP-659](https://jira.tacc.utexas.edu/browse/FP-659)
1. Navigate to your user account page and click the "Request Activation" link next to MATLAB on the right
2. Check that both of the links in the modal are now purple instead of blue
=> Task/FP-659 - Change default blue links in license modal to purple

README.md, client/src/components/_common/Message/Message.js, client/src/components/_common/Message/Message.test.js
Make prior `<Message>` usage emit logging less loud than a `console.warn`.
* [FP-639](https://jira.tacc.utexas.edu/browse/FP-639)
- _Minor_: Change two `console.warn`'s to `console.info`'s
- _Minor_: Update `README.md` with note about how to silence logging in tests.
1. Run `npm run test`.
1. See **info** logging about `Message` usage.
1. Run `npm run test -- --silent`.
1. See **no** logging about `Message` usage.
__`npm run test`__
__`npm run test -- --silent`__
=> Quick: Reduce <Message> `warn`'s to `info`'s

client/src/index.css
The "Back" button for file navigation when moving/copying files was not the correct color. We decided to put this in a smaller PR to get it merged in more quickly.
* [FP-601](https://jira.tacc.utexas.edu/browse/FP-601)
1. Select a file for copying
2. Navigate into a directory on your storage system; the back button should be purple and not blue.
=> Task/FP-601 - Correct color of back button in file navigation

client/src/components/DataFiles/DataFilesModals/DataFilesMkdirModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesPushKeysModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesRenameModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesTrashModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesUploadModal.js
Most of the updated modals handle file operations in the datafiles area. Craig reported that the modals which have an exit button on the top right should **not** have a "Close" button on the bottom.
* [FP-604](https://jira.tacc.utexas.edu/browse/FP-604)
Removed close buttons from modals
1. Open the modals; a "Close" button should not exist.
2. Within the Preview modal, the entire footer and button was removed.
=> Task/FP-604 - Remove "close" buttons from modals with X button

client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.scss, client/src/components/Sidebar/Sidebar.js, server/portal/settings/settings_secret.example.py
Uses the existing `_PORTAL_DATAFILES_STORAGE_SYSTEMS` secret setting to list Shared Workspaces (Projects) in the Data Files sidebar.
* [FP-805](https://jira.tacc.utexas.edu/browse/FP-805)
- Fixes active state of main sidebar when viewing a child view (i.e. `allocations/active`)
- Uses the `findSystemDisplayName` function as the default to set the root of data files breadcrumbs
- Projects are listed in the datefiles sidebar only if entered into the `_PORTAL_DATAFILES_STORAGE_SYSTEMS` secret setting
1. Make the following block appear in `settings_secret.py`
```
_PORTAL_DATAFILES_STORAGE_SYSTEMS = [
{
'name': 'Community Data',
'system': _AGAVE_COMMUNITY_DATA_SYSTEM,
'scheme': 'community',
'api': 'tapis',
'icon': None
},
{
'name': 'Shared Workspaces',
'scheme': 'projects',
'api': 'tapis', …
```
=> task/FP-805: Configurable projects

client/src/components/Applications/AppForm/AppForm.scss
Tweak UI of small PR that did not previously edit CSS.
* [FP-597](https://jira.tacc.utexas.edu/browse/FP-597)
- __Fix__: Remove the undesirable padding (which was usually invisible before¹²).
¹ The use of `<Sectionmessage>` makes the padding visible.
² Before, the padding was invisible on most screens, cuz message is short.
1. Load app to which you have no access.
- Check that `<SectionMessage>` does not have extra horizontal negative space.
1. Successfully submit a job.
- Check that `<SectionMessage>` does not have extra horizontal negative space.
1. Load app that cannot be loaded.
- Check that `<SectionMessage>` looks the same (space removal is not a visible change).
- __App No Access__
- __App No Load__
- __App Job Submit Success__
(no image, change is identical to "App No Load")
I add …
=> FP-597: Reduce horizontal padding on appDetail container

client/src/components/Applications/AppForm/AppForm.js, client/src/components/Applications/AppForm/AppForm.scss
Swapped out "Alert" component to "Message" component in the Applications area. I noticed the old alert message was dismissible with an X button, and the new messages will not be. Hopefully that is the intended behavior. 
* [FP-597](https://jira.tacc.utexas.edu/browse/FP-597)
1. Head to the applications page and create a job on a system where you have an allocation and one without. You should see either success/error messages.
=> task/FP-597 - Swap Alert component to Message component in applications

client/src/components/DataFiles/DataFilesModals/DataFilesShowPathModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesShowPathModal.test.js, client/src/components/DataFiles/fixtures/DataFiles.systems.fixture.js, client/src/components/_common/TextCopyField/TextCopyField.js, client/src/redux/reducers/datafiles.reducers.js, client/src/redux/sagas/datafiles.sagas.js, server/conftest.py, server/portal/apps/datafiles/urls.py, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py
Fix view path for projects by retrieving project system definitions
* [FP-213](https://jira.tacc.utexas.edu/browse/FP-213)
* [FP-692](https://jira.tacc.utexas.edu/browse/FP-692)
- Added /api/systems/definitions/<str:system> end point
- Reducer now keeps a list of other system definitions (in addition to the systemList for the sidebar)
- DataFilesShowPathModal retrieves system definition of viewed system
1. 
- Needs tests and to fix broken tests
=> bugfix task/FP-811: Fix View Path modal for project systems

client/src/components/Dashboard/Dashboard.scss, client/src/components/DataFiles/DataFilesListing/DataFilesListingCells.js, client/src/components/DataFiles/DataFilesModals/DataFilesModals.scss, client/src/components/DataFiles/DataFilesModals/DataFilesShowPathModal.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.scss, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.js, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.module.scss, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss, client/src/redux/sagas/datafiles.sagas.js, server/portal/apps/datafiles/urls.py, server/portal/apps/datafiles/views.py
CSS tweaks to projects layout in data files modals
- I opted to leave the shared workspace file listing header above the normal height of the listing, as it could make sense for headers to be higher. However, I couldn't remove the outline of the header, since it is a child element of the container that has the outline.
- This addresses the long project name overflow problem
=> Projects: tweak modal layout

client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.js, client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/redux/reducers/projects.reducers.js, client/src/redux/reducers/users.reducers.js
Fixes the following:
Frank: Selecting "Add user" but not filling in any characters seems to pull a list of everyone on the Frontera portal – or at least a list of people from a lot of different institutions.
Owais: If you're unable to create a workspace, the error message persists after closing the modal and then re-opening it
* [FP-823](https://jira.tacc.utexas.edu/browse/FP-823)
- Added reducers and dispatches to clear stale user search data and stale project operation data when loading manage team and Add Shared Workspace modals
1. Force an error on project creation - this is easiest done  in the shell by:
```
from portal.apps.projects.models import ProjectId
ProjectId.objects.all().delete()
```
2. Try to Add a Shared Workspace - this will fail and an error message will appear.
3. …
=> bug/FP-823 Project add user list shows all users, project creation failure persists

Makefile
Allows automation of using git tags, such as a release tag (`v1.0.0`), as the docker image tag. If the commit being built does not have a tag, the branch name is used as the tag.
This will come in handy when using camino v2, as we can anticipate the docker image tag when making the release for the portal.
* [FP-838](https://jira.tacc.utexas.edu/browse/FP-838)
=> task/FP-838: allow git tags as docker image tags

client/.stylelintrc.js, client/src/components/_common/TextCopyField/TextCopyField.js, client/src/components/_common/TextCopyField/TextCopyField.module.scss
Polish UI of PR #293.
* [FP-817](https://jira.tacc.utexas.edu/browse/FP-817)
- _Minor_: Allow multi-line values in CSS.
- __New__: Separate class name from state logic.
- __Fix__: Configurable values for transition duration and state duration.
- _Minor_: Remove need for access to the actual click `event` (by using `type="button"`).
- __New__: Change icon on copy, and revert.
- _Minor_: Remove redundant `display: flex` (by removing `root` class name).
- __New__: Use CSS transition instead of CSS animation.
- __New__: Use CSS global variables for color.
- __Fix__: (Minutia) Prevent Bootstrap styles from breaking color change.
1. See PR #293.
1. **Basic Test.** Click on Copy Link and move mouse away quickly.
1. See immediate change of icon: 🔗  → ✔️ 
1. See 0.15s transition from background …
=> Task/fp 817 textcopyfield enhancements  polish

server/portal/apps/workspace/api/views.py
Fixed HTML app loading
* [FP-825](https://jira.tacc.utexas.edu/browse/FP-825)
Add "appType" field to HTML app definition response from backend
1. In your container, make a categories.json fixture:
```
[{"model": "workspace.apptraycategory", "pk": 1, "fields": {"category": "Data Processing", "priority": 0}}, {"model": "workspace.apptraycategory", "pk": 2, "fields": {"category": "Simulation", "priority": 0}}, {"model": "workspace.apptraycategory", "pk": 3, "fields": {"category": "Visualization", "priority": 0}}]
```
2. In your container, make an apps.json fixture with the viz portal HTML app:
```
[{"model": "workspace.apptrayentry", "pk": 5, "fields": {"name": "", "label": "TACC Visualization Portal", "icon": "", "version": "1.0", "revision": "", "appId": "", "lastRetrieved": "", "appType": …
```
=> task/FP-825 - Fix HTML app loading

client/src/components/DataFiles/DataFilesListing/DataFilesListing.js
Prevents View Path column from showing up in Google Drive (and other non-tapis) Data Files views.
* [FP-815](https://jira.tacc.utexas.edu/browse/FP-815)
Add check that allows View Path to only show up for tapis API data files views
1. Link Google Drive
2. Verify that View Path column does not exist
Issues related to TextCopyField feedback will be addressed in https://jira.tacc.utexas.edu/browse/FP-817
Issues related to View Path splitting into two lines, as well as other data files columns, will be addressed in https://jira.tacc.utexas.edu/browse/FP-818
=> task/FP-815 - prevent View Path from appearing when browsing Google Drive

client/src/components/DataFiles/DataFiles.module.css, client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.js, client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.scss
- Add Shared Workspaces breadcrumb link
- Fix long shared workspaces title pushing toolbar to new line
* [FP-824](https://jira.tacc.utexas.edu/browse/FP-824)
* [FP-841](https://jira.tacc.utexas.edu/browse/FP-841)
* [FP-844](https://jira.tacc.utexas.edu/browse/FP-844)
1. Make a long project title
2. Make sure it displays correctly
3. Make sure you can click the Shared WOrkspaces link and go back to shared workspaces listing
=> bug/FP-841 - Add shared workspaces link in breadcdumbs, fix long titles in breadcrumbs

client/src/components/_common/DescriptionList/DescriptionList.js, client/src/components/_common/DescriptionList/DescriptionList.test.js
An array is currently incorrectly rendering as a concatenated single `<dd>` element, rather than multiple stacked `<dd>` elements. This allows for multiple `<dd>` elements when value data is an Array.
* [FP-831](https://jira.tacc.utexas.edu/browse/FP-831)
1. Run a job with multiple inputs, like compress or zippy
2. View the job detail modal in History
3. Confirm data displays correctly as multiple value elements under the key
Before:
After:
=> bug/FP-831: Allow multiple <dd> elements when data is Array in DescriptionList

client/src/components/Tickets/TicketCreateForm.js, client/src/components/Tickets/TicketCreateForm.scss, client/src/components/Tickets/TicketCreateModal.scss
Addresses style issues with TicketCreateModal from December 1st, 2020 testing session
* [FP-835](https://jira.tacc.utexas.edu/browse/FP-835)
- (minor) new ticket modal: no space beneath bottom of form and modal on short height modal - Wes (see Screenshots #1)
- (minor) new ticket modal: no space between button loading icon and button text- Wes (see Screenshots #2)
- Add ticket modal message when a ticket was successfully created looks kinda bad due to text/wrapping justification 
(see Screenshots #7)  - Nathan
1. Shrink your window size
2. Submit a ticket
Spacing between loading icon and button text:
Space between submit button and bottom of modal when modal is short
Space between ticket create information and submit button when modal is narrow
=> bug/FP-835 - ticket create modal UI fixes

client/.stylelintrc.js, client/src/components/_common/TextCopyField/TextCopyField.js, client/src/components/_common/TextCopyField/TextCopyField.module.scss
TextCopyField now uses button style transitions to indicate text was copied
* [FP-817](https://jira.tacc.utexas.edu/browse/FP-817)
- TextCopyField javascript for state changes
- Transitions from @tacc-wbomar via https://github.com/TACC/Frontera-Portal/pull/310
1. Create a link for a file
2. Use the copy button
https://user-images.githubusercontent.com/17181582/104609288-7fff3d80-5648-11eb-9df0-8c9513da0a3a.mov
=> task/FP-817 - TextCopyField user feedback

client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.js
Disables Create Link functionality for non-private systems
* [FP-850](https://jira.tacc.utexas.edu/browse/FP-850)
* [FP-856](https://jira.tacc.utexas.edu/browse/FP-856)
- Restrict View Link to private and projects schemes
1. Browse to My Data and make sure View Link is there
2. Browse to Community Data and make sure View Link is not there
An outstanding issue was identified. Currently, any user on a Shared Workspace may create links. This creates a potential situation where a user could be removed, invalidating created links.
[FP-856](https://jira.tacc.utexas.edu/browse/FP-856)
=> bug/FP-850 - Disable make link on community and public data

server/portal/utils/jwt_auth.py
Remove a comma that was causing an error with JWT Auth. This is required for jupyter mounts.
* [FP-867](https://jira.tacc.utexas.edu/browse/FP-867)
Remove a comma (probably a Django 2 compatibility problem)
1. This code must be deployed to dev.cep.tacc.utexas.edu. Unfortunately, it is very difficult to test this locally since you need a signed JWT from agave.
2. Sign in to dev.cep.tacc.utexas.edu and make sure you can access community data
3. portal-mounts-staging and staging.jupyter.tacc.cloud are currently configured to ask dev.cep.tacc.utexas.edu for mounts
4. Log in to staging.jupyter.tacc.cloud and make sure you can see dev.cep's community data
This error was detected due to this exception occuring during jupyter mounts jwt authentication:
```
[DJANGO] ERROR 2021-01-26 16:46:55,824 …
```
=> bug/FP-867 - Fix JWT Auth

server/portal/apps/projects/views.py, server/portal/apps/projects/views_unit_test.py
The Projects endpoint was not actually calling the ACLs app for each member on a new project. It was only adding them to the local metadata records. This fixes that
* [FP-868](https://jira.tacc.utexas.edu/browse/FP-868)
- Call ProjectManager.add_member for each included member on a new project
- Unit tests
1. Create a project with more than one member. You may have to use a test account
2. Log in to data.tacc.utexas.edu and locate your project folder
3. Check ACLs to make sure each member has been added to that folder. It may take a minute for the ACL app to run for every member
4. Try removing additional members to make sure the ACL app runs (optional)
=> bug/FP-868 - Set project ACLs for each member on creation

client/src/utils/systems.js
Correctly map corral system names to Corral
* [FP-653](https://jira.tacc.utexas.edu/browse/FP-653)
The Corral system name cannot be derived from the first part of the hostname. (data.tacc, cloud.corral, secure.corral.) This adds explicit mappings.
1. Go to Allocations view
2. Select an allocation and user that has an allocation on Corral
=> bug/FP-653 - Add explicit mapping for Corral system name

client/src/redux/reducers/datafiles.reducers.js, client/src/redux/sagas/datafiles.sagas.js, client/src/redux/sagas/datafiles.sagas.test.js
Handle possible errors during a data-files-scrolling request
* [FP-803](https://jira.tacc.utexas.edu/browse/FP-803).  That ticket was created for the request causing an error which has already been fixed by @jarosenb .  This is just a follow up for handing any future errors.
* Handle possible errors during a data-files-scrolling request in saga
* Add saga unit test
Add to `listing` in `server/portal/libs/agave/operations.py` (line ~36) to force error on scrolling.
```
if int(offset) > 1:
raise ApiException("dummy")
```
Go to a directory containing enough files (>100) and scroll down to trigger a file listing request.  You should see the error message (in `master`, you would just see a spinner).
=> Handle error during data files scrolling

client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.js, client/src/components/PublicData/PublicData.test.js, client/src/utils/systems.js, client/src/utils/systems.test.js
- Loads project breadcrumb for project title, even when page is refreshed
- Hide trailing "/" after "Shared Workspaces" in breadcrumbs if no project is selected
1. Go to https://cep.dev/workbench/data/tapis/projects/
2. Ensure no trailing `"/"` shows
3. Navigate into a project and ensure `"/"` now shows
4. Refresh page and ensure Project Title still shows in breadcrumbs
=> Shared Workspaces breadcrumb fixes: Load project title on page refresh

client/src/components/_common/Message/Message.js
Improve prop deprecation message to respect component used which generated the message.
* N/A
- ___Fix__: Change `<Message>` warning texts to suggest `<SectionMessage>` or `<InlineMessage>` could have been used.
1. Receive `<Message>` log message.
2. Notice that it is now `<(Section|Inline)Message>` or `<(Section)Message>`.
(skipped)
=> Quick: Clarify Message prop deprecation warning

.github/workflows/main.yml, README.md, client/src/styles/components/c-button.css, docs/index.md
Rename references of branch name `master` to `main`
=> rename master to main

client/src/redux/reducers/datafiles.reducers.js, client/src/redux/reducers/tests/datafiles.reducers.test.js, client/src/redux/sagas/fixtures/systemDefinition.fixture.js
Fixes adding definitions to the `state.definitions.list` via the `addSystemDefinition` function in `datafiles.reducers.js`.
* [FP-896](https://jira.tacc.utexas.edu/browse/FP-896)
* [FP-866](https://jira.tacc.utexas.edu/browse/FP-866)
* [FP-872](https://jira.tacc.utexas.edu/browse/FP-872)
1. Click "View Path" on a file and ensure it works correctly. (Before this PR the app would crash after clicking the button)
=> bug/FP-896: Fix add definition to list

.github/workflows/main.yml
Bump poetry version to fix pipelines
Poetry 1.0.0 breaks existing pipelines. Might still need to look at build configurations on jenkins.
=> quick - Bump poetry version

client/src/components/Onboarding/OnboardingAdmin.js, client/src/components/Onboarding/OnboardingAdmin.module.scss, client/src/components/Onboarding/OnboardingAdminSearchbar.js, client/src/redux/reducers/onboarding.reducers.js, client/src/redux/sagas/fixtures/onboarding.fixture.js, client/src/redux/sagas/onboarding.sagas.js, client/src/redux/sagas/onboarding.sagas.test.js, server/portal/apps/onboarding/api/views.py
Pagination support for onboarding admin
* [FP-935](https://jira.tacc.utexas.edu/browse/FP-935)
* [FP-877](https://jira.tacc.utexas.edu/browse/FP-877)
- Set pagination default at 25 users per page
- Add pagination component
1. Make your user staff so that you can view /workbench/onboarding/admin
2. To view simulated large results, uncomment [this line](https://github.com/TACC/Core-Portal/blob/9d6e8e98ee545488f502154b375a9a7093e4a96b/server/portal/apps/onboarding/api/views.py#L259) in views.py
- Need to handle 0 user results in search during pagination
- User table needs to scroll within component
=> task/FP-935 - onboarding admin pagination

server/portal/apps/workspace/api/views.py
List My Apps as last app category
* [FP-908](https://jira.tacc.utexas.edu/browse/FP-908)
* [FP-892](https://jira.tacc.utexas.edu/browse/FP-892)
Hide empty application tabs, including My Apps if a user has none
1. Import app categories with `python manage.py import-apps`
2. Delete an app that was the only app in its category in cep.dev/core/admin
3. Make sure that category does not appear
=> task/FP-908 - Hide empty application tabs

server/portal/apps/accounts/managers/accounts.py, server/portal/apps/accounts/managers/unit_test.py, server/portal/apps/auth/tasks.py, server/portal/apps/onboarding/steps/key_service_creation.py, server/portal/apps/onboarding/steps/key_service_creation_unit_test.py
Skip portal side requests for new storage systems for any system that is already valid (listable, accessible by user)
* [FP-898](https://jira.tacc.utexas.edu/browse/FP-898)
- Patched portal.apps.accounts.managers.accounts.setup to skip creation of systems that are accessible (this is called during the system_creation.py onboarding step)
- Patched the key_service_creation onboarding step to skip creation of systems that are accessible
These instructions are for testing the non-keyservice based system creation. Make sure your settings secrets have the following entires:
```
_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEMS = {
'frontera': {
'name': 'My Data (Frontera)',
'prefix': 'frontera.home.{username}',
'systemId': 'frontera.home.{username}', 
'host': 'frontera.tacc.utexas.edu',
'home_dir': …
```
=> task/FP-898 - onboarding system health checks

client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.js
Managing Team for Shared Workspaces now fixed when a user has been deleted from a portal
* [FP-880](https://jira.tacc.utexas.edu/browse/FP-880)
Skip displaying any member of a Shared Workspace that does not have a user object
1. Create a Shared Workspace
2. Add a test account as an editor of the project
3. Delete the test account from your portal from within the django shell using:
```
from django.contrib.auth import get_user_model
get_user_model().objects.get(username="testuser").delete()
```
4. Try managing the team. It should skip displaying the non-existent user
We probably need a more robust solution, such as pulling in user profiles from the tenant.
=> task/FP-880 - Fix Manage Team for Shared Workspaces with deleted members

server/portal/libs/agave/operations.py, server/portal/libs/agave/unit_test.py, server/portal/libs/agave/utils.py
Increment files names for Move, Copy, Trash options in the portal.
1. Navigate to My Data and copy a file into its current path
2. The a copy of the file should be created like `foo.txt` => `foo(1).txt`
3. If you repeat the copy process on `foo.txt` again you should get `foo(2).txt`
4. If you copy a duplicated file `foo(1).txt` the expected behavior is that the incrementation will start over like so:
`foo(1).txt` => `foo(1)(1).txt`
=> Task/FP-123 - Add incremented file number to files copied into the same directory.

client/src/components/DataFiles/DataFilesListing/DataFilesListing.js
Fix bug by making `columns` dependent on `fileNavCellCallback` to ensure that an updated `fileNavCellCallback` is used if scheme changes.  See [FP-970](https://jira.tacc.utexas.edu/browse/FP-970) for notes on re-creating bug
* [FP-970](https://jira.tacc.utexas.edu/browse/FP-970)
* Make `columns` dependent on `fileNavCellCallback` to ensure that an updated `fileNavCellCallback` is used if scheme changes
1. Go directly to route https://cep.dev/workbench/data/tapis/public/cep.storage.public/
2. Then click on your My Data which is `private`.
3) Confirm links to files/folders have correct scheme of `private` (and not `public`) in the route and than you can go to a subfolder and upload a file.
=> bug/FP-970 - Make columns dependent on fileNavCellCallback to handle scheme changes

client/src/components/Onboarding/OnboardingActions.scss, client/src/components/Onboarding/OnboardingStatus.js, client/src/components/Onboarding/OnboardingStatus.module.scss, client/src/components/Onboarding/OnboardingStatus.scss
- Remove unused code.
- Simplify and consistently replicate code for fix.
- Incidentally, fix loading icon size inconsistency.
* [FP-972](https://jira.tacc.utexas.edu/browse/FP-972)
- __Fix__: Remove unused styles.
- __Fix__: Make consistent duplicate fixes for loading UI bug.
- _Minor_: Simplify pre-existing fix for loading UI bug.
- [Be a staff user.](https://github.com/TACC/Core-Portal/wiki/How-to-Set-Your-User-to-Staff)
- Have a user with incomplete onboarding.
- Have an onboarding state for that user that is "Processing".
1. Load user onboarding (`/workbench/onboarding/setup/`).
2. See that any state in Processing has a pill whose text "Processing" can be read without truncation.
1. Load user onboarding administration (`/workbench/onboarding/admin/`).
2. See that any state in …
=> FP-972: Unsqueeze onboarding status loading icon

server/portal/apps/workspace/api/views.py, server/portal/apps/workspace/api/views_unit_test.py
When the `next` iterator reaches the end of the list, it raises a `StopIteration` exception. This error can be raised when a `JobSubmission` object exists in the database, but does not exist in Tapis. We can fix this by including a `default` param with the `next` method.
* [FP-975](https://jira.tacc.utexas.edu/browse/FP-975)
1. Have a `JobSubmission` in the database with an id that does not exist in Tapis. You can recreate this by finding one of your portal jobs and deleting it from Tapis via the CLI.
=> bug/FP-975: Fix `StopIteration` error for backend Jobs listing

client/src/components/Workbench/WelcomeMessages.js, client/src/components/Workbench/Workbench.scss, client/src/redux/reducers/welcome.reducers.js, server/portal/settings/settings_secret.example.py
Shows an Alert message with details about the impending [work2 migration](https://portal.tacc.utexas.edu/tutorials/stockyard-work-migration). To make it show up in only the portals that need it, we add another setting to `_WORKBENCH_SETTINGS`:
```
_WORKBENCH_SETTINGS = {
"debug": _DEBUG,
"makeLink": True,
"viewPath": True,
"compressApp": 'zippy',
"extractApp": 'extract',
"makePublic": True,
"showWork2Message": True,
}
```
* [FP-976](https://jira.tacc.utexas.edu/browse/FP-976)
1. Add the `"showWork2Message": True` configuration to your `_WORKBENCH_SETTINGS` in `settings_secret.py`
2. Open [datafiles](https://cep.dev/workbench/data/)
3. Confirm the alert message displays and the links work
4. Close the message, refresh the page, and confirm it does not show up again.
=> task/FP-976: Add configurable work2 Alert message

server/conf/cms/secrets.sample.py
Update CMS sample settings to _more closely_ match latest [`default_secrets.py` from CMS](https://github.com/TACC/Core-CMS/blob/main/taccsite_cms/default_secrets.py).
* N/A
1. _Minor_: Simpler (and less prone to becoming outdated) comment for `_LDAP`.
2. _Minor_: Replace stock comment for `_CMS_TEMPLATES` with relevant comment (still from CMS version).
3. __New__: Comment out `_CMS_TEMPLATES`'s example custom fullwidth template.
4. _Minor_: Update comments/documentation for `BRANDING & LOGOS & FAVICON`.
5. _Minor_: Remove extra space.
6. __Fix__: Add `_FAVICON` secret.
7. _Minor_: Remove inaccurate comment.
8. _Minor_: Add missing spaces (formatting consistency).
You **could** build a fresh Portal-n-CMS, but it's not necessary. Besides change 6\*, this is a noop PR.
_\* And change 3… if …
=> Quick: Update Sample CMS Settings

client/src/components/FeedbackForm/FeedbackForm.js, client/src/components/FeedbackForm/FeedbackForm.test.js, client/src/redux/reducers/workbench.reducers.js, server/portal/apps/workbench/api/unit_test.py, server/portal/apps/workbench/api/views.py
This PR passes the portal name setting up with the workbench settings. It seemed like an appropriate place, but if it is not, we could make a new view like `/apps/portal_info/` for returning it. I didn't see anything else in the settings we would want to pass up with `portal_info` besides the portal name, so I thought It seemed like overkill.
* [FP-883](https://jira.tacc.utexas.edu/browse/FP-883)
Returned `PORTAL_NAMESPACE` setting with the workbench_state containing `WORKBENCH_SETTINGS`.
Added portal name to `FeedbackForm` submission.
1. Submitting Feedback should create a ticket with a subject `Feedback for ${portalName}`
=> Task/FP-883 - Pass PORTAL_NAMESPACE to front end for use in Feedback Form

client/src/components/SiteSearch/SiteSearchListing/SiteSearchSearchbar/SiteSearchSearchbar.js
The current url's `window.location.search` `query_string` was overwriting the searchbox when the query was erased.
* [FP-985](https://jira.tacc.utexas.edu/browse/FP-985)
- Only load `window.location.search` initially
1. Type something in site search in the top navbar, like "test"
2. On the site search page, delete the query in the site search searchbox (not in the nav), and ensure it is not reset to the initial value
=> bug/FP-985: Fix window search overwriting site search query

client/src/redux/sagas/fixtures/onboarding.fixture.js, client/src/redux/sagas/onboarding.sagas.js, client/src/redux/sagas/onboarding.sagas.test.js
Onboarding admin search works, but Admin search input was being replaced with `"true"`
* [FP-984](https://jira.tacc.utexas.edu/browse/FP-984)
1. Go to https://cep.dev/workbench/onboarding/admin/
2. Search for your username in the admin searchbar
3. Confirm the string is maintained after searching, and not replaced with "true"
=> bug/FP-984: Fix Onboarding Search Query

client/src/components/DataFiles/DataFilesListing/DataFilesListingCells.js, client/src/utils/sizeFormat.js, client/src/utils/timeFormat.js
Make two Data Files Cell components use existing and new utils (to DRY up code a little).
> The new `sizeFormat` util allows `task/`[`FP-388`](https://jira.tacc.utexas.edu/browse/FP-388)`-file-uploader-ui--wip-improvement` to create a common component that does rely on `components/DataFiles/`.
* (tangential) <del>[FP-388](https://jira.tacc.utexas.edu/browse/FP-388)</del> <ins>[FP-993](https://jira.tacc.utexas.edu/browse/FP-993)</ins>
- __New__: Add utility `sizeFormat`
- __New__: Update `FileLengthCell` and `LastModifiedCell` to use `sizeFormat` and `timeFormat`.
- __Doc__: Document functions in existing utility `timeFormat`.
- __New__: Add new function `formatDateTimeFromValue ` to existing utility `timeFormat`
1. Load any Data Files table that lists file size.
2. Ensure size format has …
=> Quick: Have Data List Cells use Util Functions

client/src/utils/filePermissions.js, client/src/utils/filePermissions.test.js
Enables the `Copy` toolbar button in any datafiles system.
* [FP-973](https://jira.tacc.utexas.edu/browse/FP-973)
1. Load https://cep.dev/workbench/data/tapis/public/cep.storage.public/ or https://cep.dev/workbench/data/tapis/community/cep.storage.community/
2. Confirm that the `Copy` toolbar button works on any file
- If you can think of a reason why this should be disabled, please make a note of that.
=> bug/FP-973: Enable `Copy` button/operation in Public Data and Community Data

client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesPreviewModal.test.js, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.test.js, client/src/components/DataFiles/fixtures/DataFiles.systems.fixture.js, client/src/components/DataFiles/tests/DataFiles.test.js
Excludes non-private systems from the Copy Modal system selector dropdown.
* [FP-1013](https://jira.tacc.utexas.edu/browse/FP-1013)
1. Go to https://cep.dev/workbench/data/tapis/private/
2. Select a file, click the "Copy" toolbar, and verify Public and Community systems are excluded from the dropdown
=> bug/FP-1013: Disable copying to non-private systems in copy modal

server/portal/apps/workbench/urls.py, server/portal/templates/includes/nav_portal.html
Add link to Onboarding Admin in User Account Nav Dropdown
* [FP-1014](https://jira.tacc.utexas.edu/browse/FP-1014)
Add link to Onboarding Admin in User Account Nav Dropdown for Staff users.
1. Click over User Account Nav Dropdown
2. Click on Onboarding Admin
=> task/FP-1014: Add Onboarding Admin link to User Nav Dropdown

server/conf/docker/docker-compose-dev.all.debug.yml, server/portal/templates/includes/nav_portal.html, server/portal/templates/includes/nav_portal.raw.html, server/portal/urls.py
- Support loading Portal nav markup independently via URL
- Update Docs image tag in the Docker compose file.
- Portal & Docs: [FP-1015](https://jira.tacc.utexas.edu/browse/FP-1015)
- CMS: GH-195
- CMS: https://github.com/TACC/Core-CMS/pull/211
- Portal: https://github.com/TACC/Core-Portal/pull/390
- Docs: https://bitbucket.org/taccaci/frontera-tech-docs/pull-requests/17/fp-1015-clone-portal-nav
- __New__: Update `docs` image.
- __New__: Separate Portal nav wrapper from content.
- __New__: Load Portal nav content as markup at stand-alone URL.
See https://github.com/TACC/Core-CMS/pull/211 "Testing".
See https://github.com/TACC/Core-CMS/pull/211 "Screenshots".
See https://github.com/TACC/Core-CMS/pull/211 "Notes".
=> FP-1015: Allow Portal Nav to be Cloned

server/conf/cms/secrets.sample.py
Update CMS sample secrets so any portal instance can easily provide standard homepage and guide pages.
N/A
- __New__: Add templates to CMS sample secrets.
N/A
- All templates already available and tested on [cep](https://cep.tacc.utexas.edu/) and [3dem-staging](https://3dem-staging.tacc.utexas.edu/).
- Guide templates already available and tested on [frontera-portal](https://frontera-portal.tacc.utexas.edu/) and [pprd.protx](https://pprd.protx.tacc.utexas.edu/).
=> Quick: Add Portal Templates to CMS Sample Secrets

README.md
- CSS lint fix command was incorrect (from copy of similar JS command).
- Add new line at end of file.
N/A
- __Fix__: Update CSS lint command.
- _Minor_: Add EOF new line.
N/A
N/A
N/A
=> Fix typo in README.md (and add new line at end)

server/portal/libs/agave/operations.py, server/portal/libs/agave/operations_unit_test.py, server/portal/libs/elasticsearch/analyzers.py
* https://jira.tacc.utexas.edu/browse/FP-594
Ensuring search result matches contain the entire search query
keep spaces in ngrams so results match user input that uses spaces
1.
See jira ticket for bug description
=> Ensuring search result matches contain the entire search query

client/src/redux/sagas/datafiles.sagas.js, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py, server/portal/libs/agave/operations.py
Adds a `filesize` attribute to the metrics logs for downloads, for splunk queries.
* [FP-813](https://jira.tacc.utexas.edu/browse/FP-813)
1. Download a file, and verify that the `filesize` is logged in the docker logs.
=> task/FP-813: Download Filesize Metrics

client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.js, client/src/components/Workbench/Workbench.js, client/src/components/Workbench/Workbench.test.js
Sometimes, when selecting a file to use as an input in a job, this bug will pop up and crash the frontend. It's caused by an extraneous dispatch to `FETCH_SYSTEMS` which clears and reloads systems again, without accounting for an empty systems configuration array.
* [FP-1038](https://jira.tacc.utexas.edu/browse/FP-1038)
- Remove extraneous dispatch to `FETCH_SYSTEMS`
- Render `<LoadingSpinner>` if initial `FETCH_SYSTEMS` request is not done loading on the Workbench
1. Load an app, and confirm that no matter how many times you click the `Select Input` button on an app, it does not crash the app.
=> bug/FP-1038: Fix race condition causing `Cannot read property 'system' of undefined` bug

client/src/components/DataFiles/DataFilesListing/DataFilesListing.js, client/src/components/DataFiles/DataFilesListing/DataFilesListing.test.js, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.js, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.module.css, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.test.js
Support Count of Search Results in UI
* [FP-563](https://jira.tacc.utexas.edu/browse/FP-563)
Implementing search results message for Data Files.
1. On Data Files type a query and hit Enter
For further consideration, Search the query_string is not showing in input box when is passed as URL parameter.
=> Support Count of Search Results in UI.

client/src/styles/trumps/table.css
- Prevent button links in table cells from being cut off on the left.
- Do not preserve padding on fake link buttons. Instead, let them be padding-less, like links.
- _Tweak a comment in the same file with the relevant changes._
I.e. Fix stuff like [this (screenshot)](https://user-images.githubusercontent.com/62723358/119696920-4b309d80-be15-11eb-83e7-9b6768fa77ae.png) by not trying to preserve button padding, and explain why.
* [FP-962](https://jira.tacc.utexas.edu/browse/FP-962)
- Replace fix from 6aaab34.
- Obviate the related 6782202.
- Data Files
- Data Files > Projects
- Data Files > Projects > File Listing
- Data Files > Projects > Member List
- Onboarding Admin
- Allocations
- _any other tables with a button-as-a-link in any cell_
Both hotfix PRs (#405 and this #406) are failing …
=> Hotfix: FP-962: Simpler fix for double padding of table cell button-links

client/src/redux/sagas/jobs.sagas.js, client/src/redux/sagas/jobs.sagas.test.js
Fixes regression introduced in https://github.com/TACC/Core-Portal/pull/400. 
I had had added that TOGGLE_SUBMITTING during the adding of some unit tests without understanding its use in AppForm.js.
* [FP-1064](https://jira.tacc.utexas.edu/browse/FP-1064)
* remove problematic TOGGLE_SUBMITTING action from saga
* add comment in saga unit test to explain why the state is unique after job submission
1. Run job
2. Ensure that job submission occurs.  Scroll down to ensure that the submitting spinner is no longer there.
=> FP-1064:  Stop the spinning / remove problematic TOGGLE_SUBMITTING action from saga

client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.js, client/src/redux/reducers/datafiles.reducers.js
* [FP-1062](https://jira.tacc.utexas.edu/browse/FP-1062)
Check that the data-files modal is open and tried to push keys before refreshing data files
1. Running an app with an optional working directory field on a system that requires keys to be pushed (Matlab, Paraview)
2. Push Keys modal should appear, enter password and token
3. Data Files modal should not appear
=> Only open data files select modal when pushing keys to access data files

server/portal/settings/settings.py
We must have crossed wires at some point thinking Stampede2 used `/home`, when in actuality it is `/home1`. This was causing an issue where the tapis exec system always failed the files list test to validate the system.
1. Disable a stampede2 execution system of yours via tapis cli, i.e. `sal.TACC-ACI.exec.stampede2.HPC`
2. Run an app on stampede2 using that sys allocation
2. Confirm that keys push successfully and the job is submitted
We will need to either manually disable every user exec system using `/home` as a storage `homeDir`, or add a mechanism in the code to disable/re-clone the system if the test fails.
=> hotfix: Change stampede2 `homeDir` to `/home1`; add maverick2

client/src/components/SiteSearch/SiteSearchListing/SiteSearchListing.css, client/src/components/SiteSearch/SiteSearchListing/SiteSearchListing.js, client/src/components/SiteSearch/SiteSearchListing/SiteSearchListing.module.scss, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss
After checking with design, there is supposed to be a header, but no header labels on the SiteSearchListing. These changes should fix the column spacing issues for anything using the `InfiniteScrollTable` for Site Search
* [FP-1065](https://jira.tacc.utexas.edu/browse/FP-1065)
1. Go to the files area of Site Search and view the table listing. You should not see any overlapping or cut off columns
=> Task/FP-1065 - Fix issues with site search header and spacing

README.md
Update `README.md` to prevent error importing certificate on macOS.
N/A
- Update `README.md`
N/A
<details>
<summary>Problem</summary>
</details>
=> Upate `README.md`: Clarify cert install for macOS

README.md
- __Add requirement for ES setup.__
- Group requirements for ES setup.
- Improve(?) punctuation for ES setup.
N/A
- __New__: Add requirement bullet to ES section of Readme.
- _Minor_: Tweak formatting of ES section of Readme.
N/A
[Wes & Sal figured this out, again.](https://tacc-team.slack.com/archives/GQW4Q8HLG/p1623255556098500?thread_ts=1623252581.092900&cid=GQW4Q8HLG)
N/A
- Allocations retrieval (among other things) fails if ElasticSearch is unable to process.
- ElasticSearch requires lots of memory.
- Docker Desktop—by default—limits memory to 2GB.
=> Add Docker RAM req. to README.md

server/portal/templates/base.html, server/portal/templates/includes/nav_portal.raw.html
- Update Portal nav markup to use Cortal icons.
- _Update Font Awesome icon load to reference correct ticket to remove it._
* [FP-526](https://jira.tacc.utexas.edu/browse/FP-526)
Further header, portal nav, icon UI improvements come in https://github.com/TACC/Core-CMS/pull/222.
- __New__: Change `fa` icons to `icon` icons.
- _Minor_: Update related ticket reference in `base.html`.
1. Login to Portal.
2. Open dropdown.
3. All dropdown links must have an icon.
4. All dropdown link icons must be from [Cortal icon set](https://confluence.tacc.utexas.edu/display/UP/UI+-+Components+-+Icon?preview=%2F129171529%2F175865880%2FCortal+Icons+v1.2.pdf) (direct PDF link).
The [design where header uses a Cortal icon](https://xd.adobe.com/view/b37b291a-7798-4814-90f3-7ac63c48a3e0-e628/screen/38e3fb7c-0b56 …
=> FP-526: Update Header Dropdown to Use Cortal Icons

client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalSelectedTable.js, client/src/components/DataFiles/DataFilesTable/DataFilesTable.scss, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss
The Allocations table crushes the "View Team" button when the page width is compressed enough. File listing tables for file upload and file copy had issues where the loading spinner was cut off or squished while the success button could also be cropped as well.
* [FP-1067](https://jira.tacc.utexas.edu/browse/FP-1067)
I've attached some reference images below to show these changes.
- To fix the issues with the Allocations table button being cut off, I've just made the text wrap to a new line only for button/link elements within the InfiniteScrollTable's body
1. Fixing the issues with the file listings tables within the upload and copy areas, I've set a min-width for the status column
2. I noticed some excess spacing at the end of the columns (I'm not sure if this was intentional) I've set …
=> Task/FP-1067 - Prevent certain table columns from squishing content

client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsContactCard/AllocationsContactCard.module.scss, client/src/components/FeedbackForm/FeedbackButton.module.scss, client/src/components/History/HistoryViews/JobHistoryModal.module.scss, client/src/components/Jobs/JobsStatus/JobsStatus.module.scss, client/src/components/Onboarding/OnboardingActions.module.scss, client/src/components/SystemMonitor/SystemMonitorCells.js, client/src/components/Workbench/Workbench.scss, client/src/components/_common/DescriptionList/DescriptionList.module.scss
Where font weight is erroneously `500`, set font weight to normal or `700` (bold).
_I did this **instead of** fix "Dasboard" "headers", because [I found **zero** such discrepancies](https://jira.tacc.utexas.edu/browse/FP-1010?focusedCommentId=22386&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22386)._
* [FP-1010](https://jira.tacc.utexas.edu/browse/FP-1010)
- Change: 500 → 700 (match design)
- Code: `Dashboard`
- Design: [Core Portal > Dashbaord](https://xd.adobe.com/view/db2660cc-1011-4f26-5d31-019ce87c1fe8-ad17/)
- Image: <img width="1080" alt="Dashboard System Monitor Name" src="https://user-images.githubusercontent.com/62723358/121411648-79d86900-c929-11eb-9f26-a99e55ddc0f0.png">
- Change:
- removed ineffectual 500 from icon (_still_ match design)
- …
=> FP-1010: Fix Erroneous Font-Weight 500's

server/portal/settings/settings.py
Typo on a missing extension on a file lookup in `settings.py` was preventing `settings_custom.py` from ever being loaded.
1. Copy and paste `settings_default.py` into `settings_custom.py`
2. Change the value of something testable, like making `_SYSTEM_MONITOR_DISPLAY_LIST` blank `[]`
3. Confirm the setting change propagates on reload
4. Make sure to delete `settings_custom.py` when done testing
=> hotfix: Fix missing `.py` extension on import

client/src/components/ManageAccount/ManageAccountTables.js
Made links in Manage Account to match the website's theme.
* [FP-1095](https://jira.tacc.utexas.edu/browse/FP-1095)
Added `wb-link` class to links in `ManageAccountsTable`.
1. Check if link colors in Manage Account are the right color.
=> Adjust colors of links in Manage Account to match the website's theme.

server/portal/settings/settings_secret.example.py
The COMMUNITY_INDEX_SCHEDULE setting is configured in the settings_custom.py file.
1.
=> Move setting out of secret

client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.module.scss
Made shared workspace descriptions properly render whitespace.
* [FP-939](https://jira.tacc.utexas.edu/browse/FP-939)
Added style to descriptions to properly render whitespace in shared workspace description.
1. Ensure whitespace is properly displayed in shared workspace description.
=> Task/FP-939: Display shared workspace description whitespace.

client/src/components/Applications/AppForm/AppForm.js, client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/Applications/AppLayout/AppLayout.js, client/src/redux/reducers/apps.reducers.js, client/src/redux/sagas/fixtures/apptray.fixture.js
In the app definition refactor, we missed a spot in order to load html apps.
Also fixes scrolling to the top of the apps page after job submission.
* [FP-1108](https://jira.tacc.utexas.edu/browse/FP-1108)
1. Make sure you have the Vis Portal app in the Visualization tab, or run `./manage.py import-apps` in the `core_portal_django` container
2. Go to https://cep.tacc.utexas.edu/workbench/applications/vis-portal and make sure you can load it
=> bug/FP-1108: Fix HTML App Loading

client/src/components/Applications/AppForm/fixtures/AppForm.app.fixture.js, client/src/components/Applications/AppLayout/AppLayout.js, client/src/components/Applications/AppLayout/AppLayout.test.js, client/src/components/DataFiles/fixtures/DataFiles.files.fixture.js
Made the breadcrumbs for the applications page to properly render.
* [FP-1030](https://jira.tacc.utexas.edu/browse/FP-123)
Changed `AppLayout.js` to use the correct data to display breadcrumbs. 
1. Ensure that the application breadcrumbs show.
There is a bug with routing to html-type apps (i.e. the vis-portal) when testing locally.
=> Bug/FP-1030: Fix breadcrumbs for application page

server/portal/apps/onboarding/steps/mfa.py
Small update to wording of MFA onboarding to make it clear that TACC Token App is required
* [FP-1031](https://jira.tacc.utexas.edu/browse/FP-1031)
Text has been updated from:
```
"""First, set up multi-factor authentication on the
<a style="color:#9d85ef;" href="https://portal.tacc.utexas.edu">TACC User Portal</a>
then confirm the pairing was successful."""
```
To:
```
"""First, set up multi-factor authentication on the
<a style="color:#9d85ef;" href="https://portal.tacc.utexas.edu">TACC User Portal</a>
using
<a style="color:#9d85ef;" href="https://portal.tacc.utexas.edu/tutorials/multifactor-authentication#tacctokenapp">TACC Token App</a>,
then confirm the pairing was successful."""
```
1.
(From local dev environment)
=> [FP-1031] Onboarding: Clarify MFA Steps

client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.js, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.test.js
Removes unused/disabled buttons in Public/Community/Google Drive.
* [FP-1007](https://jira.tacc.utexas.edu/browse/FP-1007)
Added additional `show*` conditions for each toolbar button component.
1. Route to Community Data, Google Drive, and Public Data to ensure that the unused toolbar buttons are disabled.
=> Bug/FP-1007: Remove inactive toolbar buttons for public/community/google drive

client/src/components/ManageAccount/ManageAccount.js, client/src/components/Workbench/Workbench.test.js, client/src/components/_common/Section/SectionMessages.js, client/src/components/_common/Section/SectionMessages.test.js, client/src/constants/messages.js, server/portal/apps/accounts/integrations.py, server/portal/apps/accounts/views.py, server/portal/apps/googledrive_integration/integrations.py, server/portal/apps/googledrive_integration/views.py
* [FP-952](https://jira.tacc.utexas.edu/browse/FP-952)
Update "add google drive" workflow to use react error messages instead of django's template-based messages
1. Modify line 64 of server/portal/apps/googledrive_integration/views.py to make `if 'googledrive' in request.session:` validate to False
2. Go to https://cep.dev/workbench/account/ 
3. Click on, connect to Google Drive
4. Follow the steps to connect TACC google account
5. Verify error message appears below nav bar
Example of what will cause an error:
Error Location:
=> task/FP-952: Replace Django Messages with Client Side Messages

client/src/components/Applications/AppForm/AppForm.js, client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/Applications/AppForm/AppFormUtils.js, client/src/components/Applications/AppForm/AppFormUtils.test.js
Ensure that Frontera-related normal queue validation occurs only on Frontera
Validation checks for the normal queue were applied in https://github.com/TACC/Core-Portal/pull/426, that should have been limited to the `normal` queue on Frontera only.  This PR fixes that and adds some additional unit tests.
* [FP-1133](https://jira.tacc.utexas.edu/browse/FP-1133)
* Ensure that Frontera-related normal queue validation occurs only on Frontera
* Add related unit tests
1. Ensure you can submit a 1 or 2 node job on the normal queue on Stampede 2.
=> Bug/FP-1133: Ensure that Frontera-related normal queue validation occurs only on Frontera

client/src/components/Applications/AppForm/AppForm.js, client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/DataFiles/DataFiles.js, client/src/components/DataFiles/tests/DataFiles.test.js, server/portal/apps/datafiles/views.py, server/portal/apps/workspace/api/views.py
Supports the following configurations: 
`_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEMS = []`
`_PORTAL_DATAFILES_STORAGE_SYSTEMS = []`  
`_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEM_DEFAULT = ''`
* [FP-1118](https://jira.tacc.utexas.edu/browse/FP-1118)
Handles messaging in `AppForm` and `DataFiles` when configured with empty storage systems.
1. Try out variations of the above configurations and ensure that there aren't uncaught errors.
When the local storage system is empty, the default storage system should also be an empty string.
=> Task/FP-1118: Support no datafiles systems [A2CPS].

client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.test.js, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Adds a read only option to shared workspaces settings in `_PORTAL_DATAFILES_STORAGE_SYSTEMS` to disallow creation.
* [FP-1117](https://jira.tacc.utexas.edu/browse/FP-1117)
Disables shared workspace creation if settings have the `read_only` option enabled.
1. Add the read_only option to the Shared Workspaces item in `_PORTAL_DATAFILES_STORAGE_SYSTEMS` in  `settings_custom.py`.
2. Ensure that creating shared workspaces is disabled.
Wasn't sure if I should disable `Edit Descriptions` for read only shared workspaces.
Should I make this setting have an effect on [FP-1134](https://jira.tacc.utexas.edu/browse/FP-1134) for hiding it?.
=> Task/FP-1117: Read only shared workspace setting

client/src/components/Dashboard/Dashboard.js, client/src/components/Sidebar/Sidebar.js, client/src/components/Sidebar/Sidebar.test.js, client/src/components/Workbench/Workbench.js, client/src/components/Workbench/Workbench.test.js, client/src/redux/reducers/workbench.reducers.js, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
A2CPS does not want the Applications space to be enabled for the time being.
* [FP-1129](https://jira.tacc.utexas.edu/browse/FP-1129)
Custom setting added to enable/disable Applications and History sections and Dashboard Recent Jobs secction.
1. Modify **_WORKBENCH_SETTINGS = {"hideApps": True}** property to enable/disable Apps sections
**workbench/applications** and **workbench/history/jobs** routes should redirect to **workbench/dashboard**.
=> task/FP-1129: Toggle Apps and History Sections

client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.js, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.test.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.test.js, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Allows a settings value to determine if privilege is needed for editing project data.
* [FP-1134](https://jira.tacc.utexas.edu/browse/FP-1134)
Added a setting, `privilegeRequired`, in the project api setting.
When `True`, it will only display to an owner of the project.
1. Toggle the setting values and check that the buttons enable only to an `owner` when `True`.
=> Task/FP-1134: Toggle Manage Team and Edit Description [A2CPS]

server/portal/apps/projects/models/base.py, server/portal/apps/projects/models/unit_test.py, server/portal/apps/projects/views.py, server/portal/apps/projects/views_unit_test.py
A2CPS admins will be creating project systems and sharing them with users manually via tapis. This means the portal will have no notion of users or owners associated with the project.
This PR will add tapis system owners to the ProjectMetadata record, if the owner has previously logged into the portal.
* [FP-1128](https://jira.tacc.utexas.edu/browse/FP-1128)
1. Create a project in cep.tacc.utexas.edu. This will take you to the project page, e.g. `https://cep.tacc.utexas.edu/workbench/data/tapis/projects/${systemId}`
2. In cep.dev, insert the resulting project system id in the local url, e.g. `https://cep.dev/workbench/data/tapis/projects/${systemID}`
3. In the "Manage Team" modal, ensure that you see yourself as the owner
=> [A2CPS] FP-1128: Accommodate non-portal created Projects

server/portal/libs/elasticsearch/docs/base.py, server/portal/libs/elasticsearch/docs/unit_test.py
The global ES client consistently times out on the initial load, resulting in 10+ seconds of the UI hanging. Instantiating a new client inside the method fixes this.
- Create a fresh ES client inside of `IndexedAllocation.from_username`
- Update tests
1. Update `_ES_HOSTS` and `_ES_AUTH` in settings_secret to point to a staging or production environment
2. Log into the portal and check the network requests in your browser's devtools to make sure that allocations were retrieved.
=> Reduce initial load time by circumventing the global Elasticsearch client.

client/src/components/DataFiles/DataFilesModals/DataFilesAddProjectModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesAddProjectModal.test.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/redux/reducers/projects.reducers.js
This PR fixes the bug where a user with `edit` access can bypass the `owner` check when `privilegeRequired` settings is set to `True`.
The reason behind this was that the `member` list in the project `metadata` was shared and modified (`PROJECTS_MEMBER_LIST_SET` in `DataFilesSidebar.js`) on opening the
project create modal (**+ Add -> Shared  Workspace**).
While working on this, I also noticed that the member listing when clicking on **Manage Team** also changed if one opens the project create modal (**+ Add -> Shared  Workspace**) (reverting to only showing the currently authenticated user).
This PR mitigates both bugs.
* [FP-1151](https://jira.tacc.utexas.edu/browse/FP-1151)
Added a new state for local member list (`formMembers`) in the project metadata only used by `DataFilesSidebar` …
=> Bug/FP-1151: Shared workspace privilege bypass

client/src/components/ManageAccount/ManageAccount.js, client/src/components/ManageAccount/ManageAccountTables.js, client/src/components/ManageAccount/tests/ManageAccount.test.js, client/src/components/ManageAccount/tests/ManageAccountTables.test.js
Additional PR to #471 
* [FP-1171](https://jira.tacc.utexas.edu/browse/FP-1171)
Hides 3rd Party Apps and Licenses in Manage Account component when `hideDataFiles` is `True`.
1. Set `hideDataFiles` in `settings_custom.py` to `True`.
2. Ensure that 3rd Party Apps and License are hidden in `/workbench/account/`.
N/A
=> (quick fix) Task/FP-1171: Toggle Data Files.

client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.js, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.test.js, client/src/redux/reducers/projects.reducers.js
Project listings crash the frontend if there is no pi defined, or if any member is missing a user model. This handles those cases.
* [FP-1201](https://jira.tacc.utexas.edu/browse/FP-1201)
IF YOU ARE FRANK:
1. Use a2cps settings
2. Go here and make sure it works: https://cep.dev/workbench/data/tapis/projects/a2cps.project.WMA-TEST-1
ANYONE ELSE: 
1. Change your `_PORTAL_PROJECTS_SYSTEM_PREFIX` to `cep.project` and `_PORTAL_PROJECTS_ID_PREFIX` to `CEP`
2. Create a project in cep.tacc.utexas.edu with a test account
3. Add your normal user as a member
4. In https://cep.dev, confirm you can view the project normally
=> bug/FP-1201: [A2CPS] Handle missing pi in project metadata

server/conf/docker/docker-compose-dev.all.debug.yml, server/portal/apps/accounts/urls.py, server/portal/apps/accounts/views.py, server/portal/apps/auth/views.py, server/portal/settings/settings.py, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Allow the core portal's auth model backend to be used by the core cms
* [FP-1194](https://jira.tacc.utexas.edu/browse/FP-1194)
Changes allows CMS login after Core Portal has authenticated with Agave/Tapis
1. Modify the CMS image tag in `docker-compose-dev.all.debug.yml` from `taccwma/core-cms:latest` to `taccwma/core-portal-cms:78753bf` This pre-built CMS image contains the changes to enable cms login. 
2. In `settings_local.py` add entry `LOGIN_REDIRECT_URL = '/remote/login/'` 
3. Start Portal, navigate to cep.dev. Ensure you are logged out of Core Portal and Core CMS.
4. Ensure the CMS account for your primary TACC account is an admin at cep.dev/admin.
5. Using your primary TACC account log in to Core Portal as usual. Once portal login is successful, navigate to CMS home page. Verify …
=> task/FP-1194: Support CMS login

client/package-lock.json, client/package.json, client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.js
task/FP-1071 - Hide "Return to Shared Workspaces" in File Selector Modal
My understanding of the problem is that when running an application and attempting to select a shared workspace, the message "Return to Shared Workspaces" is displayed when it should only show up after selecting a shared workspace.
* [FP-1071](https://jira.tacc.utexas.edu/browse/FP-1071)
Added missing prop, "showProjects", in DataFilesSystemSelector call in DataFilesSelectModal.js. Added on line 68.
1.  Navigated to "Applications" and selected "NAMD".  
2. Used its "Select Input" to bring up the DataFilesSelectorModal and then switched to "Shared Workspaces".  
3. Noted that "Return to Shared Workspaces" no longer displayed at the Shared Workspaces level, but did still show up as expected after selecting a shared …
=> task/FP-1071 - Hide "Return to Shared Workspaces" in File Selector Modal

client/src/components/Jobs/Jobs.js, client/src/components/Jobs/Jobs.scss
The "Job Status" column of the Job History listing on the dashboard appears to overflow slightly onto the header row when scrolling.
* [FP-1111](https://jira.tacc.utexas.edu/browse/FP-1111)
* Removed 
> `.job__status {
>   position: relative;
> }`
from jobs.scss
1.  If necessary, run enough jobs to require scrolling to see all jobs in History / Jobs view of portal.
2. Test by scrolling job history table up.  "Job Status" column should no longer scroll up into the table header.
"Job Status" Column Scrolling into Header
"Job Status" Column No Longer Scrolling into Header
=> task/FP-1111: Dashboard Job History "Job Status" column overflow

client/src/components/DataFiles/DataFilesListing/DataFilesListing.js, client/src/components/DataFiles/DataFilesListing/DataFilesListing.test.js, client/src/components/DataFiles/DataFilesListing/DataFilesListingCells.js, client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesPreviewModal.test.js
This adds the missing `length` param to the `FileNavCell` and propagates it to the `preview` datafiles operation to be sent to the backend to be used by our `METRICS` logger
* [FP-1170](https://jira.tacc.utexas.edu/browse/FP-1170)
1. Preview an image or text file
2. In the docker logs, confirm you see `filesize` populated in the logs for the action. e.g.:
```
core_portal_django         | [METRICS] INFO 2021-09-24 22:09:39,879 UTC views metrics.portal.apps.datafiles.views.get:88: user:sal op:preview api:tapis scheme:private system:frontera.home.sal path:1favicon.cep.png filesize:11772
```
=> bug/FP-1170: Add `filesize` to datafiles preview logs

client/src/components/DataFiles/DataFilesListing/DataFilesListing.test.js, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.test.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.test.js, client/src/components/PublicData/PublicData.test.js, server/portal/settings/settings_custom.example.py
Remove some unused settings.  https://github.com/TACC/Core-Portal/pull/464#discussion_r713335039 was resolved in one spot but there was some more remaining spots.
Dropped systemPrefix
=> Remove unused systemPrefix workbench settings

client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.module.scss, client/src/components/DataFiles/DataFilesModals/tests/DataFilesPreviewModal.test.js, server/portal/apps/datafiles/views_unit_test.py, server/portal/libs/agave/operations.py, server/portal/settings/settings.py, server/portal/settings/unit_test_settings.py
Displays a button to preview large and html files in a new tab.
* [FP-1258](https://jira.tacc.utexas.edu/browse/FP-1258)
1. Create and upload an html file to your My Data system
2. Confirm that there is a prompt to preview the file in a new window
3. In `server/portal/libs/agave/operations.py` on line `487`, change `5000000` to `1`
4. Try to preview a text file and confirm that it prompts to open preview in a new window
=> task/FP-1258: Enable html and large file previews

client/src/components/History/History.js, client/src/components/History/History.test.js, client/src/redux/reducers/jobs.reducers.js, client/src/redux/sagas/jobs.sagas.js, client/src/redux/sagas/jobs.sagas.test.js
Made to update job status(es) for the Job Listings on opening the `JobHistoryModal` and on routing to Job Listings. 
* [FP-1109](https://jira.tacc.utexas.edu/browse/FP-1109)
1. Add a job request.
2. Route to the History tab from the sidebar.
3. Ensure that the recent job request is displayed in the listing.
4. After a while (about when the job status should change), try clicking on `View Details`
5. Ensure that the `Job Status` for the job has been updated in the listing.
=> Bug/FP-1109: Update Job Status on View Detail and Job Listing

client/src/components/DataFiles/DataFilesTable/DataFilesTable.test.js
Added unit tests for the `DataFilesTable` component.
* [FP-1197](https://jira.tacc.utexas.edu/browse/FP-1197)
Added `DataFilesTable.test.js` and tested the following behavior:
1. Columns are rendered properly.
2. Error messages are rendered accordingly.
3. Redux events are dispatched correctly.
1. npm run tests (I guess github runs them for you though)
=> Task/FP-1197: Add unit test for DataFilesTable

server/portal/apps/onboarding/steps/project_membership.py, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
BM wants to control which queue project request tickets get sent to.
* [BM-21](https://jira.tacc.utexas.edu/browse/BM-21)
1. Add this to `_PORTAL_USER_ACCOUNT_SETUP_STEPS` in `settings_custom.py`:
```
{
'step': 'portal.apps.onboarding.steps.project_membership.ProjectMembershipStep',
'settings': {
'project_sql_id': 57729,
'rt_queue': 'Web & Mobile Apps'
}
},
```
2. Login with a test user that is not on the BrainMap project
3. Confirm that the ticket goes to the WMA queue, and not the Accounting queue
4. Repeat steps 1-3, this time setting `rt_queue` to an empty string or removing it entirely, and confirm the ticket ends up in the [Accounting](https://consult.tacc.utexas.edu/Search/Results.html?Query=Queue%20%3D%20%27Accounting%27%20AND%20Status%20%3D%20%27new%27) queue
5. Delete your test …
=> task/BM-21: Add project request queue setting

server/portal/apps/onboarding/steps/project_membership.py
The link sent to users to continue onboarding is missing `/workbench`. Should be `Please login at {base_url}/workbench/onboarding/setup`
* [FP-1327](https://jira.tacc.utexas.edu/browse/FP-1327)
1. Enable project membership onboarding step by adding this to your `_PORTAL_USER_ACCOUNT_SETUP_STEPS`
```
{
'step': 'portal.apps.onboarding.steps.project_membership.ProjectMembershipStep',
'settings': {
'project_sql_id': 57729,
}
},
```
2. Go through onboarding with a user not on the specified allocation (BrainMap in this example)
3. Approve yourself via the onboarding admin panel
4. Confirm the link in the email you get in response works as intended
=> bug/FP-1327: Fix onboarding link

client/src/redux/sagas/datafiles.sagas.js
Based on the error message that Nathan was getting during the test session.
```
TypeError: Cannot read properties of undefined (reading 'toString')
The above error occurred in task Wi created by takeLatest(FETCH_FILES, Wi) created by xp created by xp Tasks 
cancelled due to error: 
takeLatest(FETCH_FILES, Wi) VM75:1 GET https://pprd.frontera-portal.tacc.utexas.edu/api/datafiles/tapis/listing/private/longhorn.home.user/?
limit=100&nextPageToken&offset=0&query_string= net::ERR_CONNECTION_REFUSED VM75:1 
GET https://pprd.frontera-
portal.tacc.utexas.edu/api/datafiles/systems/definition/longhorn.home.user/ net::ERR_CONNECTION_REFUSED
```
I could not reproduce the exact error, but it seemed reasonable that there be a handle for this kind of an error.
* …
=> Bug/FP-1292: File listing error handling when network connection failure.

server/portal/apps/search/tasks.py
There is a block of python code in a `next` function that checks for a project system with `hideSearchBar` set to `True`, which raises an exception if no system is found. This adds a default `None` to prevent the iterator from failing.
1. Delete a file
2. Confirm that the indexer does not fail
=> Fix indexer exception when no project system to skip

client/src/components/DataFiles/DataFilesModals/DataFilesAddProjectModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesAddProjectModal.test.js
There was an uncaught error when I was testing the create shared workspaces functionality in 3dem.
It seems like at the moment, the `authenticatedUser` state was at it's default state (`{user: null}`). 
Maybe because for some reason the call to [fetchAuthenticatedUserUtil](https://github.com/TACC/Core-Portal/blob/5a0610ff757100da1295820e834042b497dc03b3/client/src/redux/sagas/authenticated_user.sagas.js) didn't trigger?
I wasn't sure if I should re-request if user was null. 
It seemed like a seamless way would be to ensure that the members list didn't include the incorrect state, so that the code wouldn't reach the errors in the first place (`TypeError: e.user is null`).
This way users could just add themselves to the list if for some reason the authenticatedUser is not set properly.
* …
=> (Quickfix) Bug/FP-1295: Handle create workspace user error.

client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.js, client/src/utils/systems.js
Fixes the naming of the root path folder for Shared Workspaces in file listings for data files modals (e.g. copy file modal) 
Previously, it displayed it `/`, now it correctly displays the Shared Workspace title.
* [FP-1296](https://jira.tacc.utexas.edu/browse/FP-1296)
Made use of a better system utility function (`findSystemOrProjectDisplayName`) for rendering system name. 
1. Go to the copy file modal.
2. Make the destination a Shared Workspace.
3. Confirm that the rendering of the Shared Workspace's root folder is not a `/` but the title of the Shared Workspace.
=> Fix listing path for shared workspaces in data files modal listings.

client/src/components/DataFiles/DataFilesModals/DataFilesAddProjectModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesAddProjectModal.test.js
Removed unnecessary call to fetch user for the add project modal added in #544.
* [FP-1295](https://jira.tacc.utexas.edu/browse/FP-1295)
Removed the fetch authenticated user call and test related to that.
1. Ensure that the call isn't made to fetch users
N/A
=> Bug/FP-1295: Remove unneeded call to fetch authenticated user.

server/portal/apps/search/tasks.py
Prevent the indexer from throwing an exception when hideSearchBar isn't defined.
1. Restart web and worker containers
2. Rename a file and check that the indexer task runs without an exception.
=> bug/FP-1362: Make hideSearchBar param optional on systems

client/src/components/Allocations/Allocations.scss, client/src/components/Applications/AppBrowser/AppBrowser.scss, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.scss, client/src/components/History/History.module.scss, client/src/components/Sidebar/Sidebar.module.scss, client/src/components/SiteSearch/SiteSearchSidebar/SiteSearchSidebar.scss
Update sidebar link hover/focus/active states
* [FP-1191](https://jira.tacc.utexas.edu/browse/FP-1191)
Sidebar links on Main, Allocations, Applications, Data Files, History, and Search updated:
- :hover - purple background and not bold text
- -active - purple background and bold text
- :active - purple background and bold text
1.  Navigate to Portal Dashboard.  On the "Main" sidebar, a selected (-active) sidebar link should have a purple background with bold text.  Any Sidebar link "hovered over" should have a purple background with non-bold text. All other links should have a grey background with non-bold text.
2. With the mouse, hover over a non-active Sidebar link and "left-click and hold" on the link.  That link is now :active.  It should have a purple background and bold text.
3. …
=> task/FP-1191-Sidebar Link Hover/Active/Focus UI

client/src/components/DataFiles/DataFilesListing/DataFilesListingCells.js
`CheckboxHeaderCell` now is keyboard accessible in Data Files Table
* [FP-1386](https://jira.tacc.utexas.edu/browse/FP-1386)
Changed the `CheckboxHeaderCell` to be accessible with Spacebar
1. In Data Files Table select checkbox in header cell
2. Now able to select with Spacebar
https://user-images.githubusercontent.com/76450787/144930194-cc1ac517-34f9-4c24-96a1-9d5c769a1e64.mov
=> bug/FP-1386 Data Files Table CheckboxHeaderCell keyboard accessible

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.jsx
Remove dangling reference found during cleanup and review after:
- #520
None
- Edit comment to not reference `styleName` (and be consistent with similar comments).
N/A
N/A
=> Noop: Remove Dangling "styleName" Reference (since #520)

client/src/components/SiteSearch/SiteSearchListing/SiteSearchListing.jsx
This PR fixes a className typo in the site search results
* [FP-1479](https://jira.tacc.utexas.edu/browse/FP-1479)
Use site search locally to test that the web results no longer use default bootstrap styles
=> Bug/FP-1479: Site Search WEB results should be purple

client/src/components/Onboarding/OnboardingUser.jsx
In `AppRouter.jsx`, there was a recent [fix](https://github.com/TACC/Core-Portal/pull/578) that fetched intro messages (`FETCH_INTRO`) for authenticated users only.  The effect was dependent on `authenticatedUser`.  In OnboardingUser.jsx, we were doing a no-longer-needed dispatch for FETCH_AUTHENTICATED_USER that was causing this bug (i.e. the loop of renders/dispatches).
* [FP-1503](https://jira.tacc.utexas.edu/browse/FP-1503)
* Remove unnecessary FETCH_AUTHENTICATED_USER dispatch
1. Go to `https://cep.dev/workbench/onboarding/setup/` and ensure it loads correctly
=> task/FP-1503: Fix onboarding

server/portal/apps/onboarding/steps/project_membership.py, server/portal/apps/onboarding/steps/project_membership_unit_test.py, server/portal/fixtures/tas/tas_project_users.json
When checking if a user is a project member, the membership step uses pytas's `projects_for_user `(ie. /v1/projects/username/) and returns a list of projects. **BUT** it does not include projects who don't have any allocations. Using get_project_users is a better approach and avoids this issue.  
https://tas.tacc.utexas.edu/TACCAdministration/Projects/EditProject.aspx?id=57877).
See [COOKS-211](https://jira.tacc.utexas.edu/browse/COOKS-211) and discussed with TAS developers on slack [here](https://tacc-team.slack.com/archives/C027DA88DRV/p1645463242246379)
* [FP-1514](https://jira.tacc.utexas.edu/browse/FP-1514)
* [COOKS-211](https://jira.tacc.utexas.edu/browse/COOKS-211)
* Use pytas's `get_project_users` instead of `projects_for_user` in determining project membership
1. Make sure you …
=> task/FP-1514: Fix project membership step to handle allocation-less projects

client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.jsx, client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.test.js, client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.jsx, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.jsx, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.test.js, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.jsx
- Adds missing `modalProps` when updating modal state after projects are listed.
- Make default dropdown selection be valid - i.e. not an item in the excluded list
- Simplify file dropdown
A bug would occur where the `modalProps` would be overwritten when switching to the base project listing, removing the `canMakePublic` prop as well as others, ultimately causing the dropdown
* [FP-123](https://jira.tacc.utexas.edu/browse/FP-1154)
1. Click around the breadcrumbs in the dropdown and confirm the dropdown items remain the same, no matter where you click.
=> FP-1154: Fix modal props

server/portal/libs/elasticsearch/unit_test.py, server/portal/libs/elasticsearch/utils.py
The `include_parent` argument in `walk_children` was defaulted to `True`, which a) is semantically misleading and b) was causing a bug where documents were being deleted during indexing because we were expecting to find them in the list of their own children.
* [FP-1528](https://jira.tacc.utexas.edu/browse/FP-1528)
Change the `include_parent` argument's default from `True` to `False`.
In the shell:
```
In [1]: from portal.apps.search.tasks import agave_indexer
In [2]: agave_indexer(${YOUR_HOME_SYSTEM}, '/', recurse=True)
```
In the portal: Search for a folder in your home directory and make sure it shows up in the search results.
=> Bug/FP-1528: Recursive indexer deletes documents it shouldn't

client/src/components/Tickets/TicketModal.jsx, client/src/components/Tickets/TicketModal.scss
* [FP-1339](https://jira.tacc.utexas.edu/browse/FP-1339)
Updated CSS to resolve visual bug
1. Open a ticket modal for a ticket that contains an attachment
2. Open the accordion to the message that has the attachment
3. Make sure that the link underline only happens on the "Download" text and not when you hover over the attachment line
4. Make sure that the "Download" text is still right aligned and otherwise visually looks like it did before.
Hovering over the attachment box
Hovering over the download text link
Previous (bad) behavior for reference
=> FP-1339: Ticket Attachment Cell Hover Underlines When Not over Link

client/src/components/_common/Paginator/Paginator.jsx
Fixed paginator endcaps having different styles
* [FP-1536](https://jira.tacc.utexas.edu/browse/FP-1536)
- Fixed a typo in the CSS module className applied to 'Next >' endcap button
1. Navigate to UI Patterns, then scroll to the **Paginator** section
2. Confirm '< Previous' and 'Next >' endcap buttons have the same text size and padding
=> bug/FP-1536: Paginator endcaps have different styles

server/conf/docker/docker-compose-dev.all.debug.yml
Update ElasticSearch version by changing out base image for docker service.
* [FP-1540](https://jira.tacc.utexas.edu/browse/FP-1540)
* Update `elasticsearch` image to one with version `7.17.0`.
</details>
1. Re-build `elasticsearch` container.
2. Enter shell in `elasticsearch` container.
3. Run `curl -XGET 'http://localhost:9200`. ([source](https://kb.objectrocket.com/elasticsearch/how-to-check-your-elasticsearch-version-from-the-command-line))
4. Confirm version of ElasticSearch is updated.
- [The fix and related patch came in version `7.16.2`.](https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2)
- [The Portal recently had its version updated to `7.17.0`.](https://github.com/TACC/Core-Portal/blob/579349b/server/poetry.lock#L545-L547)
=> FP-1540: Hotfix: Update ES to Fix Security Issue

server/portal/apps/accounts/managers/user_systems.py, server/portal/apps/accounts/managers/user_systems_unit_test.py
Currently the service account is used to generate a user's private system. A2CPS wants to use this instead of the keys service, but we need to use the user's client to generate the system instead.
* [FP-1533](https://jira.tacc.utexas.edu/browse/FP-1533)
1. In `settings_default.py`, make this your `_PORTAL_USER_ACCOUNT_SETUP_STEPS`:
```
_PORTAL_USER_ACCOUNT_SETUP_STEPS = [
{
'step': 'portal.apps.onboarding.steps.mfa.MFAStep',
'settings': {}
},
{
'step': 'portal.apps.onboarding.steps.allocation.AllocationStep',
'settings': {}
},
{
'step': 'portal.apps.onboarding.steps.system_creation.SystemCreationStep',
'settings': {}
}
]
```
2. Replace `_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEM_DEFAULT` and `_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEMS` with this:
``` …
```
=> task/FP-1533: [A2CPS] Use User Client for SystemCreationStep

client/src/components/DataFiles/DataFiles.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.jsx, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.jsx, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.test.js, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.test.js, client/src/components/DataFiles/fixtures/DataFiles.systems.fixture.js, client/src/components/DataFiles/tests/DataFiles.test.js, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py, server/portal/apps/jupyter_mounts/api/views_unit_test.py, server/portal/apps/onboarding/steps/key_service_creation_unit_test.py, server/portal/settings/settings_custom.example.py, server/portal/settings/unit_test_settings.py
A2CPS wants to enable apps, but disable the showing of private storage systems in the data files area. Since a private storage system is needed for apps, we must add a 'hidden' flag to the storage system configuration from the backend portal settings.
* [FP-1541](https://jira.tacc.utexas.edu/browse/FP-1541)
1. Add `"hidden": True` to one of your storage systems in `_PORTAL_DATA_DEPOT_LOCAL_STORAGE_SYSTEMS` in `settings_default.py`
2. Go to https://cep.dev/workbench/data/ and confirm that system is not present in the sidebar
3. Confirm you can still run and clone apps
4. Confirm the hidden system is not present in any file system selector dropdowns
=> task/FP-1541: [A2CPS] Add `hidden` flag option to data files storage systems

.github/workflows/main.yml, client/package-lock.json, server/conf/docker/Dockerfile
https://nodejs.org/en/about/releases/
LTS is now 16.x
- Minor updates to formatting in package-lock.json from bump in node version
- Minor version bumps
* [FP-1549](https://jira.tacc.utexas.edu/browse/FP-1549)
1. run `make build`
2. run `npm ci` then `npm run dev`, and ensure everything works normally
=> task/FP-1549: Update node to LTS (v16.x)

server/pyproject.toml
- Completion(?) of Poetry from https://github.com/TACC/Core-Portal/pull/356.
- Match [Core-CMS#468](https://github.com/TACC/Core-CMS/pull/468/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R119-R120) (which is trying to match Portal).
<details>
> Poetry 1.0 adds the poetry.core (a pep compliant build for use in deployments) to projects now. https://github.com/python-poetry/poetry-core
> — @taoteg 
</details>
* [FP-1461](https://jira.tacc.utexas.edu/browse/FP-1461)
Dependency bump to match version actually used.
I dunno. This is more of a proposal, and an inquiry as to whether this is a noop or not. If more consideration is necessary, I'll create a ticket.
=> Quick: Set poetry to 1.1.0 since we use 1.1.0

client/src/components/DataFiles/DataFilesTable/DataFilesTable.scss
One-liner pr for fixing header hover behavior in `DataFilesTable`.
* [FP-1538](https://jira.tacc.utexas.edu/browse/FP-1538)
Fixed css in `DataFilesTable` that caused unwanted highlight for header rows.
1. Ensure that there is no highlight on `DataFilesTable` headers (see videos below).
Before:
https://user-images.githubusercontent.com/9425579/160892350-50485b55-cdd8-45b0-9d37-1f381f9faec8.mov
After:
https://user-images.githubusercontent.com/9425579/160892392-4b2e8a53-2060-456f-a905-8922b5abea57.mov
=> Bug/FP-1538: Remove hover highlight for DataFilesTable headers.

client/src/components/Allocations/AllocationsModals/AllocationsManageTeamModal/AllocationsManageTeamModal.jsx, client/src/components/Allocations/AllocationsModals/AllocationsManageTeamModal/AllocationsManageTeamModal.module.scss
* [FP-1205](https://jira.tacc.utexas.edu/browse/FP-1205)
* [FP-1532](https://jira.tacc.utexas.edu/browse/FP-1532)
- Removed placeholder text in modal search bar
- Added italicized help text under modal search bar
1. Navigate to Allocations
2. Open 'View Team' modal for a project for which you are a PI/delegate
3. Hit 'Manage Team' button in View Team modal header
4. Confirm no text is in the search bar, and that the text “_Search by entering the full username, email, or last name._” is under the search bar.
Also in comments of FP-1532 Jira ticket, but this UI solution is more of a temp solution in the event that TAS is updated to support an "as-you-type" search functionality.
=> 737: Improve UI of user searching

client/src/components/_common/SectionHeader/SectionHeader.module.css
Retain Dashboard's "New Ticket" link style, but do **not** change Allocations' "Manage Allocations" button style.
* [FP-1543](https://jira.tacc.utexas.edu/browse/FP-1543)
* Hotfix for #623
More specific selector.
1. Load dashboard.
2. Look for small gray "Add Ticket" button.
3. Load allocations.
4. Look for big purple "Manage Allocations" button.
<details><summary>Before and After the Bug</summary>
| Before the Bug | After the Bug |
| - | - |
| <img width="1212" alt="Before" src="https://user-images.githubusercontent.com/62723358/164518037-ff2ec120-93eb-497f-98e5-571c9bc7333b.png"> | <img width="1212" alt="After" src="https://user-images.githubusercontent.com/62723358/164518034-6d530a79-41c7-48f0-8e20-6b3aebb09223.png"> |
</details>
<details open><summary>Before and After the …
=> FP-1543: No Small Primary Buttons (even in Header)

README.md, server/conf/docker/docker-compose-dev.all.debug.yml
Remove lines ~~I think~~ I accidentally added in #522 ([code](https://github.com/TACC/Core-Portal/pull/522/files#diff-67ee10ce7fc260521e9912a611ab1003a513c09ec83ddf5c5ed2c74ab198d82a])).
* [FP-1194](https://jira.tacc.utexas.edu/browse/FP-1194)
- remove two lines from docker compose (dev) file
- remove README instructions that were only for those lines
1. Run/Deploy Portal.
2. Open CMS.
3. Above steps succeed.
N/A
The CMS worked on Portal before the docker compose file change I now revert. Nothing I remember suggests this change I revert was necessary. The change I revert causes an unexpected and unnecessary dependency for Portal (and a docker mount error). I think it was an accident by me to add these (I was probably testing custom CMS project via Portal in local env).
_**Update**: This …
=> fix(docker): remove test entires in docker compose

client/src/components/ManageAccount/ManageAccountModals.jsx, client/src/components/ManageAccount/tests/ManageAccountModals.test.js, client/src/components/Tickets/TicketsLayout.scss, client/src/components/_common/AppIcon/AppIcon.jsx, client/src/components/_common/AppIcon/AppIcon.test.js, client/src/components/_common/SectionHeader/SectionHeader.module.css, client/src/redux/reducers/profile.reducers.js, client/src/redux/reducers/tests/profile.reducers.test.js, client/src/redux/sagas/profile.sagas.js, client/src/redux/sagas/profile.sagas.test.js
- FP-1618: Fix perpetual spinner after updating profile
- FP-1626: Fix username casing on Onboarding page
- FP-1630: Fix column spacing for "My Tickets"
- FP-1299: Add compress/extract icons for zippy and extract toolbar apps
* [FP-1618](https://jira.tacc.utexas.edu/browse/FP-1618)
* [FP-1626](https://jira.tacc.utexas.edu/browse/FP-1626)
* [FP-1630](https://jira.tacc.utexas.edu/browse/FP-1630)
* [FP-1299](https://jira.tacc.utexas.edu/browse/FP-1299)
- FP-1618: Fix perpetual spinner after updating profile
1. Go to https://cep.dev/workbench/account
2. Click "Update Profile", change something and click "save", and close modal
3. Confirm profile reloads and new changes are visible
- FP-1626: Fix username casing on Onboarding page
1. Go to https://cep.dev/workbench/onboarding/setup
2. Confirm …
=> bug/FP-1618, FP-1626, FP-1630, FP-1299: Various bugfixes

client/src/components/Jobs/Jobs.scss
Adds fixed widths to icon and date columns in the Jobs table views. These seem like the most jarring fields to be cut off.
* [FP-1638](https://jira.tacc.utexas.edu/browse/FP-1638)
1. Go to https://cep.dev/workbench/dashboard
2. Change screen width and confirm icons and date are shown at full width
3. Repeat for https://cep.dev/workbench/history/jobs
Are these appropriate column fields (important enough) to apply fixed widths to all screen sizes?
=> bug/FP-1638: Add fixed widths for icon and date in Jobs table

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppFormUtils.js, client/src/components/Applications/AppForm/AppFormUtils.test.js, client/src/components/Applications/AppForm/fixtures/AppForm.app.fixture.js
In [FP-1628](https://jira.tacc.utexas.edu/browse/FP-1628), it was noted that we do not update some values when switching queues and that it would be helpful to update them.  This pr refactors things so that when a queue changes, we potentially alter the values of `nodeCount`, `maxRunTime`, and `processorsOnEachNode` to match the constraints of the new queue.
* [FP-1628](https://jira.tacc.utexas.edu/browse/FP-1628)
1. Setup testing app locally:  Add an entry for (`matlab-frontera-9.9u4`) in https://cep.dev/core/admin/workspace/apptrayentry/.  **Note**:  frontera jupyter hub app could also be useful to test but its is SERIAL so the matlab frontera app is a good one to use for testing.
2. Setup testing app locally:   Add Matlab license for yourself: …
=> task/FP-1628: update app values when user changes a new queue

client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.module.scss
Fix gnarly text overflow on narrow screen for Shared Workspaces modal.
* [FP-1670](https://jira.tacc.utexas.edu/browse/FP-1670)
* Use SASS mixin.﹡
<sub>﹡ I try to steer us away from SASS, but this makes instances easier to find, thus quicker to replace. Replacements of these instances begins in https://github.com/TACC/Core-Portal/pull/639.</sub>
1. Have a shared workspace with members you can manage.
2. Open that workspace.
3. Click "Change Ownership" button (looks like link).
4. Make window size narrow.
For details, see J.R.'s description in https://github.com/TACC/Core-Portal/pull/597#discussion_r877526170.
None. I do not have a workspace with members I can manage. I do not know how to create one.[^1]
[^1]: This is a courtesy PR. I don't have bandwidth to learn how to reproduce the bug. …
=> fix(FP-1670): button text overflow (workspaces)

client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.jsx, client/src/styles/components/bootstrap.modal.css, client/src/styles/components/mui.tabs.css, client/src/styles/global.css
Make **all** Material UI Tabs styling global, and _clearly_ so (so they can be reused without copying).
<details>
Re-use of code, in the past, for this project, has not been DRY. The solution to create components has been realized too slowly. So, if third-party components have global styles, let's _clearly_ apply our overrides globally. This makes re-use automatic.
</details>
* [FP-1635](https://jira.tacc.utexas.edu/browse/FP-1635)
* intended for https://github.com/TACC/Core-Portal/pull/636
Move __all__ allocations component styles to global styles.
1. Review tabs UI from https://github.com/TACC/Core-Portal/pull/636.
2. Confirm none of it has changed.
https://user-images.githubusercontent.com/62723358/170576114-dd25ea16-e5a3-4703-a84d-99c23bd79f37.mov
=> Task/FP-1635: 737 - Implement final Allocations UI - Organize MUI CSS

client/src/components/Allocations/AllocationsModals/AllocationsManageTeamTable/AllocationsManageTeamTable.module.scss, client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.jsx, client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.module.scss
Remove unused CSS (so I can fix inaccuracies of Allocations Modal UI without being confused).
<details>
Some of this unused CSS may be from before FP-1635, but its distracting me from grok-ing and re-using styles on this complex modal.
</details>
* [FP-1635](https://jira.tacc.utexas.edu/browse/FP-1635)
* intended for https://github.com/TACC/Core-Portal/pull/636
Remove unused CSS.
1. Review tabs UI from https://github.com/TACC/Core-Portal/pull/636.
2. Confirm none of it has changed.
https://user-images.githubusercontent.com/62723358/170734862-091c5d45-ba5d-4e0a-8aea-3edb2c92123c.mov
https://user-images.githubusercontent.com/62723358/170734872-2ea13107-ce66-41ae-8c30-489acc1ac7e1.mov
=> Task/FP-1635: 737 - Implement final Allocations UI - Remove Unused CSS

client/package-lock.json, client/package.json
Install `@tacc/core-styles` from NPM.
* [FP-1647](https://jira.tacc.utexas.edu/browse/FP-1647)
* based off https://github.com/TACC/Core-Portal/pull/651
- re-install (core-styles) same version, but via npm)
Nope.
Nope.
=> feat: install core-styles via npm

README.md
Add instructions (to README) for using NPM link to live-edit Core-Styles.
* [FP-1647](https://jira.tacc.utexas.edu/browse/FP-1647)
* builds off https://github.com/TACC/Core-Portal/pull/639
- add content to README
0. Load local server with live reload (`npm run dev`).
1. Follow steps from README under "Testing Core Styles Changes Locally".
2. Find a Core-Styles stylesheet to test edit (e.g. one imported by `global.css`).
3. Open `source/_imports/settings/border.css`.
4. Change its `--global-border-width--normal` from `1px` to `10px`.
5. Save edit.
6. Watch server reload.
| 1. follow steps | 2. find stylesheet | 3. open stylesheet | 4. 5. 6. change → reload |
| - | - | - | - |
| <img width="1440" alt="FP-1647 npm link 1" src="https://user-images.githubusercontent.com/62723358/171503916-6bc55 …
=> FP-1647: Use Core-Styles via NPM Link

client/src/components/Allocations/AllocationsModals/AllocationsManageTeamTable/AllocationsManageTeamTable.module.scss, client/src/components/UIPatterns/UIPatternsButton/UIPatternsButton.jsx, client/src/styles/components/c-button--new.css
Fix disabled link erroneous background everywhere, not just allocations.
* [FP-737](https://jira.tacc.utexas.edu/browse/FP-737)
* for https://github.com/TACC/Core-Portal/pull/568/
* mimicked by https://github.com/TACC/tup-ui/pull/11
- remove fix from d60ff3e
- add disabled link to UI patterns
- fix in `c-buton--new.css` instead
1. Load allocations.
2. Make a "Remove" link/button disabled.
- I did this by adding `disabled` attribute to link/button.
4. Confirm the link/button does not have its own background.
- The result will look the same, but Developer Tools CSS will show no allocations-specific CSS for this link/button background.
| UI Pattern | Alt. Button Fix |
| - | - |
| ![UI Pattern](https://user-images.githubusercontent.com/62723358/173941261-703f0818-2d3a-4b00-99b7-80699f78c774.pn …
=> fix(fp-737): remove bkgd color from disabled link

client/src/components/Workbench/Workbench.jsx, client/src/index.jsx
Fix a bug where Core Styles was clobbering Material UI and causing tabs to disappear in the Allocations area.
* [FP-1702](https://jira.tacc.utexas.edu/browse/FP-1702)
1. Stop all running containers.
2. `npm ci && npm run build`
3. set `_DEBUG = False` in `settings_custom.py`
4. Tweak the nginx conf to prevent Django from trying to serve static files. In `server/conf/nginx/nginx.conf` line 83 should read:
> location ~ ^/(auth|workbench|tickets|googledrive-privacy-policy|public-data|accounts|api|login|webhooks|search) {
5. Restart all containers.
5. Shell into the Django container (`docker exec -it core_portal_django /bin/bash`) and run `python manage.py collectstatic`
6. Navigate to the the dev portal and check that the UI renders correctly. In your network tab, the index and vendor bundle …
=> bug/FP-1702: CSS Load Order Differs on Dev vs Local

client/src/components/Onboarding/OnboardingStatus.jsx
Somewhere in the Vite build for production, styles are ordered differently causing the `Processing` pill to be truncated when a `<LoadingSpinner>` is present. This removes that possibility by setting `shouldTruncate={false}`.
* [FP-1539](https://jira.tacc.utexas.edu/browse/FP-1539)
1. On line `9` of `client/src/components/Onboarding/OnboardingStatus.jsx`, add `step.state = 'processing';`
2. [Build vite for production](https://github.com/TACC/Core-Portal/wiki/Using-Vite-production-build-locally)
3. Go to https://cep.dev/workbench/onboarding/setup/ and confirm `Processing` is not truncated.
=> bug/FP-1539: Fix Undesired `<Pill>` truncation

client/src/redux/sagas/allocations.sagas.js, client/src/utils/fetchUtil.js, client/src/utils/fetchUtil.test.js
Fix malformed `fetch` parameters, resulting in only `GET` requests.
* [FP-1715](https://jira.tacc.utexas.edu/browse/FP-1715)
- fixed `fetchUtil`
- removed bad params in `searchUsersUtil`
1. Go to https://cep.dev/workbench/allocations/approved, click on a project you are a PI/Delegate of, and confirm you can search for and add users
2. Go to https://cep.dev/workbench/applications, submit a job, and confirm you see a `POST` request in the network tab from the client
=> hotfix/FP-1715: Fix `fetchUtil`

client/src/components/Onboarding/OnboardingStatus.jsx, client/src/components/_common/Form/FileInputDropZone.jsx, client/src/components/_common/Form/FileInputDropZone.scss
Upload icon in file drop zone too small in production environments.
* [FP-1694](https://jira.tacc.utexas.edu/browse/FP-1694)
- Increased specificity of selector for this icon in this application to take precedence in both environments.
1. [Build env for production](https://github.com/TACC/Core-Portal/wiki/Using-Vite-production-build-locally)
2. Open a ticket preview and confirm, in the file drop zone, that the upload icon takes up most of the space of the drop zone (see UI photos).
3. Confirm the same for the upload modal in Data Files.
=> bug/FP-1694: Fix background icon in FileInputDropdownSelector

README.md
We don't use Webpack now, right? We use Vite. So, don't mention Webpack. Thoughts?
N/A
- remove some words from Readme so we are not wrong now nor in the future
N/A
=> docs(README): do not mention webpack

client/src/components/DataFiles/DataFilesModals/DataFilesManageProjectModal.jsx, client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.jsx, client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.module.scss, client/src/components/DataFiles/DataFilesProjectMembers/_cells/SystemRoleSelector.jsx, client/src/components/DataFiles/DataFilesProjectMembers/_cells/_tests/SystemRoleSelector.test.js, client/src/redux/reducers/projects.reducers.js
Bugfixes for Manage Team Modal
* [FP-1696](https://jira.tacc.utexas.edu/browse/FP-1696)
- Reset the error state of the modal when it is opened.
- Lowercase role names and add explanations for USER/GUEST.
- Selector dropdown no longer cuts off role names.
- Disable adding/removing members for user/guest roles.
- Disable "Transfer Ownership" when there is no one to transfer to.
Non-admin view:
=> bug/FP-1696: Manage Team modal bugfixes

server/portal/apps/projects/models/unit_test.py, server/portal/apps/projects/models/utils.py
Fixes an issue where, for project ids with multiple hyphens, the `get_latest_project_storage` function will fail.
* [FP-1722](https://jira.tacc.utexas.edu/browse/FP-1722)
1. Change `PORTAL_PROJECTS_ID_PREFIX` to `LOCAL-CEP`
2. Create a shared workspace, and note the ID number
3. In the `core_portal_django` container, run `./manage.py projects_id --update $ID`, replacing `$ID` with the ID from step 2
4. Create another shared workspace, and confirm that it properly handles the collision
=> bug/FP-1722: Fix Shared Workspaces id and accept any amount of hyphens in `PORTAL_PROJECTS_ID_PREFIX`

client/src/components/UIPatterns/UIPatternsButton/UIPatternsButton.jsx
Describe that primary buttons are allowed for any "main" purpose button.
<details>
[One designer and I agree that a pair of primary buttons is okay, because some modals have two equally important actions.](https://tacc-team.slack.com/archives/CQUA4D5KJ/p1657752714192479) (Link expires.)
</details>
* [FP-546](https://jira.tacc.utexas.edu/browse/FP-546)
* discussed because https://github.com/TACC/Core-Portal/pull/662
- change text in dev-facing UI Patterns section
Skipped.
=> docs(ui): less specific primary button use case

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesManageProject.module.scss, client/src/components/DataFiles/DataFilesModals/DataFilesManageProjectModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.module.scss, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsSearchbar/DataFilesProjectsSearchbar.module.css, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.module.scss, client/src/components/History/HistoryViews/JobHistoryModal.jsx, client/src/components/History/HistoryViews/JobHistoryModal.module.scss, client/src/components/Onboarding/OnboardingAdminSearchbar.module.scss, client/src/components/_common/Button/Button.jsx, client/src/components/_common/Button/Button.module.css, client/src/components/_common/TextCopyField/TextCopyField.jsx, client/src/styles/components/bootstrap.form.css, client/src/styles/trumps/icon.css
Small tweaks to #662. Can be cherry-picked, merged, or delayed.
<details><summary>✓ To Do</summary>
</details>
<details><summary>… Next Up</summary>
- Test #662 — onboarding.
- (as needed) Create PR for testing review.
- Review orphaned styles in #662.
- (as time allows) Create PR for style-cleanup review.
- Submit orphaned styles review of #662.
</details>
* [FP-546](https://jira.tacc.utexas.edu/browse/FP-546)
* updates https://github.com/TACC/Core-Portal/pull/662
Each commit is an isolated change and has more detail in its full commit message.
| before 369beba | after 369beba |
| - | - |
| ![369beba before](https://user-images.githubusercontent.com/62723358/178860083-8a424f6d-de07-4381-bfc5-60feb83fff71.png) | ![369beba after](https://user-images.githubusercontent.com/62723358/178860084- …
=> Task/fp 546  UI tweaks

client/src/components/Allocations/AllocationsLayout.jsx, client/src/components/Allocations/AllocationsModals/AllocationsManageTeamTable/AllocationsManageTeamTable.jsx, client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.jsx, client/src/redux/reducers/allocations.reducers.js, client/src/redux/sagas/allocations.sagas.js, client/src/redux/sagas/tests/allocations.sagas.test.js
- Fixes an issue where the allocations manage modal was unreachable.
- Fixes an issue where a race condition would cause an infinite spinner when going to a url that pointed straight to an allocations team modal
* [FP-1772](https://jira.tacc.utexas.edu/browse/FP-1772)
1. Go to https://cep.dev/workbench/allocations/approved/manage and confirm it brings up the modal
2. Open a allocations team view modal, refresh the page, and confirm there is no infinite spinner.
a. You can simulate the race condition happening by setting `force=True` in `get_allocations` in `server/portal/apps/users/utils.py`
I've also deployed this branch to dev. You can test this out here: https://dev.cep.tacc.utexas.edu/workbench/allocations/approved/59024
=> bug/FP-1772: Allocations Modal bugfixes

client/src/components/Dashboard/Dashboard.jsx, client/src/components/Dashboard/Dashboard.module.css
Stretch column panels and adding padding-bottom if there are no rows.
* [FP-1788](https://jira.tacc.utexas.edu/browse/FP-1788)
- get panel count
- add panel count as global class (so we need not define all possible counts)
- stretch height and add space
1. Use the settings from https://github.com/TACC/Core-Portal/pull/688.
2. Verify "My Tickets" column takes up **almost** full column height. — Remember the extra space below.
3. Do not use the settings from https://github.com/TACC/Core-Portal/pull/688.
4. Verify bottom panels have the same extra space as before this branch and as in step 2.
| Sans FP-1788 Settings | With FP-1788 Settings |
| - | - |
| ![Sans FP-1788 Settings](https://user-images.githubusercontent.com/62723358/186784292-48b708d3-9356-4783-b9d6-b7fc5eb8e82b.png) | ![With …
=> Task/fp 1788  apcd manage account  support tall panels

client/package-lock.json, client/vite.config.ts
The [latest version bump of vite](https://github.com/TACC/Core-Portal/pull/693) caused some issues with vite ping. I added a port specification to to the vite config, and bumped the vite react plugin as well.
1. run `npm ci` and `npm run dev`
2. open cep.dev locally, open devtools, and confirm there is no repeating `404` error for a vite ping action
=> hotfix: update vite config and vite react plugin

.github/workflows/main.yml, server/conf/docker/Dockerfile
Poetry actions are failing. To fix this, I've updated poetry to 1.2, and bumped base images and actions to latest stable versions.
* [FP-1823](https://jira.tacc.utexas.edu/browse/FP-1823)
- bump base docker image to latest stable debian lts `bullseye`
- bump github action runner images to latest ubuntu lts `focal`
- update github actions
- bump poetry to 1.1.2
1. run `make build`
2. run `make start` and `npm run dev` in separate terminal windows
3. go to cep.dev and ensure everything works as expected
4. ensure these github actions are passing
=> fix/FP-1823: Update poetry and base docker image

.github/workflows/main.yml
Codecov's uploader is deprecated and not working today.  https://docs.codecov.com/docs/about-the-codecov-bash-uploader.  This brings the uploading using gh action in line with the uploading of the backend coverage.
@edmondsgarrett  and I noticed it wasn't working correctly earlier today and we thought codecov was just down but I just saw the deprecating notice.
=> hotfix: use codecov github action instead of deprecated bash script

server/portal/settings/settings.py
LS6 has `/home1`, not `/home` as the home dir
* [FP-1870](https://jira.tacc.utexas.edu/browse/FP-1870)
=> hotfix/FP-1870: ls6 home dir

client/src/components/DataFiles/DataFilesModals/DataFilesRenameModal.jsx, client/src/components/DataFiles/DataFilesModals/tests/DataFilesRenameModal.test.js, server/portal/settings/settings.py
Added () to accepted characters and changed error message and tests to reflect changes
* [FP-1668](https://jira.tacc.utexas.edu/browse/FP-1668)
Rename modal now allows the use of parentheses "()" and the error message will include that now as an acceptable character.
1. Go to My Dashboard >> Data Files
2. Select a Workspace from the Data Files Nav (Public Data, Shared Workspace, etc)
3. Click checkbox of data file you'd like to edit
4. Click Rename
5. When modal pops up enter a name with a invalid character like &%$ to make sure the error message says () are ok
6. When modal pops up, enter a name that includes parentheses and make sure it successfully saves
=> Added () to accepted characters and changed error message to reflect

client/src/components/Sidebar/Sidebar.jsx, client/src/components/Workbench/Workbench.jsx, client/src/components/_common/Sidebar/Sidebar.jsx, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Added boolean setting that removes the 'Add Feedback' button from the sidebar 
* [FP-1839](https://jira.tacc.utexas.edu/browse/FP-1839)
Added a `hideFeeback` boolean in `settings_default.py` that removes the Add FeedBack when set to True
1. Add `"hideFeeback": True` to `_WORKBENCH_SETTINGS` in `settings_custom.py`
2. Check that the "Leave Feedback" button is hidden at the bottom of the Workbench Sidebar
=> task/FP-1839: Feedback link in portal is configurable

client/src/components/DataFiles/DataFilesModals/DataFilesDownloadMessageModal.jsx, client/src/redux/sagas/datafiles.sagas.js
Made adjustments to the download modal
* [FP-1537](https://jira.tacc.utexas.edu/browse/FP-1537)
1. Changed size of download modal to 'md' (previously lg)
2. Renamed heading to Download (previously Download Folder)
3. After the compress job is submitted the modal closes automatically and an additional success modal does not show. 
1. Go to Data Files
2. Select some files and click Download
4. Ensure modal size is smaller than before
5. Ensure heading text is Download
6. Click compress and ensure modal closes upon success
Before: 
After:
=> Download modal adjustments

client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.jsx
Correct undesired behavior: "Back" button appears at the top of the right panel list in the Copy Modal when trying to copy a file/folder from a top level directory. The name of the top level directory also does not appear in the list.  
* [FP-1669](https://jira.tacc.utexas.edu/browse/FP-1669)
Modify how the `isNotRoot` and `hasBackButton` variables are set in the DataFilesModalListingTable component.
`isNotRoot` is set to `false` if `params.path` is either an empty string or `'/'`.
`hasBackButton` set to `isNotRoot` to follow DRY.
1. Go to Data Files.
2. From a top level directory (e.g. My Data (Frontera)) select a file or directory using the checkbox.
3. Click on the Copy button at the top right.
4. Ensure that the "Back" button does NOT appear and that the top level directory name does …
=> bug/FP-1669: fix back button in copy modal

client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.jsx, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.module.scss
Upload icon needs to be greyed out, just like the text "Upload", when the upload dropdown item is disabled.
* [FP-1859](https://jira.tacc.utexas.edu/browse/FP-1859)
Wrap the icon in a new span with the appropriate CSS className.
1. Go to Data Files
2. Select Shared Workspaces
3. Click the + Add button
4. Ensure that the upload icon is greyed out.
**Before**
**After**
=> bug/FP-1859: fix upload icon color

server/portal/apps/tickets/utils.py
The SERVER_NAME field is not getting populated in the ticket data. This field is used to quickly identify the source portal the ticket is coming from without logging into RT directly. 
* [FP-1584](https://jira.tacc.utexas.edu/browse/FP-1584)
Instead of using the SERVER_NAME header in the request (which is coming in as blank), the HTTP_HOST header is used instead which contains the name of the source portal
1. In the Portal click on Leave Feedback then click on Submit a Ticket
2. Fill out the information and submit a test ticket 
3. Go to [Request Tracker](https://consult.tacc.utexas.edu/) and find the created ticket
4. Ensure the ticket data contains the HTTP_HOST field with the correct source portal name
Before: 
After: 
The SERVER_NAME header is a field that contains the name of the …
=> FP-1584 Populating source portal name in ticket data

client/src/components/FeedbackForm/FeedbackForm.jsx
To make FeedbackForm adhere to UI Behavior Specifications with no in-modal success message and change the error to an InlineMessage rather than a Bootstrap Alert
* [[FP-1877](https://jira.tacc.utexas.edu/browse/FP-1877)]
Updated Feedback Form modal to no longer display a success message in the modal upon submission like the Confluence specifications [here](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=120455500#UIBehavior/UXModals-AfterSubmit,NoError
)
It still displays a toast with 'Message sent' upon successful submission as it did previously.
Changed React Alert for the in modal error message for the FeedbackForm to an InlineMessage to follow UI guidelines specified [here](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=120455500#UIBehavior/UXModals-Aft …
=> Task/fp 1877  replace alert with inline

client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.scss
Set text color for 'Up to 500mb' to match the text color of the other text in the +Add dropdown menu.
* [FP-1860](https://jira.tacc.utexas.edu/browse/FP-1860)
* [FP-1082](https://jira.tacc.utexas.edu/browse/FP-1082)
* [FP-1083](https://jira.tacc.utexas.edu/browse/FP-1083)
* [FP-134](https://jira.tacc.utexas.edu/browse/FP-134)
Set text color to `var(--global-color-primary--dark)` from `var(--global-color-primary--xx-dark)`
1. Click on Data Files, then click on the +Add button.
2. Ensure the text color of 'Up to 500mb' matches the color of the other text in the dropdown menu.
**Before**
**After Feedback from Wes & Design on 11/2/22**
**Current state:**
The colors of the button text in the "+ Add" dropdown are specified in `DataFilesSidebar.scss`.
The color of the text "Up to 500mb" is …
=> bug/FP1860: match css text color for 'Up to 500mb' text

server/portal/apps/workspace/api/views.py, server/portal/apps/workspace/api/views_unit_test.py
Implements job re-submission/cancel behavior in backend ([which was implemented in the frontend with the job listing PR](https://github.com/TACC/Core-Portal/blob/21dbf74c976dfa3eff61f690ffe10c6961f0955d/client/src/components/History/HistoryViews/JobHistoryModal.jsx#L92)).
Job submission through the app form is related to #730 I think, which is what Nathan is working on.
* [TV3-55](https://jira.tacc.utexas.edu/browse/TV3-55)
Modify job resubmit/cancel in the backend.
1. Go to history section (https://cep.test/workbench/history/jobs).
2. Click on "View Details" for a job. (assuming that there are jobs run previously)
3. Click on "Resubmit Job".
4. Ensure that the job resubmits correctly.
I've removed the use of `JobSubmission` when resubmitting a job assuming that the tag information …
=> Task/TV3-55: Job (re)submission backend

client/src/components/Allocations/AllocationsModals/AllocationsRequestModal/AllocationsRequestModal.jsx, server/portal/fixtures/system_monitor/index.json, server/portal/fixtures/system_monitor/index_frontera_not_running.json, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Removed Longhorn from system monitor, data files, and app input
* [FP-1943](https://jira.tacc.utexas.edu/browse/FP-1943)
- Removed Longhorn from system monitor display list in settings 
- Updated system monitor fixtures removing Longhorn
1. [Go to cep.test/workbench/dashboard](https://cep.test/workbench/dashboard)
2. Check that the system monitor no longer displays Longhorn
3. Go to Applications
4. Select an app
5. Under Inputs, click the Select button under Input Directory and make sure My Data (Longhorn) is not in the drop down
6. Go to Data Files
7. Make sure My Data (Longhorn) is no longer displayed
8. Go to Allocations
9. Click Request New Allocation
10. Check the the first line says For Frontera: not For Frontera or Longhorn:
Dashboard
Data Files
Applications
Allocations
=> task/FP 1943 Remove retired Longhorn from system monitor

server/portal/apps/projects/management/commands/migrate-projects_unit_test.py, server/portal/apps/projects/management/commands/projects_id_unit_test.py, server/portal/apps/projects/models/unit_test.py, server/portal/apps/projects/unit_test.py, server/portal/libs/agave/models/systems/base_unit_test.py, server/portal/libs/agave/utils.py, server/portal/settings/settings.py, server/portal/settings/settings_default.py, server/portal/settings/settings_secret.example.py, server/portal/settings/unit_test_settings.py
Enables the use of a long-live Tapis v3 JWT by the portal service account, via the `service_account()` method
1. Grab the `_TAPIS_ADMIN_JWT` setting from [stashe](https://stache.utexas.edu/entry/bedc97190d3a907cb44488785440595c), and invoke the `service_account` to make tapis client requests
=> Tapis v3 long-live client

server/portal/apps/onboarding/steps/system_access_v3.py, server/portal/libs/agave/operations.py, server/portal/libs/agave/utils.py
Updates the TV3-82 onboarding branch: 
- Change order of operations so that credentials aren't tested until after they're registered in the key service.
- Add a step that uses the service account to give read/write/modify permissions to users on systems. This will make file operations respect POSIX permissions on the underlying system.
- Update operations for listing/mkdir for testing.
=> task/TV3-82--perms: Set system permissions during onboarding

server/conf/cms/secrets.sample.py, server/conf/docker/docker-compose-dev.all.debug.yml
After #752, the CMS index links no longer routed correctly (or maybe they never did). This PR fixes that issue, as well as updates/simplifies the CMS settings and pins the CMS version.
- Pin CMS version to v3.9.1 (latest versioned release), to prevent breaking changes in the `latest` tag from affecting local Core Portal development.
- Fix the `ES_DOMAIN` setting in `secrets.sample.py`
- Simplify local CMS settings in `secrets.sample.py` by leveraging defaults in the Core-CMS `settings.py`
1. Make sure all containers are not running
2. Update the `secrets.py` file for local CMS: `cp server/conf/cms/secrets.sample.py server/conf/cms/secrets.py`
3. Run `docker-compose -f server/conf/docker/docker-compose-dev.all.debug.yml pull cms`
4. Run migrations in the `core_portal_cms` container
5. Make …
=> Hotfix: Update CMS configurations

client/src/components/Submissions/Submissions.jsx, client/src/components/Submissions/Submissions.module.scss, client/src/components/Submissions/Submissions.test.js, client/src/components/Workbench/Workbench.jsx, client/src/components/Workbench/WorkbenchSidebar/WorkbenchSidebar.jsx
Call the `/submissions/check-submitter-role/` endpoint to determine if active user has permissions to view the Submissions component.
* [FP-1986](https://jira.tacc.utexas.edu/browse/FP-1986)
* https://github.com/TACC/Core-CMS-Custom/pull/118
1. Go to https://apcd-qa.tacc.utexas.edu/workbench/data-submission/
a. If you have a role in `['APCD_ADMIN', 'SUBMITTER_ADMIN', 'SUBMITTER_USER']`, you should be able to access the Submissions component and submit a file.
b. If you don't have a role in `['APCD_ADMIN', 'SUBMITTER_ADMIN', 'SUBMITTER_USER']`, then you should not be able to access the Submissions component, and instead see the screenshot below.
=> task/FP-1986: Restrict APCD submissions access

client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesMoveModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.jsx, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.jsx, client/src/components/Toasts/Toast.test.js, client/src/utils/systems.js, client/src/utils/systems.test.js
The goal for this was to fix issues with incorrect system name appearing and systems not being shown.
The main issue behind these bugs was that the `system` field in a systems list is not unique for v3 (e.g both My Data (Work) and Community Data have the system field as cloud.data.community). In order to ensure a unique system is selected I added the additional use of the fields `homeDir` and `scheme` to ensure a unique system is selected.
* [TV3-107](https://jira.tacc.utexas.edu/browse/TV3-107)
* [TV3-120](https://jira.tacc.utexas.edu/browse/TV3-120)
Fix for TV3-107:
- Instead of just using the system field also concatenated the homeDir field to get a system
Fix for TV3-120: 
- To get the correct display name, also added an additional parameter of scheme to findSystemDisplayName which …
=> task/TV3-107 & TV3-120 - Fix incorrect and missing systems

client/src/components/DataFiles/DataFilesModals/DataFilesShowPathModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesUploadModal.jsx, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.jsx
- Fixes an error where the Google Drive system would fail to render in datafiles
- Fixes paths in the upload and view path modals
1. Confirm you can go to https://cep.test/workbench/data/googledrive/private/googledrive/ without the UI breaking
2. Confirm the View Path modals show correct values for all tapis systems
3. Confirm the Upload modal shows the correct paths
=> Quick: Fix datafiles paths in modals

client/src/components/DataFiles/DataFilesListing/DataFilesListing.test.js, client/src/components/DataFiles/DataFilesTable/DataFilesTable.jsx, client/src/components/DataFiles/DataFilesTable/DataFilesTable.test.js, client/src/redux/sagas/datafiles.sagas.js, server/portal/apps/accounts/managers/accounts.py, server/portal/apps/accounts/managers/unit_test.py, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py, server/portal/libs/agave/utils.py
In Tapis v2, a failed file listing call on a system returned a `502` error. In v3, a failed file listing returns `500`. Treat these `500` responses as a need for the user to push keys and create a user credential for the system.
* [TV3-154](https://jira.tacc.utexas.edu/browse/TV3-154)
1. Via command line, delete your frontera credential, replacing `$USERNAME` with your username:
a. `client.systems.removeUserCredential(systemId='frontera', userName=$USERNAME)`
2. Wait a few minutes for the cache to clear in Tapis
3. Go to https://cep.test/workbench/data/tapis/private/frontera
4. Confirm you get the prompt to push keys.
5. Push keys and confirm the process works.
=> bug/TV3-154: Treat `500` errors from file listings as need for keys

server/portal/apps/accounts/api/views/systems.py
Add 10s delay to work around tapis-ssiue
* [TV3-163](https://jira.tacc.utexas.edu/browse/TV3-163)
You might need to add resource_set='dev' to the client initialization to test it out.  Thanks @shayanaijaz 
Testing is same as https://github.com/TACC/Core-Portal/pull/788:
1. Via command line, delete your frontera credential, replacing `$USERNAME` with your username:
a. `client.systems.removeUserCredential(systemId='frontera', userName=$USERNAME)`
2. Wait for the cache to clear in Tapis
3. Go to https://cep.test/workbench/data/tapis/private/frontera
4. Confirm you get the prompt to push keys.
5. Push keys and confirm the process works.
6. Confirm the file listing works and we never see the "push keys" prompt.
* [TV3-164](https://jira.tacc.utexas.edu/browse/TV3-164) is the follow on issue to …
=> task/TV3-163: Add 10 s delay to workaround tapis-issue

server/portal/libs/agave/models/systems/base.py, server/portal/libs/agave/models/systems/base_unit_test.py, server/portal/settings/settings.py, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py, server/portal/settings/settings_secret.example.py, server/portal/settings/unit_test_settings.py
Removed unused `AGAVE` settings and their usages in the code
* [TV3-166](https://jira.tacc.utexas.edu/browse/TV3-166)
- Removed all `AGAVE` settings from the static settings files 
- Refactored code to use new Tapis settings 
1. Update secrets file by removing the `Agave Tenant` and `Agave Client Configuration` settings
2. Make sure app builds and runs fine
No UI changes
Once this is approved we can also go in and update the existing v3 secret files and stache entries and remove the Agave settings
=> task/TV3-166 Remove Unused Agave Settings

server/portal/apps/auth/backends.py, server/portal/apps/auth/unit_test.py
Previously we were relying on a call to Tapis profiles `userinfo` to retrieve a user's name and email. Now, we will use TAS to get that info.
This PR also adds some error handling and cleans up the user model creation/updating step.
* [TV3-169](https://jira.tacc.utexas.edu/browse/TV3-169)
1. Confirm logging into the portal works
2. Change your name or email in LDAP, and wait a few minutes for it to update in TAS: https://accounts.tacc.utexas.edu/profile
3. Logout and back into the portal, and confirm your info has updated under manage account
=> task/TV3-169: Replace tapis profile info with TAS info

client/src/components/DataFiles/DataFilesProjectMembers/_cells/SystemRoleSelector.jsx
This might be contributing to weird uWSGI Harakiri errors we're seeing when trying to add users to Shared Workspaces.
* [TV3-172](https://jira.tacc.utexas.edu/browse/TV3-172)
- Prevent refetching of user roles in the Team Members modal on remount/focus change.
=> Task/TV3-172: Prevent excessive refetching of user roles.

client/src/utils/systems.js
Adds `cloud.data` to the list of aliases for "corral"
1. Go to https://cep.test/workbench/data/tapis/private/cloud.data/ and confirm the breadcrumb reads "Corral" instead of "Cloud"
=> Quick: add cloud.data as alias for corral

server/portal/fixtures/system_monitor/index.json, server/portal/fixtures/system_monitor/index_frontera_not_running.json, server/portal/fixtures/system_monitor/index_missing_frontera.json, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
Remove Maverick2 from _SYSTEM_MONITOR_DISPLAY_LIST in settings now that the system is retired
- Removed sysmon fixtures that include Maverick2
- Removed Maverick2 from _SYSTEM_MONITOR_DISPLAY_LIST in settings
1. Go to cep.test and make sure Maverick2 no longer appears in the system monitor
From Sal for deployment - 
> We'll have to remove it from each portal config in [https://github.com/TACC/Core-Portal-Deployments](https://github.com/TACC/Core-Portal-Deployments), and redeploy each individually
=> Remove Maverick from sysmon and from sysmon fixtures

server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
TAS no longer houses a user's MFA pairing status. For now, we need to disable the MFAStep onboarding step from all portals by removing that step from _PORTAL_USER_ACCOUNT_SETUP_STEPS.
* [WI-39](https://jira.tacc.utexas.edu/browse/WI-39)
1. Reset your "Multi-Factor Authentication" step in http://cep.test/workbench/onboarding/admin
2. Pull down this PR
3. Log out and back in, and confirm you bypass that step without needing to resolve it
=> fix/WI-39: Remove `MFAStep` from onboarding steps

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppFormSchema.js, client/src/components/_common/Form/FormField.jsx, client/src/styles/elements/text-semantics.css, client/src/styles/global.css
After discussion with CMD, we came down on this design:
- client apps have more complex required Parameters
- wma apps have less complex required Parameters
- regardless who owns the app:
- add Parameters section
- describe parameters well
- after each label's text, but before [Required] add "(containerArgsOrWhatever)"
- avoid the term "Advanced"
* [TV3-176](https://jira.tacc.utexas.edu/browse/TV3-176)
1. Go to https://cep.test/workbench/applications/qgis?appVersion=3.30
2. Confirm you get the correct sub-categorization in parentheses for all items under "Parameters"
3. Confirm links in parentheses work
=> task/TV3-176: Revised `parameterSet` view in AppForm

README.md
After I followed the readme to do a local setup, I found two steps where more details could have helped. 
There are two updates here:
* For the step, go to browser and check https://cep.test, this step needs to happen after local setup is complete. Add a note to add that info.
* For local client, npm run dev is needed when debug setting is on. Without that the requests to cep.test:3000 fail and nothing works. Added a note for that.
Look at preview
NA
NA
=> Task/update-readme: Minor update to readme to add a bit more context to local build step

server/conf/docker/docker-compose-dev.all.debug.yml, server/conf/docker/docker-compose.yml
Change the Core Portal Docker image to be `:latest` not `:tapisv3`.
> **Warning**
> I do **not** know if this is a correct solution.
* hotfix for #704
- **changed** `:latest` to `:tapisv3`
0. `make stop`
1. `make build`
2. `make start`
3. `python manage.py migrate`
Verify **no** `Error response from daemon: manifest for taccwma/core-portal:tapisv3 not found: manifest unknown: manifest unknown`. Verify portal is accessible at https://cep.test (assuming you set that up correctly prior to this PR).
N/A
- [(internal) identification of problem and possible solution](https://tacc-team.slack.com/archives/C04TQ1P04UX/p1687882006083509?thread_ts=1687812398.730479&cid=C04TQ1P04UX)
=> fix(docker): use `latest` not `tapisv3` image

README.md, client/src/components/SystemStatus/SystemStatus.jsx, client/src/components/SystemStatus/SystemStatus.module.scss, client/src/components/_common/SectionContent/SectionContent.layouts.module.css, client/src/components/_common/Sidebar/Sidebar.module.css
Fix various UI issues in #807.
* [WP-43](https://jira.tacc.utexas.edu/browse/WP-43)
* [TUP-514](https://jira.tacc.utexas.edu/browse/TUP-514)
* builds upon #807
- **fixed** two relevant bugs (4421eb93, af76710)
- **changed** Section layout to `twoColumn` (e2d96d0)
- **changed** code to align tables vertically (e2d96d0)
- **added** override of `twoColumn` layout media queries with container queries (e2d96d0)
- **removed** `SectionTableWrapper` around single-row (i.e. no-need-to-scroll) table (e2d96d0)
1. Review "System Status" section at various screen heights and widths.
2. System Status table should scroll (when space is limited).
3. System Monitor table should never scroll.
4. The "System Status" section tables should be:
- half-width on a wide screen
- full-width on a narrow screen* …
=> task/WP-43 - System Monitor UI Update - UI Tweaks

client/src/components/SystemStatus/SystemStatus.jsx, client/src/components/_common/Sidebar/Sidebar.jsx, client/src/components/_common/Sidebar/Sidebar.module.css
Support sidebar with items that do not have icons.
* new feature first used by #807
- **added** class to SidebarItem Icon
- **changed** SidebarItem icon to not appear if no iconName given
- **changed** SidebarItem text to only have padding-left if icon is present
- **changed** SystemMonitor to not pass empty iconName
1. Verify "System Status" section sidebar items' left-aligned text is the same distance from edge of section as would be a sidebar item with an icon.
=> task/WP-43 - System Monitor UI Update - Sidebar Without Icons

README.md
Fix an inaccurate description for one branch prefix.
* fixes mistake in #814
* **changed** misleading text
1. Compare our short descriptions to [longer descritpions I found](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13#types)
N/A
We can use these branch names to help auto-generate changelogs for GitHub releases. I am testing it in TACC/Core-Styles ([workflows](https://github.com/TACC/Core-Styles/tree/main/.github), [release with relevant PRs](https://github.com/TACC/Core-Styles/releases), [labels](https://github.com/TACC/Core-Styles/labels), [guide](https://tiagomichaelsousa.dev/articles/stop-writing-your-changelogs-manually)).
=> docs: fix bad desc of branch prefix "style"

client/src/components/DataFiles/DataFilesTable/DataFilesTable.jsx
Fixes an issue (related to #830) where the client would crash if the system doesn't exist.
* [WP-40](https://jira.tacc.utexas.edu/browse/WP-40)
1. Go to https://cep.test/workbench/data/tapis/private/cloud.corral
2. Instead of crashing, displays the default error message.
=> Quick: Catch edge case in #830

server/portal/apps/projects/workspace_operations/shared_workspace_migration.py
In Tapis v3, system ids cannot include numbers. To get around this, we need two system prefixes to perform migrations.
1. Tested migrating the [3DEM PPRD portal](https://3dem-staging.tacc.utexas.edu/)
=> Quick: handle 3dem workspace migrations

server/portal/apps/accounts/api/views/systems.py
Removing 10 second delay that was added as a workaround for a tapis cache issue mentioned [here](https://github.com/tapis-project/tapis-files/issues/58). The latest Tapis release has a fix for this cache delay
* [TV3-164](https://jira.tacc.utexas.edu/browse/TV3-164)
- Removed the manual 10 second delay 
1. Via command line, delete your frontera credentials, replacing `$USERNAME` with your username:
a. `client.systems.removeUserCredential(systemId='frontera', userName=$USERNAME)`
2. Wait for cache to clear in Tapis 
3. Go to My Data (Frontera) and go through the push keys process. Ensure file listing works as soon as the modal closes
No UI Changes
=> task/TV3-164 Remove 10 second system credential delay

client/src/components/SystemMonitor/SystemMonitor.jsx
Includes fix for a bug where the `Running` and `Waiting` fields in System Monitor component appeared blank when a system is unoperational
* [WP-45](https://jira.tacc.utexas.edu/browse/WP-45)
- Modified an if statement that now checks if job `running` and `waiting` values are defined or not
1. To simulate some test data, go to `server/portal/apps/system_monitor/views.py` and replace line 41 with the following snippet
<details>
<summary>View Snippet</summary>
```js
systems_json = {
"Lonestar6": {
"display_name": "Lonestar6",
"tas_name": "lonestar6",
"hostname": "ls6.tacc.utexas.edu",
"system_type": "COMPUTE",
"timestamp": "2023-07-25T15:30:11.219662+00:00",
"online": True,
"reachable": False
},
"Stampede2": {
"display_name": "Stampede2",
"tas_name": "stampede4",
"hostname": …
```
=> bug/WP-45 Fix Sysmon blank fields for unoperational systems 

client/src/components/History/HistoryViews/JobHistoryModal.jsx
Goal for this task was to add a `Cancel Job` action for a job in the job details before it is completed.
* [WP-75](https://jira.tacc.utexas.edu/browse/WP-75)
1- Added a Cancel Job button in the Jobs Detail view and added a cancel job flow that is kicked off after button is clicked
1. Go to Applications in the Portal and using any Application submit a job
2. Go to the History tab and go to the job details of the job you submitted
3. Ensure Cancel Job button is visible
4. Click on Cancel Job and ensure modal closes and job status is updated. Will need to enable webhook notifications for status to update without page refresh
=> task/WP-75  Implement cancel job action

server/portal/libs/agave/operations.py, server/portal/libs/agave/operations_unit_test.py
Fix a bug where multiple users' files could appear in search results in Data Files
* [WP-230](https://jira.tacc.utexas.edu/browse/WP-230)
- use the path as a prefix when querying the Files index, so that search results do not contain files from out of scope.
- Perform a listing before the search query to double check that the client performing the search has access to the files.
1. Perform a search in the Data Files area and make sure no other users' files appear in the listing.
=> bug/WP-230: Prevent other users' files from appearing in search results

server/portal/apps/users/views.py
For CEPv2: Address a security issue where a call to /api/users would return all user profiles if a query string wasn't passed.
=> CEPv2: Prevent user search endpoint from returning all user profiles

server/portal/apps/webhooks/views.py, server/portal/apps/workspace/api/utils.py, server/portal/apps/workspace/api/views.py
Fixes an issue where after timing out an interactive job is displayed as FAILED when in fact the job was successful and should have the FINISHED state because it timed out after reaching the maximum allotted time.  
* [WP-189](https://jira.tacc.utexas.edu/browse/WP-189)
The changes implemented here are on the portal side where a check is made to confirm if the job is interactive and whether or not it ended because of a timeout. On the tapis side the job state remains `FAILED` but we are able to use the exit code provided in the `remoteResultInfo` attribute of a job to determine if it was a timeout and display a success message on the portal side. This change is made in `JobsView` and `JobsWebhookView` endpoints 
1. Enable webhook notifications in order to see job status updates without …
=> task/WP-189 Handle timeout exit code for interactive app jobs

client/jest.config.js, client/jest.setup.js
Running unit tests results in a lot of errors, this change adds some options in the settings to hide various levels of warnings, errors, etc.
* [WP-172](https://jira.tacc.utexas.edu/browse/WP-172)
Added setting to jest configuration that can be uncommented to suppress various levels of logging. Also added the "verbose" option to make the unit test output nicer looking.
1. In client/jest.setup.js uncomment log levels 
2. Run tests and verify that the log levels are suppressed
With all log levels suppressed
=> WP-172: Minimize unit test warnings

client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.jsx, client/src/components/DataFiles/DataFilesModals/tests/DataFilesCopyModal.test.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.jsx, client/src/redux/sagas/projects.sagas.js
The goal for this was to fix a bug where no backend requests were sent when doing a file copy operation from a private system to a shared workspace. 
Upon further investigation this bug seems to stem from a previous PR [bug/FP-1567](https://github.com/TACC/Core-Portal/pull/619). In that PR a [side effect](https://github.com/TACC/Core-Portal/pull/619/files#diff-935654badc41f6dce6ff84b12fbeb2f09d08fec0e1d6441c641d0347c0225550R14) was added that cleared the data file selection whenever a shared workspace listing happened to fix a toolbar bug that was occurring. Due to this, when a file is selected for copy and the user selects a shared workspace to copy it to, the `getProjectsListing` saga clears the selected file in the state, and since there is no file to copy anymore no backend request …
=> bug/WP-249 Shared Workspace Copy Bug Fix

client/src/components/SystemStatus/SystemStatus.jsx, client/src/redux/sagas/systemMonitor.sagas.js
On the portal dashboard and System Status page, the system list was not in alphabetical order. The default selection on System Status page was Frontera which appeared last in the list due to the system list not being sorted alphabetically. This has been fixed to sort the systemList in alphabetical order in both places and fix the default selector to be first item or Frontera.
* [WP-228](https://jira.tacc.utexas.edu/browse/WP-228)
* Added code to sort the result of system monitor api call in the `src/redux/sagas/systemMonitor.sagas.js` file
1. Log onto the portal and go to the main Dashboard
2. Ensure the System Status in the right appears in alphabetical order
3. Navigate to the System Status page by clicking on the System Status sidebar item and ensure system list is in alphabetical …
=> Fixed sorting for system list

client/src/components/DataFiles/DataFilesModals/DataFilesMoveModal.jsx, client/src/redux/sagas/datafiles.sagas.js
Bug fixes for file operations noticed in shared workspaces. The bugs were mostly due to being in the root of a system and having blank strings as paths and not necessarily related to any shared workspace functionality itself. Bugs that were fixed include: 
- Page breaking when a move modal was opened in a shared workspace 
- Move operation failing when moving file to the root of a system
- Rename operation failing when renaming a file located at the root of a system
* [WP-262](https://jira.tacc.utexas.edu/browse/WP-262)
- Simplified some code and added `'/'` to arguments to ensure paths are never empty strings
1. Go to a Shared Workspace and test out the `move` and `rename` functionality and ensure everything works smoothly
No UI changes
=> bug/WP-262 Workspace file operations bug fixes

client/src/components/Jobs/Jobs.jsx, client/src/components/Jobs/Jobs.test.js, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.jsx, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss, server/portal/apps/workspace/api/views.py
Includes fix for JobsView component in the History section not showing more than 50 jobs. This was due to a bug in the InfiniteScrollTable component.
* [WP-52](https://jira.tacc.utexas.edu/browse/WP-52)
- Made minor changes to `InfiniteScrollTable` layout and css to make onScroll event handler work again
- Tweaked logic for scroll value calculations to correctly determine when bottom of page is reached 
- Added logic when dispatching `GET_JOBS` saga to ensure multiple requests are not sent
- Tweaked `getJobSearchList` Tapis query to use the `skip` parameter instead of `startAfter` since startAfter is not implemented yet
1. Go to the History section in the portal 
2. In order to test infinite scroll functionality make sure you have more than 50 jobs submitted or change the `LIMIT` value on …
=> bug/WP-52 Jobs View Infinite Scroll Fix

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppFormSchema.js, client/src/components/Applications/AppForm/AppFormUtils.js
TAPIS V3 provides a mechanism to pass in path to copy input contents into. This path is optional. 
From tapis docs:
_"A JobFileInput object is complete when its sourceUrl and targetPath are assigned; this provides the minimal information needed to effect a transfer. If only the sourceUrl is set, Jobs will use the simple directory or file name from the URL to automatically assign the targetPath. Specifying a targetPath as “*” results in the same automatic assignment."_
[TAPIS V3 doc](https://tapis.readthedocs.io/en/latest/technical/jobs.html)
* [WP-211](https://jira.tacc.utexas.edu/browse/WP-211)
* App Form: Add support for "targetPath" of a fileInput
* Add form field for target path when processing file inputs
* When populating job data, retrieve target path info and populate it according …
=> Task/WP-211: App Form updates to allow target path

client/src/components/Applications/AppForm/AppForm.jsx, server/portal/apps/datafiles/views.py, server/portal/settings/settings.py, server/portal/settings/settings_default.py
- Fixes case where the default system is not the first system in the list
- Fixes case where no default is set, and sets first system as default if so
- Adds the scratch filesystem, and removes the my data corral filesystem
- Sets the work filesystem as default locally
1. Spin up the portal and confirm the work filesystem is default
2. Confirm the scratch filesystem also works
3. Remove the `default` flag from the work filesystem in `_PORTAL_DATAFILES_STORAGE_SYSTEMS` and confirm work is still set as default
4. 3. Remove the `default` flag from the work filesystem in `_PORTAL_DATAFILES_STORAGE_SYSTEMS` and make another filesystem default, and confirm that system now shows as default
=> Quick: handle missing default system; enable work as default system locally

client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.scss
The triangle bit of the Data Files Add menu dropdown is not centered. This fix makes the dropdown centered and also makes the "Add" button centered.
* [WP-276](https://jira.tacc.utexas.edu/browse/WP-276)
* Changed width of Add button
* Added margin to the drop down menu before and after it is clicked
1. Navigate to portal > Data Files > Add button
2. Check if the "Add" button and dropdown triangle is centered
=> Bug/WP-276: Fixed Data Files Add button dropdown off-centered UI

server/portal/apps/site_search/api/unit_test.py, server/portal/apps/site_search/api/views.py, server/portal/libs/agave/operations.py
Public and community data system site search currently fails, due to a missing client for a files listing safety check.
* [WP-298](https://jira.tacc.utexas.edu/browse/WP-297)
1. Search in the site search and confirm it does not fail, both logged in and logged out
=> bug/WP-297: Fix site search for public and community data

client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.jsx, client/src/components/DataFiles/DataFilesBreadcrumbs/DataFilesBreadcrumbs.scss, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.scss, client/src/styles/components/dropdown-menu.css
Do **not** duplicate dropdown-menu styles (to resolve https://github.com/TACC/Core-Portal/pull/866#discussion_r1341649579).
* improve #866
- **added** `dropdown-menu.css`
- **changed** Data Files Breadcrumbs & Sidebar to use new CSS component
- **changed** Data Files Breadcrumbs to use **temporary** ID[^1] for specificity
[^1]: Use of ID for this is **not** recommended, hence "temporary". See [UI - CSS Style Guide - Specificity @ IDs in CSS](https://confluence.tacc.utexas.edu/display/~wbomar/UI+-+CSS+Style+Guide+-+Specificity#UICSSStyleGuideSpecificity-IDsinCSS).
1. Open https://cep.test/workbench/data/.
2. Navigate to a deeply-nested folder.
3. Open [ + Add ] and [ Go to ... ] menus.
4. Verify UI matches #866.
5. If UI differs, verify UI matches …
=> task/WP-65-DropdownViewFullPath - dropdown-menu css component 

client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.jsx, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.jsx, client/src/components/DataFiles/DataFilesStatus/DataFilesStatus.jsx, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.jsx
Some variable names and props in the DataFiles components weren't descriptive enough. This change fixes that to the extent without changing the original intention of the code. Also some of the variables needed destructuring which this achieves.
* [WP-66](https://jira.tacc.utexas.edu/browse/WP-66)
* Changed some variables names
* Updated propTypes where missing
* Destructured some objects
1. Go to Data Files and making sure functionalities work as expected without breaking anything
No visible UI change expected from this PR
=> Task/WP-66: Refactored some variables and props to include proptypes

client/src/components/Jobs/JobsSessionModal/JobsSessionModal.jsx, client/src/components/Jobs/JobsStatus/JobsStatus.jsx, server/portal/apps/projects/workspace_operations/shared_workspace_migration.py, server/portal/apps/webhooks/views.py
Some apps may require additional, freeform information to be rendered to the interactive session modal. This PR takes the "message" param from a webhook if it exists and renders it to the user.
* [WP-315](https://jira.tacc.utexas.edu/browse/WP-315)
1. Update your settings_secret.py with https://stache.utexas.edu/entry/bedc97190d3a907cb44488785440595c
2. Uncomment the lines under "DEV TENANT SETTINGS" to enable the dev tenant locally
3. Sign out and back in to https://cep.test/login
4. Run `./manage.py import-apps -c` in your local `core_portal_django` container to get the latest apps
5. Run an Rstudio session at https://cep.test/workbench/applications/rstudio?appVersion=4.3
6. Confirm the interactive session modal includes a message with a session password
Inviting feedback on how this …
=> task/WP-315: Handle interactive session messages

server/portal/apps/tickets/rtUtil.py
The rtpy documentation is misleading: https://python-rt.readthedocs.io/en/latest/rest1.html#rt.rest1.Rt.create_ticket 
Specifying "Requestors" instead of "Requestor" as we've been doing causes the requestors to be added AFTER ticket creation, meaning no one gets an email confirmation.
* [WP-319](https://jira.tacc.utexas.edu/browse/WP-319)
- pass `Requestor` instead of `Requestors` to the create_ticket util.
1. Submit a ticket through the portal and check that you get a confirmation email.
=> bug/WP-319: Fix email confirmation for tickets

server/portal/apps/projects/views.py, server/portal/apps/search/tasks.py, server/portal/libs/agave/operations.py, server/portal/libs/agave/operations_unit_test.py, server/portal/libs/elasticsearch/docs/base.py, server/portal/libs/elasticsearch/utils.py
Implements workspace search that matches the new tapis v3 implementation of workspaces/projects
* [WP-164](https://jira.tacc.utexas.edu/browse/WP-164)
- Simplified `IndexedProject` document wrapper to more closely resemble the actual response that is sent to the frontend 
- Added new shared task that indexes the projects 
- Added elasticsearch query for when a `query_string` parameter is sent in a get projects request
- Fixed a bug that was causing file listing search within shared workspaces to not work
1. Setup search index using instructions from the Core Portal [README](https://github.com/TACC/Core-Portal#setting-up-search-index)
2. Go to shared workspace and test out the search functionality. The title field for a workspace is search on at the moment 
3. Go into a shared workspace …
=> task/WP-164 Implement Workspace Search

client/src/components/Onboarding/OnboardingAdmin.jsx, client/src/components/Onboarding/OnboardingAdmin.module.scss
The onboarding Admin page has checkbox to filter users whose onboarding steps aren't complete. This makes it easier to view users who have Allocations and System Access steps not completed. 
* [WP-32](https://jira.tacc.utexas.edu/browse/WP-32)
* Added Checkbox component
* Added new handler toggleShowIncomplete based on user interaction with checkbox
* Replaced users with filteredUsers
1. Create a new file `users.jsx` and add dummy users (https://gist.github.com/asimregmi/891566eab2ecf34b71d26f6d226be10c)
2. Add the following code to `OnboardingAdmin.jsx`
Import : `import dummyusers from './users'`
In line 243, remove { users }
In line 246: `const users = useSelector((state) => dummyusers)`
Another testing method: Add new entry to the props from the React dev tools, but might be …
=> Task/WP-32--onboarding page filter show  incomplete

client/src/utils/doesClassExist.js, client/src/utils/doesClassExist.test.js
During the testing session, we realized that all app icons in the categories are defaulting to icon-applications instead of their unique icon or the category icon on dev.cep and frontera (dev) sites. The previous PR WP-273 was working correctly on cep.test, however once deployed to dev/pprod, the logic failed. Wanted to investigate where there was a difference between local env and dev/pprod env.  
Portals: cep, frontera.
* [WP-355](https://jira.tacc.utexas.edu/browse/WP-355)
- In the doesClassExist function, added a second check in the if statement to see if either ::before or :before pseudos existed after the className. 
- In the stylesheet/css files we were using to check for classNames--all the css rules have ::before after the icon classNames. However, once the css file was being …
=> task/WP-355: Fixing issue with icons on dev/prod sites

client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.jsx, server/portal/apps/projects/views.py, server/portal/apps/projects/workspace_operations/shared_workspace_operations.py
Workspace search is crashing when parsing results.
Root cause: 
* Results are returned from search index and not the tapis api response results. For example, some items in search index does not have certain fields (like name) indexed.
* Results are retrieved from all users.  For example: searching for "test" brings various results from search index which should not be visible to the user.
* [WP-354](https://jira.tacc.utexas.edu/browse/WP-354)
* Use the search results and find the matching ones from api. Provide the api result json instead of what is indexed.
* Search results are filtered to what is visible to the user.
* Add protection in js code to avoid crash
Local testing:
1. with search match
2. with no matches
3. with no query
Testing on dev.cep:
1. Crash with out the fix. Search for …
=> Bug/WP-354: Workspace search - filter results visible to user

server/portal/apps/site_search/api/unit_test.py, server/portal/apps/site_search/api/views.py
Site search is resulting in public and community files from root level path.
* [WP-356](https://jira.tacc.utexas.edu/browse/WP-356)
Use the home directory for public and community data files as path to search.
Deployed the branch to [dev.cep](https://dev.cep.tacc.utexas.edu/)
* Used site search and checked the following:
* The paths listed in the public and community data folders are accurate. They are correctly based on config: corral/tacc/aci/CEP/public and corral/tacc/aci/CEP/community
* The search results from site-search match the results from data files search.
Screenshots:
Site search shows 37 results for public and 6 results for community:
Public file search shows 37 results:
Community file search shows 6 results
NA
=> bug/WP-356: Use home dir to isolate the search.

server/portal/apps/workspace/api/views.py
The job search is returning jobs from other portal sharing same tenant.
The search query conditions for portal name and query strings is enforcing portal condition correctly.
* [WP-361](https://jira.tacc.utexas.edu/browse/WP-361)
Fix the query to force condition logic, add the missing parentheses  (portal_match) AND (name_match OR archiveSystemDir_match OR appid_match OR archiveSystemId_match)
* For future, instead of manually constructing the query, query building utils can be used to build the query and avoid issues like this 
1. Without this PR, check the issue exists
2. In the [code change](https://github.com/TACC/Core-Portal/pull/896/files#diff-7a99e667ee8895ba518b7185992351579fcaf7e6f75310030fc8ba5c51db62c6R201) the portal name to 'Frontera'.
3. With dev tools open, run a query like …
=> Bug/WP-361: Fix query string construction

server/portal/apps/projects/views.py
There are documents in the projects index which are old and do not have same schema as the search expects.
Some of those do not have id field.
* [WP-384](https://jira.tacc.utexas.edu/browse/WP-384)
* Handle scenario where id is missing.
* exec into portal: docker exec -it core_portal_django bash
* Add 2 projects to index which could cause problems.
* project with no "id" field
```
curl -H "Content-Type: application/json" -X POST http://core_portal_elasticsearch:9200/cep-dev-projects/_doc -d '
{"name": "CEP-foo","host": "cloud.data.tacc.utexas.edu","updated": "2023-11-11T00:00:00","owner": {"username": "foo","first_name": "foo","last_name": "foo","email": "foo@tacc.utexas.edu"},"title": "testfoo","description": "foo"}'
```
* project does not exist in tapis
```
curl -H "Content-Type: …
```
=> Bug/WP-384: workspace search: handle scenario where id is missing in results

client/src/components/DataFiles/DataFilesTable/DataFilesTable.jsx, client/src/components/DataFiles/DataFilesTable/DataFilesTable.test.js, client/src/components/PublicData/PublicData.jsx, client/src/components/PublicData/PublicData.test.js, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py
- fix show path
- fix public path
- prevent access outside public path, and show message
* [WP-390](https://jira.tacc.utexas.edu/browse/WP-390)
1. Log out of cep.test
2. Go to https://cep.test/public-data/
3. Confirm you are redirected to correct public data path set in `settings_default.py`
4. Go to a directory above the homeDir of public data, like https://cep.test/public-data/tapis/public/cloud.data/corral/tacc/
5. Confirm you get an unauthorized message
6. Click "View Path" and confirm it works as expected
=> bug/WP-390: Fix Public Data view

client/src/components/DataFiles/DataFilesDropdown/DataFilesDropdown.jsx, client/src/styles/components/dropdown-menu.css
The system name (root) in the dropdown menu is not truncated like the path folder names. This is causing a text overflow if the system name is a long string. See example below with Frontera system names/labels. Only an issue if the system name is over 20-char in length.
We can use the substring method, like I used for the path folder names below to handle this issue. 
* [WP-388](https://jira.tacc.utexas.edu/browse/WP-388)
- Added check if systemName was longer than 20 characters--used substring method to grab first 20 chars--otherwise render full systemName (or Shared Workspaces, if applicable)
1. Go to server > portal > settings > settings_default.py
2. Locate _PORTAL_DATAFILES_STORAGE_SYSTEMS
3. Change the name field for one of the objects to something like 'name': 'My Data (Frontera …
=> task/WP-388: fixed text overflow for longer system labels(systemName)

client/src/components/Allocations/tests/AllocationsCells.test.js, client/src/components/Allocations/tests/AllocationsTables.test.js, client/src/components/Workbench/AppRouter.jsx, client/src/components/Workbench/index.test.js
Fixes the bug where in certain cases after logging in the user would be redirected to the /api/profile/data path and see a screen with api data text. 
* [WP-287](https://jira.tacc.utexas.edu/browse/WP-287)
- Removed an extra GET_PROFILE_DATA action that was being dispatched in AppRouter.jsx. 
- Cleaned up tests for Allocations components  by removing unused variables
The profile data retrieved is added to the profile state variable. This state is only used in the ManageAccount components and [ManageAccount.jsx](https://github.com/TACC/Core-Portal/blob/main/client/src/components/ManageAccount/ManageAccount.jsx#L36) already has a `GET_PROFILE_DATA` action being dispatched. So the data is available in that component and removing the action from the AppRouter does not have an effect here. …
=> bug/WP-287 Fix Invalid Url Redirect

client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.jsx
On downloading files marked 'Other' via preview, trying to preview instead leads to download, but still opens & closes a browser tab before the download is fired. This PR prevents that new tab for this case.
* [WP-320](https://jira.tacc.utexas.edu/browse/WP-320)
- On 'Preview File' button when a file is unable to be displayed in the preview modal, now checks for file type 'Other' to determine if a new tab opens or not
1. On the workbench, go to Data Files > Shared Workspaces, and find the workspace titled 'Workspace for test files'
2. In that folder, click the name of the `.zip` file to open the File Preview modal
3. Once the modal loads with the message 'Unable to show preview.', click on the 'Preview File' button
4. Confirm that the .zip file downloads to your browser and no new tab on …
=> task/WP-320: No new tab when downloading files from My Data

server/portal/urls.py
The [django-impersonate](https://pypi.org/project/django-impersonate/) middleware was not functioning properly with the url structure we had in place for some reason.
1. Login in one tab with your user, and grant yourself superuser status
2. Login in an incognito tab with another test user
3. Go to https://cep.test/core/impersonate/2 and confirm impersonation works
=> Quick: fix impersonation url

client/src/components/DataFiles/DataFilesTable/DataFilesTable.jsx, server/portal/apps/workspace/api/views.py
Tapis has updated new files status codes to reflect more accurately responses from the files service. We will need to update our error handling accordingly:
[Files: Review http status codes for errors · Issue #102 · tapis-project/tapis-files](https://github.com/tapis-project/tapis-files/issues/102)
This PR is a quick fix to get the push keys modal working again. A follow up task will be made to improve overall error handling.
* [WP-402](https://tacc-main.atlassian.net/browse/WP-402)
1. Remove your user credential on Frontera via `client.systems.removeUserCredential(userName=$username, systemId='frontera')`
2. Go to https://cep.test/workbench/applications/paraview?appVersion=5.10.0 and confirm you are prompted to push keys
3. Go to https://cep.test/workbench/data/tapis/private/frontera/ …
=> Hotfix WP/402: handle 401 unauthorized Tapis error for pushing keys

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/Applications/AppForm/fixtures/AppForm.app.fixture.js
Use `archiveSystemId` value set in app definition if provided.
* [WP-408](https://tacc-main.atlassian.net/browse/WP-408)
* [WP-103](https://tacc-main.atlassian.net/browse/WP-103)
1. Go to https://cep.test/workbench/applications/opensees-mp-ls6
2. Confirm the "Archive System" field shows `cloud.data`, which is the `archiveSystemId` of this app, instead of `frontera`, which is the default system locally.
=> bug/WP-408: use archiveSystemId set in app definition as default

client/src/components/Applications/AppBrowser/AppBrowser.jsx, server/portal/apps/workspace/api/views.py
In the /workbench/applications, applications inside each category appeared randomly in order that tapis retrieved it. 
* [WP-358](https://tacc-main.atlassian.net/browse/WP-358)
* used python `sorted` method to sort apps based on app label in backend
1. Go to https://cep.test/workbench/applications and confirm the apps inside categories appear alphabetically
=> Task/WP-358: sort apps inside category before rendering

client/src/components/DataFiles/DataFilesListing/DataFilesListing.jsx, client/src/components/PublicData/PublicData.jsx
Public Data listing: Need a mechanism to navigate folders similar to data files listing
* [WP-367](https://tacc-main.atlassian.net/browse/WP-367)
- Changed component in PublicData from DataFilesBreadcrumbs to CombinedBreadcrumbs (includes dropdown menu)
- Added extra "workbench-wrapper" class to handle styling for dropdown menu in Public Data CMS
- There was also a small bug related to WP-304 where errors were thrown related to system name and the search bar, when in the root directory of Public Data CMS. 
- Fixed the above bug in this PR too. Added new code to DataFilesListing to check if the current path is the root. This now correctly handles the placeholder text in the Search bar when in root. 
1. Go to cep.test
2. Go directly to https://cep.test/public-data/
3. Test new dropdown menu …
=> task/WP-367: Adding Public Data CMS Nav and fixing search bar root bug

server/portal/urls.py, server/portal/views/unit_test.py, server/portal/views/views.py
To have a monitoring website, a non-authenticated endpoint is needed. This health-check endpoint provides a mechanism to share status. 
* [WI-15](https://tacc-main.atlassian.net/browse/WI-15)
/core/health-check endpoint will provide ping status to validate nginx, uwsgi, django worker is up or not.
A 200 status shows the portal is up. Anything else shows the portal is down.
In future this can be expanded to provide additional status (DB, ES, etc). 
1. curl https://cep.test/core/health-check
{"status": "healthy"}
2. Unit test to ensure this endpoint is not removed accidently.
N/A
=> WI-15: Add health check for site status

.github/pull_request_template.md, client/src/components/Applications/AppForm/AppForm.jsx, client/src/redux/sagas/apps.sagas.js
After job submission, the success message will hang at the top of the screen even if you navigate away and back to the app (without refreshing the browser).
Direction
To replicate:
1. submit a job (i.e. [paraview](https://cep.tacc.utexas.edu/workbench/applications/paraview?appVersion=5.10.0))
2. Click the "Allocations" button on the left hand sidebar
3. Go back to the "Applications" view on the left hand sidebar
4. Click Visualization -> Paraview
* [WP-59](https://tacc-main.atlassian.net/browse/WP-59)
- added a useEffect and useHistory to listen for navigation changes and reset the jobSubmission properties
- removed logic to not reload an app if it's already `currentApp` exists https://github.com/TACC/Core-Portal/blob/6bfc782bef08164ecfb03cefa0036f345032de7a/client/src/redux/sagas/apps.sag …
=> useEffect to handle rendered message behvaior

client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.jsx, client/src/components/DataFiles/DataFilesModals/tests/DataFilesPreviewModal.test.js
When file cannot be previewed, the button message should say "Download File"
* [WP-398](https://tacc-main.atlassian.net/browse/WP-398)
- Changed 'Preview File' to say 'Download File'
- Updated unit tests to reflect that change
1. On the workbench, go to Data Files > Shared Workspaces, and find the workspace titled 'Workspace for test files'
2. In that folder, click the name of the .zip file to open the File Preview modal
3. Make sure the button reads "Download File"
=> WP-398: 'Preview File' button should say 'Download File'

server/portal/templates/includes/header.html
As of https://github.com/TACC/Core-CMS/pull/604, the Core-CMS can use a search other than Portal.
None
- **deleted** a comment in a template
Skipped
N/A
CMS uses Google search on [ECEP](https://ecepalliance.org/) and [TACC](https://tacc.utexas.edu/) sites.
=> docs(server): remove outdated comment

client/src/redux/sagas/datafiles.sagas.js, client/src/redux/sagas/datafiles.sagas.test.js
Tapis had inconsistency in url encoding requirement. For job submission, sourceUrl was required to be encoded. But, when transfering files the sourceUrl should not be needed. This led to failures in jobs.
Tapis now fixed the bug to not require any encoding in url values in json content. Job submission is json content.
See bug details: https://github.com/tapis-project/tapis-jobs/issues/66
This bug is now in develop branch
* [WP-305](https://tacc-main.atlassian.net/browse/WP-305)
* Remove encodeURI in client side javascript during compress and extract.
* No other logic in server or client is using encodeURI in 3.x.
1. Test extract with and without spaces in zip file name
2. Test compress with and without spaces in file names. 
3. Update test automation
=> Bug/WP-305: Do not encode sourceUrl field for tapis jobs

server/portal/apps/auth/views.py, server/portal/apps/users/unit_test.py, server/portal/apps/users/utils.py, server/portal/apps/users/views.py, server/portal/settings/settings.py, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py, server/portal/settings/unit_test_settings.py
Staff and Superuser can be set in through the `_PORTAL_ELEVATED_ROLES` object in `settings_default.py` or `settings_custom.py` for per-portal configuration. Either the TAS group or TACC id can be used. 
```
_PORTAL_ELEVATED_ROLES = {
"staff": {
"groups": [],
"usernames": []
},
"superuser": {
"groups": [],
"usernames": []
}
}
```
* [WP-409](https://tacc-main.atlassian.net/browse/WP-409)
- added a new dict object `_PORTAL_ELEVATED_ROLES` object in `settings_default.py` and imported it to `settings.py` 
- updated 'get' method to loop through the PORTAL_ELEVATED_ROLES to check if user's username or TAS groups is in the dict object. Skips if role is already applied to the user.
- updated unit tests to reflect new dict object in `settings.py`
1. Remove staff and superuser status, and add your …
=> WP-409: Set members to superuser via TAS

server/portal/apps/users/tas_to_tacc_resources.json, server/portal/settings/settings.py, server/portal/settings/settings_default.py
Stampede3 is part of TACC-ACI allocation and is usable for testing.
* tas_to_tacc_resources.json is matched against available allocations in tas. Need to keep this json updated.
* system monitor list adjustment
1. Allocation shows Stampede3
2. System Monitor: TAS is still not updated for Stampede3, so that shows as maintenance. https://tap.tacc.utexas.edu/status does not show stampede3 yet.
=> Add Stampede3 to allocation list and system monitor list

server/portal/apps/tickets/rtUtil.py, server/portal/apps/tickets/unit_test.py
In cases, where email in RT Ticketing system is different case vs email address stored in Core Portal user list, a bug shows up where ticket list shows up, but viewing details of the ticket (get_ticket call) fails on access control in rtUtil.djangoRT module.
When searching for tickets, rtUtil.djangoRT uses Requestors__exact search. For this search, RT uses case insensitive. So, the user is able to see all the tickets.When opening a specific ticket, portal does case sensitive check for access to the ticket in requestors and cc fields.
RT search depends on the DB settings for case sensitivity. Search api `__exact` converts to `=` in sql.
* [WP-547](https://tacc-main.atlassian.net/browse/WP-547)
* update djangoRT.hasAccess to do case insensitive look up for user.
* Checked that no other code …
=> WP-547: case insensitive email in GET tickets

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppFormUtils.js
Job submission for FORK type job is not failing.
Concepts like queues, allocation, node and core count do not apply to FORK job type. 
Errors seen in dev console.
```
index.ec69ba6e.js:32 TypeError: Cannot read properties of undefined (reading 'maxMinutes')
at getQueueMaxMinutes (index.e90d3a4d.js:98:81851)
at children (index.e90d3a4d.js:98:141791)
at Formik (index.e90d3a4d.js:43:61737)
at jd (index.ec69ba6e.js:30:53016)
at H_ (index.ec69ba6e.js:34:8745)
at b_ (index.ec69ba6e.js:34:950)
at nL (index.ec69ba6e.js:34:878)
at jo (index.ec69ba6e.js:34:732)
at Qc (index.ec69ba6e.js:32:10899)
at index.ec69ba6e.js:30:38809
```
* [WP-946](https://tacc-main.atlassian.net/browse/WP-946)
* Adjust validation for : Node Count, Core Count, Max Minutes, Batch Logical Queue limits and allocation.
1. Open …
=> Handle validation for FORK job type

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppForm.test.js
For parameterSet, tapis only supports string arguments. See openapi spec [here](https://github.com/tapis-project/tapipy/blob/main/tapipy/resources/openapi_v3-apps.yml#L1686).
Hello World app has a note to indicate that Sleep Time should be rendered as number in App Form. When submitting the job, the value in parameterSet below has Sleep Time as number, it should be json string.
{
"appArgs": [
{
"name": "Greeting",
"arg": "hello"
},
{
"name": "Target",
"arg": "world"
},
{
"name": "Sleep Time",
**"arg": 31**
}
],
}
* [WP-551](https://tacc-main.atlassian.net/browse/WP-551)
If the arg value is integer, change that to string.
1. Go to hello world app, change the sleep time to something else and submit job. Job should work.
2. To regression test, change other parameters, change MaxMinutes and …
=> WP-551: use only strings for app arguments

Makefile, server/conf/docker/docker-compose-dev.all.debug.yml, server/portal/settings/settings.py, server/portal/settings/settings_default.py, server/portal/settings/unit_test_settings.py, server/portal/urls.py, server/portal/views/views.py
This PR to provides docs behind a login.
Following are needed to accomplish that:
* Adjustment to core portal to allow support for login based docs
* A compose which can pull docker image from private hub.
Steps to apply for actual site:
1. In configs, adjust docker compose to add docs sections for internal docs. This run mkdocs build.
2. Add mount path from mkdocs container to core portal container
3. Adjust settings to set the doc root.
4. Adjust cms menu to add new menu item to the docs link.
[WP-594](https://tacc-main.atlassian.net/browse/WP-594)
* Add url mapping to map internal-docs to view. 
* Add method to serve the content
* Settings provide the base path to the docs.
1. Setup core portal - run make build, make start, npm run dev. The default compose yml has frontera docs
2. Go …
=> task/wp-594: Setup internal docs with login access

server/portal/apps/search/tasks.py
Cron based indexer is using `/` as the path to walk the files.
It should use the system home dir.
* [WP-684](https://tacc-main.atlassian.net/browse/WP-684)
* Get the homeDir from system and use it.
1. Add this to settings_local.py
COMMUNITY_INDEX_SCHEDULE = {'hour': '*', 'minute': 15}
2. Check the logs
docker logs core_portal_workers
```
[DJANGO] INFO 2024-08-29 19:20:00,011 UTC tasks portal.apps.search.tasks.index_community_data:54: INDEXING Community Data SYSTEM with file path /corral/tacc/aci/CEP/community
[DJANGO] INFO 2024-08-29 19:20:00,016 UTC tasks portal.apps.search.tasks.index_community_data:54: INDEXING Public Data SYSTEM with file path /corral/tacc/aci/CEP/public
```
Note: there are errors related wma_prtl SSH access, will resolve that separately and a PR is not needed for …
=> Cron indexer should use home dir as root instead of '/'

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/Applications/AppForm/AppFormUtils.js
* [ValidateOnMount](https://github.com/jaredpalmer/formik/blob/main/packages/formik/src/Formik.tsx#L432) setting in Formik always uses initialValues.
* Everytime the component re-renders, validateOnMount triggers using initialValues. This is happening in AppForm immediately after value change. After value changes in the form, there are two sets of validators triggers - one is for validateOnMount and another for validateOnChange.
* If the initialValue of allocation is empty (portalAlloc is empty as an example), the validateOnMount causes error on empty allocation. 
* Enable validateOnMount for first render, which is what is intended. Afterwards on change handlers will trigger validation. setValue also triggers validation automatically.
Do not show allocations without execution hosts.
* …
=> Bug/WP-677: Dynamic exec system bug fixes - validation and allocation list

server/portal/apps/projects/views_unit_test.py, server/portal/apps/projects/workspace_operations/shared_workspace_operations.py
Handle key name change from PR https://github.com/TACC/WMA-Tapis-Templates/pull/55
[WP-371](https://tacc-main.atlassian.net/browse/WP-371)
SetFacl app PR: https://github.com/TACC/WMA-Tapis-Templates/pull/55
1. Rename key from username to usernames to match the app update.
1. Test workspace - add users.
=> WP-371: Additional fix to update key to usernames

client/src/redux/sagas/systems.sagas.test.js
This is a feature written to test `systems.sagas.js`, thus ensuring that the `pushSystemKeys()` function works as intended.
* [WP-76](https://tacc-main.atlassian.net/browse/WP-76)
I added the `systems.sagas.test.js` file and wrote a test for the `pushSystemKeys()` function.
1. In VSCode, navigate to Core-Portal/client/src/redux/sagas/systems.sagas.test.js.
2. In the Terminal, navigate to Core-Portal/client/src/redux/sagas and run this command: `npx vitest run systems.sagas.test.js`.
3. The test should pass.
Further refining of this test may be needed.
=> Task/WP-76: Add unit tests for /api/accounts/systems/ route

client/src/components/DataFiles/DataFilesListing/DataFilesListing.jsx
On CEP Shared Workspaces → any workspace title still says "Search Root"
* [WP-420](https://tacc-main.atlassian.net/browse/WP-420)
- Changed the logic that shows "Search Root" to the current working directory folder name instead of Root. The only time that this would occur is on the first project directory navigation. The rest of the navigations into additional sub folders seems correct
=> Bug/WP-420: Search placeholder does not update on navigating to directories

client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/ReviewAuthors.jsx
Add ACM Ref, APA, BibTex, MLA, and IEEE citations to the "Review Authors and Citation" page.
* [WP-574](https://tacc-main.atlassian.net/browse/WP-574)
- Created a component for each citation type. Formatted each citation type to match: https://www.digitalrocksportal.org/projects/317/cite/
- Created a component to display the citations
- Used css to put a box around each citation
1. Click Request Publication
2. Continue to Review Authors and Citation
3. Verify the Citations match the examples from the link above. 
DOI is missing
Date Published is missing (right now, it is using Date Created)
=> Refactor ReviewAuthors component to use separate citation components

client/src/components/DataFiles/DataFilesModals/DataFilesModals.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesProjectTreeModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesProjectTreeModal.module.scss, client/src/components/_custom/drp/DataFilesProjectFileListingAddon/DataFilesProjectFileListingAddon.jsx, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/ProjectTreeView.jsx, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/ReviewProjectStructure.jsx, client/src/components/_custom/drp/utils/hooks/useDrpDatasetModals.js, client/tsconfig.json, client/vite.config.ts
Add a toolbar button and modal to display the tree for DRP projects
The project tree in the publication pipeline has been refactored to a reusable component. A `readOnly` prop controls whether the editing UI is rendered alongside each tree node.
* [WC-93](https://tacc-main.atlassian.net/browse/WC-93)
1. Open a DRP project in your local environment.
2. Click "View Project Tree" in the menu and confirm that the tree is rendered correctly.
(`readOnly=false`)
(`readOnly=true`)
=> Task/WC-93:  Add toolbar button and modal to display the tree for DRP projects

client/src/redux/sagas/datafiles.sagas.js
Close the file upload modal after all uploads have completed.
* [WC-130](https://tacc-main.atlassian.net/browse/WC-130)
1. Upload a file and check that the modal closes after the upload succeeds.
=> Close upload modal after successful upload

server/portal/apps/projects/workspace_operations/project_publish_operations.py, server/portal/apps/publications/views.py, server/portal/settings/settings.py, server/portal/settings/settings_custom.example.py
Adds Django email config and tasks to email authors when their publication request is accepted/rejected.
* [WC-155](https://tacc-main.atlassian.net/browse/WC-155)
1. Add the `_DEFAULT_FROM_EMAIL` setting to your local settings_custom file.
2. [PPRD ONLY] Accept/reject a publication you are an author on and check that a confirmation email is sent. 
There are security issues around using relay.tacc from a dev machine, so SMTP_HOST shouldn't be set to relay.tacc there.
=> Task/WC-155: Email project authors when publication request is accepted/rejected.

client/src/hooks/datafiles/mutations/useCopy.ts
Updating hooks to use React Query mutations with Typescript. This mutation covers copying a file.
* [WP-728](https://tacc-main.atlassian.net/browse/WP-728)
- useCopy.js to useCopy.ts
- Identify types of payloads
- Wraps dispatch actions inside a mutation
- Navigate to the folder where the file is that you would like to copy
- Select the checkbox of the folder
- Click the copy button
- Select the destination directory to copy to
=> Task/WP-728: Mutation hook: Copy file

client/src/components/Jobs/JobsStatus/JobsStatus.jsx
Fix typo in jsx
[WP-765](https://tacc-main.atlassian.net/browse/WP-765)
1. Go to https://cep.test/workbench/history/jobs and check the status button
**Before**
**After**
=> WP-765: Fix job status button to show background

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/_common/Form/FormField.jsx
* After update to react v18, this infinite loop on dependency checker is happening:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, 
but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```
Also, fixes this warning:
A <Button> that is not `type="link"` and has no `size` is automatically assigned `size="auto"`.
[WP-778](https://tacc-main.atlassian.net/browse/WP-778)
1. Only set state if something changed.
1. Go to App Form of any app, use the drop down values - example, change the value of queue from debug to development and back. Change to large and observe the effects on the fields.
2. Also try to use "reset fields to default" and then use the select drop down.
=> WP-778: Fix infinite loop for state update in useEffect

client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.module.scss, client/src/styles/components/dropdown-menu.css
- Fix display of border on data files "Add" dropdown
- Fix button group in Manage Project modal
[WP-783](https://tacc-main.atlassian.net/browse/WP-783)
Before:
After:
Before:
After:
=> Quick: CSS regression fixes- testing session 2024-11-26

client/src/redux/sagas/projects.sagas.js
Show a toast notification when changing the owner of a project.
* [WC-148](https://tacc-main.atlassian.net/browse/WC-148)
1. Change the owner of a project you administer. You should see a toast notification with the name of the new owner.
=> Task/WC-148: Toast notification when changing project owner

client/src/components/DataFiles/DataFilesModals/DataFilesPublicationRequestModal.jsx, client/src/components/_common/DescriptionList/DescriptionList.jsx
- Updates the `DescriptionList` component to permit sorting by adding a `_order` key. The key is filtered out before rendering the list, so it won't show up in the UI.
- Sorts publication requests in descending date order before passing them to `DescriptionList`.
* [WC-166](https://tacc-main.atlassian.net/browse/WC-166)
1. Go to a project with >1 publication requests and check that the requests are sorted in order of descending date.
=> Task/WC-166  Sort publication requests by descending date

client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.jsx, client/src/components/_common/TextCopyField/TextCopyField.jsx
With update to bootstrap, started see these issues:
* Copy button in TextCopyField modal is aligned to the left instead of right
* Close button in Allocation Modal does not have padding.
[WP-781](https://tacc-main.atlassian.net/browse/WP-781)
* Use appropriate bootstrap classes to fix this.
1. Go to Data Files and see View Full Path modal
2. Go to Allocation and view Allocation Modal for an allocation
**View Full Path**
Before
After 
**Allocation Modal**
Before: 
After:
=> WP-781: FIx UI formatting issues

client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.jsx, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.test.jsx, client/src/hooks/datafiles/mutations/useCompress.ts, client/src/hooks/datafiles/mutations/useExtract.ts
* In site search which shows community and public data files, the drill through on the file/folder is leading to error due to empty allocation list.
* Compress and Extract mutation is not handling case where allocation is not fetched yet.
[WP-835](https://tacc-main.atlassian.net/browse/WP-835)
* Handle case where allocation is not fetched or available.
* switch to useQuery for getting extractApp - otherwise every render is requesting the app.
1. Site search with keyword to get file listed. Drill through the file and it should the data files listing
2. Extract a zipped file in data files
3. Compress a file/folder in data files.
=> WP-835: Click through file location in site search results is failing

client/vite.config.ts
Addresses an issue where Vite assets weren't loading to do a CORS issue. The `origin` setting has worked for this in the past, but might not be respected as of recent browser/Node updates.
=> Quick: Add explicit CORS config to Vite

client/src/hooks/datafiles/mutations/useUpload.test.ts, client/src/hooks/datafiles/mutations/useUpload.ts
Upload is sending `//` to server and failing in url mapping.
* [WP-870](https://tacc-main.atlassian.net/browse/WP-870)
1. url.replace does not modify in place, fix it.
1. Added unit tests
2. go to [dev.apcd and try upload.](https://dev.apcd.tacc.utexas.edu/workbench/data-submission/) and try upload
=> WP-870: Fix broken file uploads and APCD file submissions

client/src/components/DataFiles/CombinedBreadcrumbs/CombinedBreadcrumbs.jsx, client/src/components/DataFiles/DataFilesDropdown/DataFilesDropdown.jsx, client/src/components/DataFiles/DataFilesListing/DataFilesListing.jsx, client/src/components/DataFiles/DataFilesListing/DataFilesListingCells.jsx, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.jsx, client/src/components/DataFiles/DataFilesPublicationsList/DataFilesPublicationsList.jsx, client/src/components/Publications/PublicationDetailPublicView.jsx, client/src/components/Publications/PublicationsPublicView.jsx, client/src/components/Workbench/AppRouter.jsx, client/src/components/_custom/drp/DataFilesProjectFileListingAddon/DataFilesProjectFileListingAddon.jsx, client/src/components/_custom/drp/DataFilesProjectFileListingMetadataTitleAddon/DataFilesProjectFileListingMetadataTitleAddon.jsx, server/conf/nginx/nginx.conf, server/portal/apps/datafiles/views.py, server/portal/apps/projects/views.py, server/portal/urls.py
Serve published projects on a world-readable page at `/publications`
* [WC-186](https://tacc-main.atlassian.net/browse/WC-186)
- Add world-readable `/publications` page.
- Update projects UI to work without auth for published projects,
- Update projects/publications backend to remove auth requirement for viewing published projects.
1. Visit https://cep.test/publications/ and click through publications and file listings within those publications
2. Repeat in an unauthenticated session
=> task/WC-186: Serve published projects on a world-readable page

client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.jsx, client/src/components/Publications/PublicationDetailPublicView.jsx
Fix a bug where clicking into a directory in a project/publication would link out to the `/published` view.
=> Quick: Fix workbench publications linking to public area

client/src/hooks/datafiles/mutations/useUpload.ts, client/src/utils/apiClient.ts
Defaults to 1min now for timeout, and increases upload timeouts to 5min
1. Upload a largeish file and confirm it succeeds
2. In `client/src/hooks/datafiles/mutations/useUpload.ts`, change the default timeout to `1000`, 1 second. Upload the same file and watch it fail.
=> Hotfix: increase axios timeout

server/portal/templates/base.html, server/portal/templates/includes/nav_portal.raw.html
Fix position of menu of portal nav on Portal. (It is positioned as expected on CMS.)
- [WP-895](https://tacc-main.atlassian.net/browse/WP-895)
- expected by https://github.com/TACC/Core-CMS/pull/913
- continues incomplete Bootstrap update from #1030
- **updated** Bootstrap and Popper JS
1. Run Core-Portal with this Core-CMS.
2. Open CMS page.
3. Verify portal nav dropdown menu location is underneath its toggle.
https://github.com/user-attachments/assets/c4e8bbd1-72f9-4996-bcc3-5b49548e2278
> [!IMPORTANT]
> Other dropdown menu positions work because they rely on Reactstrap for JavaScript.[^1]
> [!TIP]
> The bug of orange underline appearing beneath header is fixed separately in #1068.
[^1]: Wait, so… the HTML-driven load of Bootstrap JavaScript is only for the portal nav dropdown? Maybe. …
=> fix: WP-895 portal nav position wrong on portal

client/src/components/DataFiles/DataFilesModals/DataFilesAddProjectModal.jsx, client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.jsx
* [Wc-191](https://tacc-main.atlassian.net/browse/Wc-191)
Add the following placeholder text to the identified input field: 
PI question about the Add Dataset view: We are not clear what is the meaning of the “Role”, especially since here we cannot add anyone else.
1. click "+Add" --> choose "Dataset"
2. Check modal for expected changes
changing "members" to "authors" will reflect everywhere DataFilesProjectMembers.jsx is used.
=> Requested Changes [post-workshop] for the "Add Dataset" View

server/portal/templates/includes/nav_portal.raw.html
Workbench user drop down menu is cut off on the right.
[WP-839](https://tacc-main.atlassian.net/browse/WP-839)
User drop-down menu styling fixed
1. Log in as Admin user, verify User drop-down menu is not cut off
=> Fix: Workbench drop down menu is cut off on the right.

client/src/components/DataFiles/DataFilesModals/DataFilesAddProjectModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesProjectEditDescription.module.scss, client/src/components/DataFiles/DataFilesModals/DataFilesProjectEditDescriptionModal.jsx, client/src/components/_common/Form/DynamicForm/DynamicForm.jsx, client/src/components/_common/Form/DynamicForm/DynamicForm.module.scss, client/src/components/_common/Form/FormField.scss, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublish.jsx, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/DataFilesProjectPublishWizard.module.scss, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/ProjectDescription.jsx, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/ReviewProjectStructure.jsx, client/src/components/_custom/drp/DataFilesProjectPublish/DataFilesProjectPublishWizardSteps/SubmitPublicationRequest.jsx
- Adds validation for project metadata when publishing
- Adds validation for file/folder structure and ensures there are no empty file less folders 
- Reverts required validation for project description
* [WC-231](https://tacc-main.atlassian.net/browse/WC-231)
* [WC-215](https://tacc-main.atlassian.net/browse/WC-215)
1. Try to  publish a project without title/description/cover image and ensure it doesn't let you progress 
2. Try to create some empty entities (empty digital data, empty analysis data)  and ensure it doesn't let you progress
=> task/WC - 231 & 215 - Publication Metadata Validation

client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.jsx, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.jsx, client/src/components/Publications/PublicationDetailPublicView.jsx
Adds the copy/download toolbar to the public view of DRP pubs, and implements the download hook for files too large to preview.
* [WC-230](https://tacc-main.atlassian.net/browse/WC-230)
In the public view (https://cep.test/publications):
1. Try to preview a large file and make sure that the download button in the preview window starts an actual download
2. Inside a publication, use the download button (logged in and logged out) and the copy button (logged in). Copy might take a minute to process because it's done through the async Tapis transfer endpoint.
=> Task/WC-230 Support download/copy for published DRP files

server/portal/settings/settings.py
Fixes for two items found in DRP PPRD BURP Security Scan. 
* No JIRA ticket at the moment.
- Sets the following values to `True`:
- CSRF_COOKIE_SECURE
- CSRF_COOKIE_HTTPONLY
1. Look at codebase and see configs in `settings.py`.
1. No visible test.
1. Will require a fresh BURP Scan of the PPRD host to verify these changes resolved issue.
=> Fixes for the vulnerabilities identified in the digital rocks portal preprod host security scan.

.github/workflows/main.yml, server/conf/docker/Dockerfile, server/conf/docker/docker-compose-dev.all.debug.yml, server/conf/docker/docker-compose.yml, server/conf/nginx/nginx.conf, server/poetry.lock, server/pyproject.toml
- fix http2 nginx directive
- pin nginx version to `stable`
- bump redis to `latest`
- upgrade python poetry to v2
- upgrade node to v22 LTS
Resolves:
```
2025/03/26 16:51:08 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/nginx.conf:51
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/nginx.conf:51
```
1. `make stop`, then `make start`
2. Confirm you can navigate the site as normal
=> Quick: fix http2 directive; upgrade poetry; upgrade node

client/src/components/DataFiles/DataFilesModals/DataFilesFormModal.jsx, client/src/components/_custom/drp/DataFilesProjectEditDescriptionModalAddon/DataFilesProjectEditDescriptionModalAddon.jsx, client/src/components/_custom/drp/DataFilesProjectFileListingMetadataAddon/DataFilesProjectFileListingMetadataAddon.jsx
- explain in validation that URLs must start with https://
- render related datasets before software in the modal to keep things consistent.
* [WC-239](https://tacc-main.atlassian.net/browse/WC-239)
=> Task/WC-239: Dataset form fixes

client/src/components/Applications/AppForm/AppForm.jsx, client/src/components/Applications/AppForm/AppForm.test.jsx, client/src/components/Applications/AppForm/AppFormSchema.js, client/src/components/Applications/AppForm/fixtures/AppForm.app.fixture.js, client/src/components/DataFiles/fixtures/DataFiles.systems.fixture.js, client/src/components/DataFiles/tests/DataFiles.test.jsx, client/src/redux/reducers/datafiles.reducers.js, server/portal/apps/datafiles/views.py, server/portal/apps/datafiles/views_unit_test.py
- By default, use the portal's `PORTAL_DATAFILES_DEFAULT_STORAGE_SYSTEM` setting value to set the `archiveSystemId` and `archiveSystemDir`
- Add's support for the `notes.label` field of app parameter fields.
* [WA-392](https://tacc-main.atlassian.net/browse/WA-392)
1. Go to https://cep.test/workbench/applications/opensees-sp-v35?appVersion=0.0.1 and confirm the default archive settings are those of the portal
2. Go to https://cep.test/workbench/applications/jupyter-hpc-native?appVersion=frontera and confirm the environment label is rendering
=> task/WA-392: use portal archive sys and path defaults; use parameterSet notes.label

server/conf/docker/docker-compose-dev.all.debug.yml, server/portal/apps/workspace/api/views.py
- Fixes an issue with apps not appearing in the apps listing due to the default limit being `100`
- Fixes an issue with the app matching logic to display apps in the portal
* [WA-442](https://tacc-main.atlassian.net/browse/WA-442)
1. Add a new app with app id `jupyter-hpc-native` to the apps tray, and confirm it appears in your apps workbench listing. On `main` branch, it will not appear.
=> bug/WA-442: Fix apps listing

server/portal/apps/projects/workspace_operations/datacite_operations.py
Add DataCite `relatedIdentifier` entries for the following metadata:
- Related Datasets
- Related Software
- Related Publications
* [WC-202](https://tacc-main.atlassian.net/browse/WC-202)
=> Task/WC-202: Add related works/software to DRP datacite JSON

server/conf/docker/docker-compose-dev.all.debug.yml
Pin CMS to latest.
_I will start to tag `latest` (i.e. build `main`) when I release new CMS versions._
<details>
I learned that if I build `main`, then image is tagged `latest`  **and** as the latest version. So, I will build `main` knowing that it updates Core-Portal local dev.
</details>
1. Create **fresh** Portal with **fresh** CMS.
2. Verify no need to #1096.
> [!NOTE]
> If login to CMS gives "CSRF verification failed.", blame [WP-897](https://tacc-main.atlassian.net/browse/WP-897) not this PR.
Skipped.
=> feat(cms): update from pinned tag to latest tag

client/src/components/DataFiles/DataFilesModals/DataFilesDownloadMessageModal.jsx, client/src/components/DataFiles/DataFilesModals/tests/DataFilesDownloadMessageModal.fixture.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesDownloadMessageModal.test.jsx
Fix unit tests.
Dropped checked for other modals (like `Large Download Modal`) as only rendering `DataFilesDownloadMessageModal`
* [WP-949](https://tacc-main.atlassian.net/browse/WP-949)
None
=> hotfix/WP-949: fix unit tests

server/portal/apps/workspace/api/views.py
Fixes an issue where the 'My Apps' listing was showing every version of every app in the workspace.
* [WA-451](https://tacc-main.atlassian.net/browse/WA-451)
1. Compare the "My Apps" listing between this branch and main, and confirm this branch has no duplicate entries (showing each version of each app shared with you or created by you, and only shows the latest)
=> bug/WA-451: Prevent 'my apps' listing from showing every version of each app

server/portal/apps/datafiles/views.py, server/portal/apps/workspace/api/utils.py, server/portal/utils/decorators.py
Retries the original request after successful credential creation, and add a `retry` decorator to handle credential creation propagation time to tapis.
1. (on staging tenant) Delete your vista credential
2. List https://cep.test/workbench/data/tapis/private/vista and confirm listing succeeds
=> Hotfix: fix tms handling to retry request, and add retry decorator

server/portal/apps/datafiles/views.py, server/portal/apps/projects/views.py, server/portal/apps/projects/views_unit_test.py, server/portal/settings/settings.py
Hash session IDs before they are written to our metrics logger.
* [WI-185](https://tacc-main.atlassian.net/browse/WI-185)
- Add a log filter that hashes the session key before writing to Splunk.
- Hash session keys passed as tapis-tracking-id headers.
=> task/WI-185: obfuscate Django session IDs in logs

server/portal/apps/auth/middleware.py
Ignore tapis oauth url paths for Tapis Token Refresh Middleware
1. Confirm you do not see "Tapis OAuth token expired for user {request.user.username}. Refreshing token" if your token is expired and you go to /login
=> Quick: Ignore oauth urls in token refresh middleware

README.md
Remind user they can login to CMS with TACC account. Let user know adding CMS page is optional.
~~If dev wants to create CMS pages, instruct them how to login to CMS. Lead them to do so with TACC account, but permit manual account.~~
<details><summary>Inspiration</summary>
Docs need not encourage dev to _manually_ create a CMS superuser, because they might report [CSRF token problem upon trying to login with it](https://tacc-main.atlassian.net/issues/WP-897). (I had reported that, yet I knew the CMS well.) Do encourage login via TACC user, because (A) that is more akin to login on remote servers, and (B) it is workaround for login aspect of [WP-897](https://tacc-main.atlassian.net/browse/WP-897) bug.
</details>
* [WP-897](https://tacc-main.atlassian.net/issues/WP-897)
* **updates** …
=> docs: clarify cms access and page mgmt

client/src/hooks/datafiles/mutations/toolbarAppUtils.ts, client/src/utils/getCompressParams.ts, client/src/utils/getExtractParams.ts
VMs are not allocated resources in TAS projects, so need to not check these execution systems against TAS allocations to allow jobs to run.
* [WP-966](https://tacc-main.atlassian.net/browse/WP-966)
- Check truthy of `canRunBatch` attribute on exec system object from compress/extract app, return 'VM' if false
- Use above return value to avoid passing `schedulerOptions` back to tapis (unneeded for VM apps)
1. Update your `settings_default.py` `_WORKBENCH_SETTINGS` to point to `compress-express` and `extract-express` (both v0.0.1)
2. In Data Files + Shared Workspaces, confirm that you can submit compress and extract jobs from the toolbar and that they run and complete successfully
thank you Sal for the fix idea!
Adding testing coverage for all of this new compress + extract code coming in …
=> hotfix: Bypass allocations check for toolbar apps running on VM
