TACC/Core-Portal

.github/workflows/main.yml
Run GitHub actions on all Pull Requests.
[Documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags)
=> Run actions on all PR branches

client/src/redux/sagas/allocations.sagas.js, client/src/redux/sagas/tests/allocations.sagas.test.js
Test coverage for `allocations.sagas.js`
* [FP-570](https://jira.tacc.utexas.edu/browse/FP-570)
From the `client` directory, run `jest src/redux/sagas/tests/allocations.sagas.test.js`
=> Task/FP-570: Allocations Sagas Tests

client/src/components/History/HistoryBadge/HistoryBadge.module.scss, client/src/components/_common/Pill/Pill.js, client/src/components/_common/Pill/Pill.module.scss
Tweaks to CSS on new `Pill` component.
* [FP-722](https://jira.tacc.utexas.edu/browse/FP-722)
- Update CSS to match design more accurately.
- Add new comments in CSS.
- (for consistency) Use `.root`, not `.pill` as class for component.
1. Add DEBUG = True to settings.py
2. Look at UIPatterns in dashboard (Pill demos have been added to bottom)
=> Task/fp 772 pill component  tweak

client/src/components/UIPatterns/UIPatterns.js, client/src/components/UIPatterns/UIPatternsPill/UIPatternsPill.js, client/src/components/UIPatterns/UIPatternsPill/index.js, client/src/components/_common/Message/Message.module.scss, client/src/components/_common/Pill/Pill.js, client/src/components/_common/Pill/Pill.module.scss, client/src/components/_common/Pill/Pill.test.js, client/src/components/_common/Pill/index.js, client/src/components/_common/index.js, client/src/styles/settings/color.css
A pill component, as specified in [confluence](https://confluence.tacc.utexas.edu/pages/viewpage.action?spaceKey=UP&title=UI+-+Components+-+Pill)
* [FP-772](https://jira.tacc.utexas.edu/browse/FP-772)
- Added Pill component in _common
- Added UIPatterns demo of Pill
- Changed global color variable --global-color-warning--normal to #C7CE1D
- Added --global-color-warning--alt #9D85EF
- Change Message component color from --global-color-warning --global-color-warning--alt
1. Add DEBUG = True to settings.py
2. Look at UIPatterns in dashboard (Pill demos have been added to bottom)
=> task/FP-772 UI pill component

client/src/components/Tickets/TicketModal.js, client/src/components/_common/Form/FileInputDropZoneFormField.js
Added the date into the rest of the span containing the ticket response header class
* [FP-629](https://jira.tacc.utexas.edu/browse/FP-629)
1. Go to the tickets area and open up a ticket chain to check for the changes. Both the username and date should be included in the purple color
=> Task/FP-629 - Apply color signifying ticket responder to date and name

server/poetry.lock, server/pyproject.toml
Missed including gevent in the requirements for uwsgi running in deployed configurations.
* [FP-299](https://jira.tacc.utexas.edu/browse/FP-299)
=> hotfix for task/FP-299: add gevent

client/src/components/Onboarding/OnboardingUser.test.js, client/src/components/Workbench/Workbench.test.js, client/src/redux/reducers/systemMonitor.reducers.js, client/src/redux/reducers/tickets.reducers.js, client/src/redux/reducers/welcome.reducers.js
Add workbench unit tests to previous PR related to  FP-768
* [FP-768](https://jira.tacc.utexas.edu/browse/FP-768).
1. Run client side unit tests
=> Add workbench unit test

client/src/redux/sagas/authenticated_user.sagas.js
Fix fetchAuthenticatedUserUtil
* none
=> Fix fetchAuthenticatedUserUtil

client/src/components/Onboarding/OnboardingUser.js
=> task/FP-782 - Show Access Dashboard button always

client/src/components/FeedbackForm/FeedbackButton.js, client/src/components/FeedbackForm/FeedbackButton.module.scss, client/src/components/FeedbackForm/FeedbackButton.test.js, client/src/components/FeedbackForm/FeedbackForm.js, client/src/components/FeedbackForm/FeedbackForm.module.scss, client/src/components/FeedbackForm/FeedbackModal.js, client/src/components/FeedbackForm/FeedbackModal.module.scss
**Optional** rename of functions, variables, and classNames to be less verbose and more consistent. _This PR may be closed anyone for any reason—no problem._
* [FP-186](https://jira.tacc.utexas.edu/browse/FP-186)
1. Run `npm run test`, and expect no errors.
1. Load app, click feedback link, submit feedback.
1. See that **neither** styles **nor** functionality has changed.
See PR #201.
This PR _is **not**_ required for approval of PR #217.
=> (Optional) Task/fp 186 naming and cleanup

server/portal/views/base.py, server/portal/views/unit_test.py
Follow on to #256, this PR:
* improves tests
* adds some additional comments
* [FP-517](https://jira.tacc.utexas.edu/browse/FP-517)
1. improves tests (parameterize some things to simplify)
2. add some additional comments
1. run tests
2. confirm that there is still full coverage on views/base.py
=> FP-517 improve tests

client/src/components/Workbench/WelcomeMessages.js, client/src/components/Workbench/Workbench.js, client/src/components/Workbench/Workbench.test.js, client/src/redux/reducers/workbench.reducers.js, client/src/redux/sagas/workbench.sagas.js, server/portal/apps/workbench/api/unit_test.py, server/portal/apps/workbench/api/views.py, server/portal/settings/settings.py, server/portal/settings/settings_secret.example.py, server/portal/settings/unit_test_settings.py
Pass `WORKBENCH_SETTINGS ` secret setting to the frontend to configure visibility of certain UI elements.
* [FP-806](https://jira.tacc.utexas.edu/browse/FP-806)
- Refactor `WelcomeMessages` into its own component
- Show a `LoadingSpinner` when waiting for backend response
1. Add the following to your `settings_secret.py` file:
```
_WORKBENCH_SETTINGS = {
"debug": _DEBUG
}
```
Any feedback welcome with respect to the structure and naming of the object passed to the frontend.
=> task/FP-806: Workbench Config

client/src/components/Applications/AppForm/AppForm.test.js, client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.js, client/src/components/DataFiles/DataFilesModals/DataFilesSelectModal.js, client/src/components/DataFiles/DataFilesModals/tests/DataFilesCopyModal.test.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.js, client/src/components/DataFiles/DataFilesSidebar/DataFilesSidebar.js, client/src/components/DataFiles/DataFilesSystemSelector/DataFilesSystemSelector.js, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.js, client/src/components/DataFiles/fixtures/DataFiles.systems.fixture.js, client/src/redux/reducers/datafiles.reducers.js, client/src/utils/systems.js
Add project selector to Copy and Select modals.
* [FP-799](https://jira.tacc.utexas.edu/browse/FP-799)
1. Copy a file into a project
2. Select a file as an input to an application.
=> Task/FP-799:   Add projects to system selector.

client/src/components/DataFiles/DataFilesModals/DataFilesCopyModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesModalTables/DataFilesModalListingTable.js, client/src/components/DataFiles/DataFilesStatus/DataFilesStatus.js, client/src/redux/sagas/datafiles.sagas.js, client/src/redux/sagas/datafiles.sagas.test.js, server/portal/apps/datafiles/urls.py, server/portal/apps/datafiles/views.py, server/portal/libs/googledrive/operations.py
Opens a Toast notification for external resource integration data files events
1. Copy a file to/from google drive and see a toast with correct info
=> toasts for external integration data files events

.codecov.yml, .github/pull_request_template.md, Makefile, README.md
- Disables Codecov PR annotations
- Remove "PR Status" section of PR Template
- Add branch deploy docker tags
=> disable codecov annotations; pr template adjustment; branch deploys

client/src/components/DataFiles/DataFilesModals/DataFilesLinkModal.js, client/src/components/DataFiles/DataFilesModals/DataFilesLinkModal.module.scss
Fix according to feedback for FP-740 for testing session:
[Confluence](https://confluence.tacc.utexas.edu/pages/resumedraft.action?draftId=232456879&draftShareId=5bd86082-331c-48d2-a88a-8d2f036931e3&)
* [FP-740](https://jira.tacc.utexas.edu/browse/FP-740)
* [FP-814](https://jira.tacc.utexas.edu/browse/FP-814)
- Fix text color and spacing
- Fix button styles for confirm
1. Create a link for a file
2. Click the Delete or Replace button to view style changes
=> task/FP-814 - public url fixes from testing

client/src/components/DataFiles/DataFilesModals/DataFilesProjectEditDescriptionModal.js
Fix Yup validation message for empty project description
* [FP-824](https://jira.tacc.utexas.edu/browse/FP-824)
* [FP-843](https://jira.tacc.utexas.edu/browse/FP-843)
Made description field nullable to allow for empty description without validation error message
1. Change a project title and leave the description empty
=> bug/FP-843 - Shared Workspace description Yup validation message

server/portal/apps/onboarding/steps/access.py, server/portal/apps/onboarding/steps/allocation.py, server/portal/apps/onboarding/steps/mfa.py, server/portal/apps/onboarding/steps/project_membership.py, server/portal/apps/onboarding/steps/system_creation.py
Update onboarding step description texts
* [FP-832](https://jira.tacc.utexas.edu/browse/FP-832)
Change description texts as per ticket
1. Restart your containers
2. Go to cep.dev/workbench/onboarding/setup and verify text has changed
=> bug/FP-832 - Update onboarding step description texts

client/src/components/DataFiles/DataFilesModals/DataFilesCompressModal.js, client/src/redux/sagas/datafiles.sagas.js, server/portal/apps/workspace/api/views.py
Allow zip file names with spaces
* [FP-864](https://jira.tacc.utexas.edu/browse/FP-864)
- /api/workspace/apps endpoint now allows "name" query parameter, to search for apps by name
- getLatestApps utility function in datafiles.sagas.js specifies app query by name, rather than a full listing (results were getting truncated on the back end resulting in not finding new zippy apps)
- remove space replacement in form submission
- **new wrapper.sh in external repo** [portal-agave-templates](https://bitbucket.org/taccaci/portal-agave-templates/commits/0fc0e11a40a1622e39deb7404cff2c332ef4ff2a)
*This may be difficult*
I created a private zippy-jchuah-0.2 application that has the new wrapper script, for testing purposes. In general, the test method will be to instruct the front end and back end to …
=> task/FP-864 - Allow zipfiles with spaces

client/src/components/Toasts/Toast.js
Update ToastMessage to match FP-866 changes
* None.  Creating a follow on ticket as we should cover this area with unit test
* Update ToastMessage to match FP-866 changes
1. Upload a file
=> Hot fix:  update ToastMessage to match FP-866 changes

client/src/components/UIPatterns/UIPatterns.js, client/src/components/UIPatterns/UIPatternsPaginator/UIPatternsPaginator.js, client/src/components/UIPatterns/UIPatternsPaginator/index.js, client/src/components/_common/Paginator/Paginator.js, client/src/components/_common/Paginator/Paginator.module.scss, client/src/components/_common/Paginator/Paginator.test.js, client/src/components/_common/Paginator/index.js, client/src/components/_common/index.js
General pagination component
* [FP-802](https://jira.tacc.utexas.edu/browse/FP-802)
* [FP-877](https://jira.tacc.utexas.edu/browse/FP-877)
Add a paginator component with demo in UI-pattern
1. Test out the component in UI-Patterns
2. Only the first one supports callbacks for clicking on pages, the others are there just to show that it correctly displays available pages.
Design as part of [Onboarding Admin](https://xd.adobe.com/view/db2660cc-1011-4f26-5d31-019ce87c1fe8-ad17/screen/bd06dcf8-7744-474e-a155-93e3d28fa1a4)
=> task/FP-802 - Paginator component

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.js
Suggestion for handling back-to-all-files button in public-data
* [FP-899](https://jira.tacc.utexas.edu/browse/FP-899)
* https://github.com/TACC/Core-Portal/pull/366#discussion_r597271398
=> Handle back-to-all-files button in public-data

server/portal/apps/onboarding/steps/mfa.py
Fix typo: "multi-faction" → "multi-factor".
_**Update**: Also, fix spelling and add comma: "First setup" → "First, set up"._
N/A
* __Fix__: Typo in onboarding step description.
1. Load onboarding for user (may require [deleting user](https://github.com/TACC/Core-Portal/wiki/How-to-Delete-Your-User).)
2. Confirm text typo is fixed.
Before\
After First Fix\
After Second Fix\
=> Quick: Fix Onboarding MFA step desc. typo

client/src/components/Allocations/Allocations.scss, client/src/components/Allocations/AllocationsLayout.js, client/src/components/Allocations/AllocationsRoutes.js, client/src/components/Allocations/AllocationsTables.js, client/src/components/Applications/AppForm/AppForm.js, client/src/components/Applications/AppLayout/AppLayout.js, client/src/components/Dashboard/Dashboard.js, client/src/components/DataFiles/DataFiles.js, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.js, client/src/components/DataFiles/DataFilesProjectsList/DataFilesProjectsList.js, client/src/components/History/History.js, client/src/components/History/History.module.scss, client/src/components/ManageAccount/ManageAccount.js, client/src/components/ManageAccount/ManageAccountTables.js, client/src/components/Onboarding/OnboardingAdmin.module.scss, client/src/components/Onboarding/OnboardingUser.js, client/src/components/PublicData/PublicData.js, client/src/components/_common/Form/FormField.js, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss
Enable and fix all temporary disabled lint errors from https://github.com/TACC/Core-Portal/pull/350.
* [FP-962](https://jira.tacc.utexas.edu/browse/FP-962) (more importantly, though, is it's PR: #350)
- Remove `/* !!!: Temporary […] */` comments.
- Remove comments added to disable linting.
- Fix lint errors.
1. Compare the app on this branch to the target branch.
2. Confirm zero differences.
Skipped.
The only manual changes that could have been functional were those made to `InfiniteScrollTable` row styles, which still look as they did before. _N.b. For this screenshot, I temporarily changed the JavaScript code to show all types of rows in an `InfiniteScrollTable`._
- The JavaScript changes were _mostly_ done via `npm run lint:js -- --fix`.
- The CSS changes were _all_ done manually.
=> Task/fp 962 f.k.a. fp 385 section comp welcome msg  sections  lint fixes

client/src/components/Allocations/Allocations.global.css, client/src/components/Allocations/Allocations.scss, client/src/components/Allocations/AllocationsTables.js, client/src/components/Allocations/AllocationsTables.module.scss, client/src/components/Dashboard/Dashboard.module.css, client/src/components/DataFiles/DataFiles.global.css, client/src/components/DataFiles/DataFilesModals/DataFilesModals.scss, client/src/components/DataFiles/DataFilesProjectFileListing/DataFilesProjectFileListing.module.scss, client/src/components/DataFiles/DataFilesProjectMembers/DataFilesProjectMembers.scss, client/src/components/DataFiles/DataFilesTable/DataFilesTable.scss, client/src/components/DataFiles/DataFilesToolbar/DataFilesToolbar.scss, client/src/components/Jobs/Jobs.scss, client/src/components/ManageAccount/ManageAccount.scss, client/src/components/ManageAccount/ManageAccountTables.js, client/src/components/SystemMonitor/SystemMonitor.css, client/src/components/SystemMonitor/SystemMonitor.js, client/src/components/SystemMonitor/SystemMonitor.module.scss, client/src/components/SystemMonitor/SystemMonitorCells.js, client/src/components/Tickets/TicketsLayout.scss, client/src/components/_common/InfiniteScrollTable/InfiniteScrollTable.scss, client/src/components/_common/Pill/Pill.js, client/src/components/_common/Pill/Pill.module.scss
* [FP-962](https://jira.tacc.utexas.edu/browse/FP-962) (more importantly, though, is it's PR: #350)
- __New__: Update table font size (and related elements) to 14px.
- __Fix__: Update table column widths (and related elements) to adapt to larger font.
<details>
<summary>Details</summary>
- __New__: Change size of Allocation Badges
- _Minor_: Remove redundant overwrite from Data Files Modals CSS
- __New__: Change size of Data Files Project Description
- _Minor_: Inherit size for Data Files Project Member List
- __New__: Change size for Data Files Tables
- __New__: (Bonus) Change size of Data Files Header Actions
- __New__: Change size of Manage Account "Tables"
- __New__: (Related) Change size of Manage Account "Last Changed […]" note in "Table"
- __New__: Change size of System Monitor …
=> Task/fp 385 section comp welcome msg  sections  table font size

client/src/components/Applications/AppForm/AppForm.js
This should remove any null or blank form inputs in the job submission form. If there is anything else we should check for, let me know and I'll get it updated.
* [FP-1000](https://jira.tacc.utexas.edu/browse/FP-1000)
1. You may have to set the conditional to `false` on the input requirement settings in [AppFormSchema.js](https://github.com/TACC/Core-Portal/blob/main/client/src/components/Applications/AppForm/AppFormSchema.js#L110)
2. Once you've done this, submit a job like MatLab or Rstudio without filling in the working directory. You should see that the inputs object within the job submission log to be empty and not have something like `'workingDirectory' : ''`
=> Task/FP-1000 - Remove falsy values from job submission

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.js, client/src/components/SiteSearch/SiteSearchListing/SiteSearchSearchbar/SiteSearchSearchbar.js
* [FP-1066](https://jira.tacc.utexas.edu/browse/FP-1066)
Added minlength=3 to search input field
1. Search in Data Files and make sure searches with one or two characters are not allowed, searches with no input should still process and produce the default data catalog
2. Test search box functionality is the same as above at the /search page
=> task/FP-1066: Enforce a minimum length of 3 characters for search query

server/portal/apps/projects/managers/base.py
Improve Projects Search
* [FP-1021](https://jira.tacc.utexas.edu/browse/FP-1021)
Shared Workspaces searching wasn't work properly. Fixing search Projects filtering.
1. Do some searching in My Data -> Shared Workspaces
Clear Shared Workspace search issue can't be reproduced.
=> Shared Workspace searching issue.

README.md
Adds information to the README about extra prerequisites for developing on Linux.
N/A
Adds instructions to README
1. Ensure that instructions works on linux?
N/A
=> Add instructions for setting ElasticSearch on Linux in README.

README.md
Tweak formatting and capitalization mistakes in `README.md`.
* N/A
- Fix one capitalization mistake.
- Fix formatting so notes are not interpreted as code blocks (but as additional content for bullet point).
1. Preview the changed formatting.
2. Confirm they are italics/emphasized text, not code.
N/A
[Background](https://tacc-team.slack.com/archives/GQW4Q8HLG/p1624563888051300?thread_ts=1624563661.050700&cid=GQW4Q8HLG)
=> Tweak to README.md (formatting)

server/portal/apps/auth/views.py, server/portal/apps/auth/views_unit_test.py
The allocation cache isn't being updated. This PR adds the update of the cache when users log in. See  [FP-1139](https://jira.tacc.utexas.edu/browse/FP-1139) for more details/background on the regression.
* [FP-1139](https://jira.tacc.utexas.edu/browse/FP-1139)
* Update allocations cache during login
**Simple test**
1. Login
2. Check for "Already onboarded, running non-onboarding steps (e.g. update cached allocation information)" in django log
**More extensive testing**
1. Setup your ES indexes in README.md
2. Login and see your allocations (https://cep.dev/workbench/allocations/approved)
3. Update  `server/portal/apps/users/utils.py` so you limit the tas-derived list of allocations by changing line 69 to `for tas_proj in tas_projects[:2]:`.  Restart the worker so that it has the change …
=> bug/FP-1139: Update allocations cache during login

server/portal/apps/onboarding/steps/allocation.py, server/portal/apps/onboarding/steps/key_service_creation.py, server/portal/apps/onboarding/steps/system_creation.py
* [FP-123](https://jira.tacc.utexas.edu/browse/FP-1004)
Updated wording as requested in linked Jira ticket.
1. Navigate to workbench/onboarding/setup to verify changes are satisfactory.
=> Small changes to the onboarding step wording, as requested in FP-1004

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.js, client/src/components/SiteSearch/SiteSearchListing/SiteSearchListing.js
Fixes a site search bug when switching from 'cms' site search to 'public' or 'community' site search, introduced by me in https://github.com/TACC/Core-Portal/pull/455.
* [FP-1080](https://jira.tacc.utexas.edu/browse/FP-1080)
* [FP-508](https://jira.tacc.utexas.edu/browse/FP-508)
1. Submit a site search, with results
2. Switch from the 'cms' tab to the 'public' tab, and confirm the client does not crash. (It should crash on the main branch)
=> fix/FP-1080: Fix site search bug

client/src/components/Allocations/AllocationsCells.js, client/src/components/Allocations/AllocationsModals/AllocationsManageTeamModal/AllocationsManageTeamModal.js, client/src/components/Allocations/AllocationsModals/AllocationsModals.test.js, client/src/components/Allocations/AllocationsModals/AllocationsTeamViewModal/AllocationsTeamViewModal.js, client/src/components/_common/UserSearchbar/UserSearchbar.js, client/src/components/_common/UserSearchbar/UserSearchbar.module.scss, client/src/components/_common/UserSearchbar/index.js, client/src/components/_common/index.js, client/src/redux/reducers/allocations.reducers.js
- Create and implement a common `UserSearch` component for searching for users
- The search component for Allocations uses the TAS user search endpoint, but the query must be an exact match for a username
* [FP-737](https://jira.tacc.utexas.edu/browse/FP-737)
* [FP-1180](https://jira.tacc.utexas.edu/browse/FP-1180)
1. Go to https://cep.dev/workbench/allocations/approved and click Manage Team -> search for a user
=> task/FP-737, task/FP-1180: Use Search component from Projects

client/package-lock.json, client/package.json, client/src/components/Allocations/AllocationsModals/AllocationsManageTeamModal/AllocationsManageTeamModal.js, client/src/components/_common/UserSearchbar/UserSearchbar.js, client/src/redux/sagas/allocations.sagas.js, client/src/utils/fetchUtil.js
A single term is used to find a unique set of results against the `username`, `lastName`, and `email` fields in TAS.
* [FP-1190](https://jira.tacc.utexas.edu/browse/FP-1190)
* [FP-737](https://jira.tacc.utexas.edu/browse/FP-737)
- unified search
- allow overriding of `fetchParams` in `fetchUtil`
1. Search for a `franklin`
2. look at requests and see they add up to 12
3. See that there are only 11 listed in dropdown (no duplicates, a unique set)
=> task/FP-1190: Unified search for FP-737

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.js
Update search text when not enough characters
* [FP-1096](https://jira.tacc.utexas.edu/browse/FP-1096)
Updated the text letting users know they don't have enough characters to start a search for my data section.
1. Go to My Account
2. Go to Data File.
3. Go to My Data
4. Search any character with less than 3 on Data File Searchbar
5. Check if warning message match with "Include at least 3 characters in your search."
=> task/FP-1096 Update search text when not enough characters

client/src/components/DataFiles/DataFilesTable/DataFilesTable.scss
Added a hover effect to Data Files
* [FP-1264](https://jira.tacc.utexas.edu/browse/FP-1264)
Hover effect was added to Data Files
1. Check example video for result
https://user-images.githubusercontent.com/76450787/139488389-87ff7ba8-84dd-49fc-a30c-8f9a0ad0ebf1.mov
Spoke with Design to make sure this was the correct color effect wanted.
=> task/FP-1264 Added hover effect to Data Files

client/src/components/ManageAccount/ManageAccount.js, client/src/components/ManageAccount/ManageAccount.scss
Option to move the error message to the top of the page
1.
=> Moving error message to top of the page

README.md
Update README for server testing
* [FP-1308](https://jira.tacc.utexas.edu/browse/FP-1308)
updated readme for outdated method server testing
1.
=> task/FP-1308 Update README for server testing

client/src/components/Applications/AppForm/AppFormUtils.js
1. Navigate to Joe's AlphaFold app
2. Select the Brainmap allocation and different queues, and check that the submit button works.
=> Fix job validation when maxNodes > processorsPerNode

client/src/components/Allocations/AllocationsModals/AllocationsManageTeamModal/AllocationsManageTeamModal.js, client/src/components/Allocations/tests/AllocationsManageTeamModal.test.js, client/src/components/Allocations/tests/AllocationsTables.test.js
Added unit tests for basic display components for team management
* [FP-1181](https://jira.tacc.utexas.edu/browse/FP-1181)
* [FP-737](https://jira.tacc.utexas.edu/browse/FP-737)
Fixed failing allocations unit tests and added basic unit tests
From the client directory, run `jest src/components/Allocations/tests
This PR doesn't include user events in the component. Additionally, redux tests aren't updated to reflect this feature.
=> Task/FP-1181: Basic unit tests for front-end components

client/src/components/ManageAccount/ManageAccountTables.jsx, client/src/components/Workbench/AppRouter.jsx, client/src/components/Workbench/index.test.js
- Fixes a typo in the Orcid Id link
- Fixes a race condition preventing saved intro messages from being fetched
* [FP-1420](https://jira.tacc.utexas.edu/browse/FP-1420)
* [FP-1425](https://jira.tacc.utexas.edu/browse/FP-1425)
1. Enter this in your "Orcid ID" field on your account: `0000-0001-7554-8044`
2. Ensure the link takes you to orcid.org
3. Close a welcome message
4. Ensure that the message stays closed on page refresh
=> bug/FP-1420, bug/FP-1425: Fix non-persistent Welcome Message state; Fix Orcid ID link

client/src/components/History/HistoryViews/JobHistoryModal.jsx
=> bug/FP-1429: fix styling on 'Resubmit Job' button

server/portal/apps/googledrive_integration/views.py, server/portal/apps/public_data/views.py, server/portal/apps/request_access/views.py
Fixes a bug crashing unauthed view of /public data and /googledrive-privacy-policy
* [FP-1447](https://jira.tacc.utexas.edu/browse/FP-1447)
1. Ensure you are logged off
2. Go to https://cep.dev/public-data/ and ensure it does provides functionality as expected
=> hotfix/FP-1447: handle anonymous users in data context

client/src/styles/settings/color.css
- Clean up CSS comment from FP-1082.
- Update CSS comment for FP-1613.
* [FP-1082](https://jira.tacc.utexas.edu/browse/FP-1082): Link Text Color Contrast Fail - 3 Implement Fix with Variables
* [FP-1613](https://jira.tacc.utexas.edu/browse/FP-1613): Use Global Color Vars - Opaque Gray not Translucent Gray
N/A
=> Quick: Clean up FP-1082 & Prep for FP-1613

README.md
Add prettier check/fix commands to README
None
=> Add prettier check/fix commands

client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.jsx, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.module.scss, client/src/components/DataFiles/DataFilesSearchbar/DataFilesSearchbar.test.js, client/src/components/SiteSearch/SiteSearch.jsx, client/src/components/SiteSearch/SiteSearchSidebar/SiteSearchSidebar.jsx, client/src/components/SiteSearch/SiteSearchSidebar/SiteSearchSidebar.scss, client/src/components/SiteSearch/SiteSearchSidebar/SiteSearchSidebar.test.js, client/src/components/_common/Pill/Pill.jsx
In [FP-1566](https://jira.tacc.utexas.edu/browse/FP-1566), it was noted that we briefly show 0 results when searching in DataFiles.  In working on this PR, I noticed that we show also the most recent count result in site-level search while performing the search.  This PR addresses those two issues:
* hide count in site-level search until we have the search results.
* hide results in DataFiles until we have the search results.
* [FP-1566](https://jira.tacc.utexas.edu/browse/FP-1566)
* hide count in site-level search until we have the search results.
* hide results in DataFiles until we have the search results.
* Add related unit tests
If you want to, you can add some sleep statements (i.e. `import time; time.sleep(2)`) to allow you to better see things:
* in the `tapis_get_handler` in …
=> task/FP-1566: fix early search results display

CHANGELOG.md, client/src/components/Sidebar/Sidebar.jsx, client/src/components/Sidebar/Sidebar.test.js, client/src/components/Workbench/Workbench.jsx, server/portal/settings/settings_custom.example.py
Add support for "hideAllocations" setting
* [FP-1643](https://jira.tacc.utexas.edu/browse/FP-1643)
- Add hideAllocations setting to _WORKBENCH_SETTINGS (in setting_customs.example.py)
- Add hidden flag for hideAllocations
- Add hideAllocations to unit testing for hidden components
1. In your settings_custom.py _WORKBENCH_SETTINGS add `"hideAllocations": True`
2. Log in and make sure you do not see Allocations in the sidebar
=> task/FP-1643 -- toggle allocations setting

client/src/components/_common/SystemsPushKeysModal/SystemsPushKeysModal.jsx
There was an undefined variable `buttonIcon` breaking render of the modal.
* [FP-1836](https://jira.tacc.utexas.edu/browse/FP-1836)
1. Checkout this branch
2. Have everything running locally (`make start` and `npm run dev`)
3. Have ngrok running and configured locally
4. Submit any app
5. Confirm you get the `SystemPushKeysModal` prompting you for your TACC Token and password
6. Confirm you can push keys and submit a job
=> hotfix/FP-1836: Fix SystemPushKeysModal

.github/workflows/main.yml, client/src/components/Allocations/AllocationsModals/AllocationsModals.test.js, client/src/components/Allocations/AllocationsModals/AllocationsRequestModal/AllocationsRequestModal.jsx
Update xras link for requesting new allocations
* [FP-1856](https://jira.tacc.utexas.edu/browse/FP-1856)
1. Go to https://cep.test/workbench/allocations/approved/manage
2. Confirm link is updated
=> task/FP-1856: update xras link for requesting new allocations

client/src/components/Tickets/TicketCreateForm.jsx, server/portal/settings/settings_custom.example.py, server/portal/settings/settings_default.py
* Ticket attachment size and message as setting values.
* Update client/src/components/Tickets/TicketCreateForm.jsx
Co-authored-by: Sal Tijerina <r.sal.tijerina@gmail.com>
* Linting.
Co-authored-by: Sal Tijerina <r.sal.tijerina@gmail.com>
1.
=> task/FP-1951: Configurable Ticket Attachment Size (#754)

client/src/components/History/HistoryViews/JobHistoryModal.jsx, client/src/components/History/HistoryViews/tests/JobHistoryModal.test.js, client/src/components/Jobs/Jobs.jsx
=> Task/tv3 93 v2 historical jobs  minor tweaks

client/src/styles/elements/text-semantics.css, client/src/styles/global.css
Move new global CSS to appropriate stylesheet.
* [TV3-176](https://jira.tacc.utexas.edu/browse/TV3-176)
* updates #812
* **changed** location of new styles
1. Verify links with monospace code added in [#812](https://github.com/TACC/Core-Portal/pull/812/) are purple, not blue.
Skipped. (I accept the punishment.)
=> Task/tv3 176  advanced app form view  tweak

server/portal/apps/signals/receivers.py
After the upgrade to Django 3.2, the SetupEvent `save()` signal was being prevented to being passed to the websocket, breaking Onboarding notifications.
* [WP-191](https://jira.tacc.utexas.edu/browse/WP-191)
1. Set yourself as [staff](https://github.com/TACC/Core-Portal/wiki/How-to-Set-Your-User-as-Staff-or-Superuser)
2. Go to https://cep.test/workbench/onboarding/admin
3. Reset your System Access step and confirm you see the state change
=> bug/WP-191: Fix SetupEvent not sending websocket notifications

README.md
Fix this typo that's been bugging me for years.
- [~~prequisite~~](https://www.merriam-webster.com/dictionary/prequisite)
- [**prerequisite**](https://www.merriam-webster.com/dictionary/prerequisite)
- **fixed** typo
N/A
=> docs(README): prequisites to prerequisites

server/conf/docker/Dockerfile
Update `POETRY_VERSION=1.8.2` in the Dockerfile
[Built](https://jenkins.portals.tacc.utexas.edu/job/Core_Portal_Build/5/console) and [deployed](https://jenkins.portals.tacc.utexas.edu/job/Core_Portal_Deploy/default/105/console) to https://dev.cep.tacc.utexas.edu/
=> Quick: update poetry to 1.8.2

server/portal/apps/users/tas_to_tacc_resources.json, server/portal/settings/settings.py
Update tas to tacc resources json to include vista. When tas is ready, just need to update settings.
[WP-833](https://tacc-main.atlassian.net/browse/WP-833)
1. does not break app. tas does not have vista yet, so no other testing.
=> task/wp-833: resource json update to include vista

server/poetry.lock, server/portal/apps/_custom/drp/models.py, server/portal/apps/projects/tasks.py, server/portal/apps/projects/views.py, server/portal/libs/agave/operations.py, server/portal/libs/files/file_processing.py, server/pyproject.toml
Adds Image processing functionality that runs on upload and whenever the metadata is updated
* [WC-156](https://tacc-main.atlassian.net/browse/WC-156)
[Sample File](https://utexas.box.com/s/1ekx0n4gvls0ozpntk1ove3w98w16jg1) 
1. Replace settings_forms.py file with the updated file from [here](https://github.com/TACC/Core-Portal-Deployments/blob/main/digitalrocks/camino/settings_forms.py)
2. Upload sample file and use the following values for metadata: 
- Image Type: 8-bit
- Width: 600
- Height: 730
- Number of images: 170
- Byte Order: Big Endian
- Use Binary Correction: True
3. After successful upload wait a couple of mins and refresh the listing to see the processed image files
=> task/WC-156 - DRP Image Processing

client/src/components/DataFiles/DataFilesModals/DataFilesProjectEditDescriptionModal.jsx, client/src/components/DataFiles/DataFilesModals/DataFilesViewDataModal.jsx, client/src/components/_common/Form/DynamicForm/DynamicForm.jsx, client/src/components/_common/Form/DynamicForm/DynamicForm.module.scss, client/src/components/_common/Form/FormField.jsx, client/src/components/_common/Form/FormField.scss, client/src/components/_custom/drp/DataFilesProjectEditDescriptionModalAddon/DataFilesProjectEditDescriptionModalAddon.jsx, client/src/components/_custom/drp/DataFilesProjectEditDescriptionModalAddon/DataFilesProjectEditDescriptionModalAddon.module.scss, server/portal/apps/_custom/drp/models.py, server/portal/apps/projects/workspace_operations/project_meta_operations.py
Requested Changes to Edit Dataset view
* [WC-192](https://tacc-main.atlassian.net/browse/WC-192)
Change the following labels in the view:
1.
For Related Publications and Related Datasets, I commented out unused fields and repurposed other fields without changing the 'name'
I used the DesignSafe “Related Work” to model the  DR Related Publication and Designsafe “Referenced Data and Software“ to model the DR Related Datasets
=> Requested changes to Edit Dataset view

client/src/components/DataFiles/DataFilesModals/DataFilesFormModal.jsx, server/portal/apps/_custom/drp/models.py
Requested Changes [post-workshop] for the "Add Digital Dataset" View
* [WP-XYZ](https://tacc-main.atlassian.net/browse/WP-XYZ)
Add a list of descriptions for each field that needs to be populated: 
1.
I was unable to do the first description request. (Digital datasets should not contain any analysis results. If any kind of analysis is conducted on the dataset and is included in the data, it should be listed under the analysis dataset (see next section).)
=> Add digital_dataset and description fields to DrpOriginDatasetMetadata

client/src/components/DataFiles/DataFilesModals/DataFilesPreviewModal.module.scss, client/src/components/DataFiles/DataFilesModals/DataFilesUploadModalListing/DataFilesUploadModalListingTable.jsx, client/src/components/_custom/drp/DataFilesPreviewModalAddon/DataFilesPreviewModalAddon.jsx, client/src/components/_custom/drp/DataFilesPreviewModalAddon/DataFilesPreviewModalAddon.module.scss, client/src/components/_custom/drp/DataFilesUploadModalAddon/DataFilesUploadModalAddon.jsx, client/src/components/_custom/drp/DataFilesUploadModalListingTableAddon/DataFilesUploadModalListingTableAddon.jsx, client/src/components/_custom/drp/DataFilesUploadModalListingTableAddon/DataFilesUploadModalListingTableAddon.module.scss, client/src/hooks/datafiles/mutations/useUpload.ts, server/portal/apps/_custom/drp/models.py, server/portal/apps/projects/management/commands/migrate_drp_project_metadata.py, server/portal/apps/projects/tasks.py, server/portal/apps/projects/views.py, server/portal/libs/agave/operations.py, server/portal/settings/settings_default.py
Adds advanced image tag for an image for finer metadata control
* [WC-226](https://tacc-main.atlassian.net/browse/WC-226)
=> task/WC-226 - DRP Image Processing Refactor

server/conf/nginx/nginx.conf, server/portal/settings/settings.py, server/portal/settings/settings_default.py, server/portal/urls.py
- Fix local staticfiles settings and paths
- Disable strict cookies when debug is true
1. Confirm put/post methods work locally
2. Confirm static assets are loading at /core/admin
=> Quick: local settings fixes
